export type LessonTopic = {
  ar: string;
  en: string;
};

export type GradeLessonGroup = {
  slug: string;
  grade: number;
  year: number;
  title: string;
  topics: LessonTopic[];
};

export const uaeCurriculumGrades: GradeLessonGroup[] = [
  {
    slug: "grade-1-year-2",
    grade: 1,
    year: 2,
    title: "Grade1/Year2",
    topics: [
      { ar: "اللهُ رَبّي", en: "Allah Is My Lord" },
      { ar: "سورة الفاتِحة", en: "Surat Al-Fatihah" },
      { ar: "الصِّدْقُ طَريقُ الْجَنَّةِ", en: "Truthfulness Is the Path to Paradise" },
      { ar: "أركان الإسلامِ", en: "The Pillars of Islam" },
      { ar: "سورةُ الْفيلِ", en: "Surat Al-Fil" },
      { ar: "مَوْلِدُ الرَّسولِ مُحمَّد ﷺ", en: "The Birth of the Prophet Muhammad ﷺ" },
      { ar: "اللهُ الرَّحمنُ", en: "Allah, The Most Merciful" },
      { ar: "سورةُ الْفَلقِ", en: "Surat Al-Falaq" },
      { ar: "دُعاءُ النَّومِ", en: "The Supplication Before Sleep" },
      { ar: "أبو هُرَيرةَ رضي الله عنه", en: "Abu Hurairah, May Allah Be Pleased with Him" },
      { ar: "الوضوءُ", en: "Wudu" },
      { ar: "الرَّحْمَة بِالْحَيَوانِ", en: "Mercy to Animals" },
      { ar: "سورة الإخلاص", en: "Surat Al-Ikhlas" },
      { ar: "أركان الإیمانِ", en: "The Pillars of Faith" },
      { ar: "آدابُ النَّظافَة في الإسلام", en: "Cleanliness Etiquette in Islam" },
      { ar: "المسلم عون لأخیه", en: "A Muslim Helps His Brother" },
      { ar: "أحبُ أسرتي", en: "I Love My Family" },
      { ar: "رسولنا مُحَمَّد ﷺ في رِعایَةِ جَدِّهِ وَعَمّهِ", en: "Our Prophet Muhammad ﷺ Under the Care of His Grandfather and Uncle" },
      { ar: "اللهُ الْخالِقُ الْعَظيمْ", en: "Allah, The Great Creator" },
      { ar: "سورة الناس", en: "Surat An-Nas" },
      { ar: "صلاتي نور حياتي", en: "My Prayer Is the Light of My Life" },
      { ar: "الْبِرُّ حُسْنُ الْخُلْقِ", en: "Righteousness Is Good Character" },
      { ar: "سورةُ الْماعونِ", en: "Surat Al-Ma'un" },
      { ar: "أحب مخلوقات ربي", en: "I Love the Creatures of My Lord" },
      { ar: "سورة الكوثر", en: "Surat Al-Kawthar" },
      { ar: "أسماء بنت أبي بكر الصديق رضي الله عنهما", en: "Asma bint Abi Bakr, May Allah Be Pleased with Them" },
      { ar: "من آداب الطعام", en: "Etiquette of Eating" },
      { ar: "حديث الرحمة", en: "The Hadith of Mercy" },
      { ar: "التسامح", en: "Tolerance" },
      { ar: "أحب الزراعة", en: "I Love Planting" },
      { ar: "خيركم من تعلم القرآن وعلمه", en: "The Best of You Learn and Teach the Quran" },
      { ar: "سورة النصر", en: "Surat An-Nasr" },
    ],
  },
  {
    slug: "grade-2-year-3",
    grade: 2,
    year: 3,
    title: "Grade2/Year3",
    topics: [
      { ar: "اللهُ اللَّطيفُ الخَبيرُ", en: "Allah, The Gentle and All-Aware" },
      { ar: "آية الكرسي", en: "Ayat Al-Kursi" },
      { ar: "الإيمان بالرُسُلِ", en: "Belief in the Messengers" },
      { ar: "سورَة العصرِ", en: "Surat Al-Asr" },
      { ar: "أحبُّ الخَيْرَ لأخي", en: "I Love Good for My Brother" },
      { ar: "الطَّهارَةُ وَنَواقِضُ الوُضوءِ", en: "Purification and Things That Break Wudu" },
      { ar: "فَنٌ وَابتِكار إسلامِي", en: "Islamic Art and Creativity" },
      { ar: "سورَةُ الشّرْح", en: "Surat Ash-Sharh" },
      { ar: "الرَّسول ﷺ يُحِبُ الْعَمَلَ", en: "The Prophet ﷺ Loves Work" },
      { ar: "حُسْنُ الوضوءِ", en: "Perfecting Wudu" },
      { ar: "عَلِي بْنُ أَبي طالِب رضي الله عنه", en: "Ali ibn Abi Talib, May Allah Be Pleased with Him" },
      { ar: "فَضْلُ تلاوة القُرآنِ الكریمِ", en: "The Virtue of Reciting the Noble Quran" },
      { ar: "سورةُ القَّدْرِ", en: "Surat Al-Qadr" },
      { ar: "السَّيِّدَةُ فاطِمَةُ رضي الله عنها", en: "Lady Fatimah, May Allah Be Pleased with Her" },
      { ar: "سورةُ الضُّحى", en: "Surat Ad-Duha" },
      { ar: "آدابُ الطَّعامِ", en: "Food Etiquette" },
      { ar: "خَيْرُ الأعْمالِ في الإسْلامِ", en: "The Best Deeds in Islam" },
      { ar: "الله الخالق القديرُ", en: "Allah, The Powerful Creator" },
      { ar: "مِنْ أَخْلاقِ المُسلِمِ", en: "From the Character of a Muslim" },
      { ar: "مِنْ أَخلاقِ النبيّ ﷺ", en: "From the Character of the Prophet ﷺ" },
      { ar: "سورةُ الشَّمْسِ", en: "Surat Ash-Shams" },
      { ar: "احترامُ الآخَرين", en: "Respecting Others" },
      { ar: "الصَّلاةُ عَلى النَّبِيِّ ﷺ", en: "Sending Blessings Upon the Prophet ﷺ" },
      { ar: "سورةُ التُكاثرِ", en: "Surat At-Takathur" },
      { ar: "نِعْمَةُ الثَّبات", en: "The Blessing of Steadfastness" },
      { ar: "كُلُّ أُمَّتي يَدْخُلونَ الجَنَّةَ", en: "All of My Ummah Will Enter Paradise" },
      { ar: "أحبُّ جيراني", en: "I Love My Neighbors" },
      { ar: "سورةُ العادِياتِ", en: "Surat Al-Adiyat" },
    ],
  },
  {
    slug: "grade-3-year-4",
    grade: 3,
    year: 4,
    title: "Grade3/Year4",
    topics: [
      { ar: "بِرُّ الوالِدَيْنِ", en: "Honoring Parents" },
      { ar: "آدابُ التَّلاوَةِ", en: "Etiquette of Quran Recitation" },
      { ar: "نزولُ الوَحْي عَلى النَّبِيِّ مُحَمَّدٍ ﷺ", en: "The Descent of Revelation Upon Prophet Muhammad ﷺ" },
      { ar: "سورَةَ العَلق", en: "Surat Al-Alaq" },
      { ar: "خَديجَةُ بِنْتُ خُوَيْلِدٍ رضي الله عنها", en: "Khadijah bint Khuwaylid, May Allah Be Pleased with Her" },
      { ar: "حُسْنُ الخُلْقِ", en: "Good Character" },
      { ar: "الإيمانَّ بِالمَلائِكَةِ", en: "Belief in the Angels" },
      { ar: "سورَةُ البَيِّنَةِ", en: "Surat Al-Bayyinah" },
      { ar: "شُروطُ الصَّلاةِ وَمُبْطِلاتُها", en: "Conditions of Prayer and What Invalidates It" },
      { ar: "فَضْلُ تَرتيلِ القُرْآنِ الكَريمِ", en: "The Virtue of Reciting the Quran Beautifully" },
      { ar: "الأذانُ وَالإقامَةُ", en: "The Adhan and Iqamah" },
      { ar: "مُكَفّراتُ الذُّنوبِ", en: "Expiations for Sins" },
      { ar: "آدابُ الزِّيارَةِ وَالضَّيافَةِ", en: "Etiquette of Visiting and Hosting" },
      { ar: "الصَّوْمُ", en: "Fasting" },
      { ar: "سورَةُ الهُمَزَّةِ", en: "Surat Al-Humazah" },
      { ar: "صِفاتُ المُؤْمِنِ", en: "Qualities of the Believer" },
      { ar: "سورَةُ اللَّيْلِ", en: "Surat Al-Layl" },
      { ar: "التَّسامُحُ", en: "Tolerance" },
      { ar: "العِلْمُ وَالمَعْرِفَةُ", en: "Knowledge and Learning" },
      { ar: "أَبو بَكر الصَّدّيقُ", en: "Abu Bakr As-Siddiq" },
      { ar: "سورَةُ الفَجْرِ", en: "Surat Al-Fajr" },
      { ar: "الصِّدْقُ", en: "Truthfulness" },
      { ar: "الإيمانُ بِالرُّسلِ (موسى وَعيسى)", en: "Belief in the Messengers (Musa and Isa)" },
      { ar: "البَحْثُ عَنِ المَعْرِفَةِ", en: "Seeking Knowledge" },
      { ar: "سورة البلد", en: "Surat Al-Balad" },
      { ar: "التعاون سر النجاح", en: "Cooperation Is the Secret of Success" },
      { ar: "التراحم رعاية المحتاجين", en: "Compassion and Caring for Those in Need" },
      { ar: "العمل الصالح (سورة الذاريات 15-23)", en: "Righteous Deeds (Surat Adh-Dhariyat 15-23)" },
      { ar: "صلة الأرحام", en: "Maintaining Family Ties" },
      { ar: "نعمة الماء", en: "The Blessing of Water" },
      { ar: "الموعظة الحسنة (سورة النحل 125-128)", en: "Gentle Preaching (Surat An-Nahl 125-128)" },
      { ar: "الرسول صلى الله عليه وسلم يحب جيرانه", en: "The Prophet ﷺ Loved His Neighbors" },
      { ar: "تذوق الإيمان", en: "Tasting the Sweetness of Faith" },
    ],
  },
  {
    slug: "grade-4-year-5",
    grade: 4,
    year: 5,
    title: "Grade4/Year5",
    topics: [
      { ar: "آداب الدخول والخروج من المنزل", en: "Etiquette of Entering and Leaving the Home" },
      { ar: "سورة البروج (1)", en: "Surat Al-Buruj (1)" },
      { ar: "من أحكام التجويد: القلقلة", en: "Tajwid Rules: Qalqalah" },
      { ar: "المؤمن القوي", en: "The Strong Believer" },
      { ar: "بدء الدعوة إلى الإسلام", en: "The Beginning of the Call to Islam" },
      { ar: "أم المساكين السيدة زينب بنت خزيمة رضي الله عنها", en: "Umm Al-Masakin Zaynab bint Khuzaymah, May Allah Be Pleased with Her" },
      { ar: "الإيمان بالكتب السماوية", en: "Belief in the Heavenly Books" },
      { ar: "سورة الطارق", en: "Surat At-Tariq" },
      { ar: "التثبت من الأخبار", en: "Verifying News" },
      { ar: "أهمية الصلاة المفروضة وآدابها", en: "The Importance of Obligatory Prayer and Its Etiquette" },
      { ar: "أحسنكم أخلاقا", en: "The Best of You in Character" },
      { ar: "السنن الرواتب", en: "The Regular Sunnah Prayers" },
      { ar: "الهجرة إلى الحبشة", en: "Migration to Abyssinia" },
      { ar: "حسن المعاملة", en: "Good Treatment of Others" },
      { ar: "سورة الأعلى", en: "Surat Al-A'la" },
      { ar: "صلاة الجماعة", en: "Congregational Prayer" },
      { ar: "سورة الغاشية", en: "Surat Al-Ghashiyah" },
      { ar: "البحث والتفكير العلمي", en: "Research and Scientific Thinking" },
      { ar: "حمد الله تعالى على نعمه", en: "Praising Allah for His Blessings" },
      { ar: "عام الحزن", en: "The Year of Sorrow" },
      { ar: "أخلاق المتقين", en: "The Character of the God-Fearing" },
      { ar: "صبر النبي", en: "The Patience of the Prophet" },
      { ar: "سورة الانشقاق", en: "Surat Al-Inshiqaq" },
      { ar: "المرافق العامة", en: "Public Facilities" },
      { ar: "الرفق", en: "Gentleness" },
      { ar: "صيامي لربي", en: "My Fasting Is for My Lord" },
      { ar: "في ظل صدقتي", en: "Under the Shade of My Charity" },
      { ar: "سورة المطففين", en: "Surat Al-Mutaffifin" },
      { ar: "الكرم من كمال الإيمان", en: "Generosity Is Part of Complete Faith" },
      { ar: "بيئتي مسؤوليتي", en: "My Environment Is My Responsibility" },
      { ar: "ذو النورين عثمان بن عفان", en: "Dhun-Nurayn Uthman ibn Affan" },
    ],
  },
  {
    slug: "grade-5-year-6",
    grade: 5,
    year: 6,
    title: "Grade5/Year6",
    topics: [
      { ar: "سورة الانفطار", en: "Surat Al-Infitar" },
      { ar: "المفلس الحقيقي", en: "The Truly Bankrupt Person" },
      { ar: "أحب العمل إلى الله تعالى", en: "The Most Beloved Deeds to Allah" },
      { ar: "محبة الله تعالى", en: "Love of Allah" },
      { ar: "دعوة أهل الطائف", en: "The Call to the People of Ta'if" },
      { ar: "سورة التكوير", en: "Surat At-Takwir" },
      { ar: "الإحسان إلى الناس", en: "Doing Good to People" },
      { ar: "الإيمان باليوم الآخر", en: "Belief in the Last Day" },
      { ar: "صلاة الجماعة", en: "Congregational Prayer" },
      { ar: "الإسراء والمعراج", en: "Al-Isra' and Al-Mi'raj" },
      { ar: "سورة عبس", en: "Surat Abasa" },
      { ar: "القلقلة", en: "Qalqalah" },
      { ar: "القرآن شفيعي", en: "The Quran Is My Intercessor" },
      { ar: "آداب ركوب وسائل النقل", en: "Etiquette of Using Transportation" },
      { ar: "فاطمة بنت عبد الملك", en: "Fatimah bint Abd Al-Malik" },
      { ar: "القلب الرحيم", en: "The Merciful Heart" },
      { ar: "الرفق خير", en: "Gentleness Is Goodness" },
      { ar: "يسروا ولا تعسروا", en: "Make Things Easy and Do Not Make Them Hard" },
      { ar: "الهجرة إلى المدينة", en: "Migration to Madinah" },
      { ar: "الله القادر", en: "Allah, The All-Powerful" },
      { ar: "سورة النبأ (1-16)", en: "Surat An-Naba (1-16)" },
      { ar: "الطريق إلى الجنة", en: "The Road to Paradise" },
      { ar: "نعمة العقل", en: "The Blessing of Intellect" },
      { ar: "آداب الطريق", en: "Etiquette of the Road" },
      { ar: "صلاة الجمعة وصلاة العيدين", en: "Jumu'ah Prayer and Eid Prayers" },
      { ar: "سورة النازعات", en: "Surat An-Nazi'at" },
      { ar: "الله الحكم العدل", en: "Allah, The Judge and The Just" },
      { ar: "سورة النبأ (17-40)", en: "Surat An-Naba (17-40)" },
      { ar: "وجوه في الجنة", en: "Faces in Paradise" },
      { ar: "مع رسولي", en: "With My Messenger" },
      { ar: "الشجاعة", en: "Courage" },
      { ar: "عمر بن الخطاب", en: "Umar ibn Al-Khattab" },
      { ar: "الإنسان والكون", en: "Humanity and the Universe" },
    ],
  },
  {
    slug: "grade-6-year-7",
    grade: 6,
    year: 7,
    title: "Grade6/Year7",
    topics: [
      { ar: "الكِتابُ الحَقُّ (السجدة 1-12)", en: "The True Book (As-Sajdah 1-12)" },
      { ar: "مِنْ وَصايا الرَّسولِ ﷺ", en: "From the Advice of the Prophet ﷺ" },
      { ar: "التَّطَوُّعُ عِبادَةٌ وَانْتِماءُ", en: "Volunteering Is Worship and Belonging" },
      { ar: "حُرْمَةُ المُسْلِمِ", en: "The Sanctity of a Muslim" },
      { ar: "فَرائِضُ الصَّلاةِ وَسُنَنُها وَمَكْروهاتُها", en: "The Obligations, Sunnahs, and Disliked Acts of Prayer" },
      { ar: "الإِماراتُ في خِدْمَةِ العالَمِ", en: "The UAE in Service of the World" },
      { ar: "صِفاتُ المُؤْمِنِينَ وَجَزاؤُهُمْ (السجدة 13-22)", en: "The Qualities of Believers and Their Reward (As-Sajdah 13-22)" },
      { ar: "أَحْكامُ النَّونِ السّاكِنَةِ وَالتَّنْوينِ: الإِظْهارِ الحَلْقِيِّ", en: "Rules of Noon Sakinah and Tanwin: Clear Pronunciation" },
      { ar: "حاسِبوا أَنْفُسَكُمْ", en: "Take Account of Yourselves" },
      { ar: "آدابُ المَسْجد", en: "Etiquette of the Mosque" },
      { ar: "الحَياةُ في المَدينَةِ المُنَوَّرَةِ بَعْدَ الهِجْرَةِ", en: "Life in Madinah After the Migration" },
      { ar: "سُجودُ السَّهْوِ وَسُجودُ التَّلاوَةِ", en: "Sujud As-Sahw and Sujud At-Tilawah" },
      { ar: "الصَّبْرُ وَاليَقينُ (السَّجْدَةُ 23-30)", en: "Patience and Certainty (As-Sajdah 23-30)" },
      { ar: "حُكْمُ الإِذْغامِ", en: "The Rule of Idgham" },
      { ar: "المُؤْمِنُ بَيْنَ الشُّكْرِ وَالصَّبْرِ", en: "The Believer Between Gratitude and Patience" },
      { ar: "مِنْ عَلاماتِ السّاعَةِ", en: "From the Signs of the Hour" },
      { ar: "الإِمامُ مالِكُ بْنُ أَنَسِ", en: "Imam Malik ibn Anas" },
      { ar: "سَبيلُ الهِدايَةِ (المُلْك 1-14)", en: "The Path of Guidance (Al-Mulk 1-14)" },
      { ar: "الاِقْلابُ", en: "Iqlab" },
      { ar: "أَخْلاقٌ حَميدَةٌ", en: "Noble Character Traits" },
      { ar: "أَنا مُتَسامِحُ", en: "I Am Tolerant" },
      { ar: "غَزْوَةُ بَدْرِ الكُبْرى", en: "The Great Battle of Badr" },
      { ar: "قُدْرَةُ اللهِ تَعالى (المُلْك 15-24)", en: "The Power of Allah (Al-Mulk 15-24)" },
      { ar: "الإِخْفاءُ الحَقيقِيُّ", en: "True Ikhfa'" },
      { ar: "اخْتِيارُ الجَليسِ", en: "Choosing Companions" },
      { ar: "التَّفْكيرُ العِلْمِيُّ", en: "Scientific Thinking" },
      { ar: "غَزْوَةُ أُحدٍ", en: "The Battle of Uhud" },
      { ar: "بيئَتي أَمانَةٌ", en: "My Environment Is a Trust" },
      { ar: "دُروس وَعِبَرٌ (المُلْك 25-30)", en: "Lessons and Reflections (Al-Mulk 25-30)" },
      { ar: "يُسْرُ الإِسْلامِ", en: "The Ease of Islam" },
      { ar: "آدابُ الدُّعاءِ", en: "Etiquette of Supplication" },
      { ar: "صِيامُ التَّطَوُّعِ", en: "Voluntary Fasting" },
      { ar: "السَّيِّدَةُ عائِشَةُ أُمُّ المُؤْمِنينَ", en: "Lady Aishah, Mother of the Believers" },
    ],
  },
  {
    slug: "grade-7-year-8",
    grade: 7,
    year: 8,
    title: "Grade7/Year8",
    topics: [
      { ar: "البعث والنشور", en: "Resurrection and Rising Again" },
      { ar: "المستظلون في ظل الرحمن", en: "Those Shaded by the Most Merciful" },
      { ar: "من بشائر المصلين", en: "Glad Tidings for Those Who Pray" },
      { ar: "أدلة وحدانية الله تعالى", en: "Proofs of the Oneness of Allah" },
      { ar: "مراقبة الله تعالى", en: "Being Mindful of Allah" },
      { ar: "سنن الفطرة", en: "Practices of Natural Purity" },
      { ar: "الخلاق العليم", en: "The Creator, The All-Knowing" },
      { ar: "التوبة فرصة العمر", en: "Repentance Is the Opportunity of a Lifetime" },
      { ar: "المغيث الحليم جل جلاله", en: "The Helper, The Forbearing, Glorified Is He" },
      { ar: "الغسل", en: "Ghusl" },
      { ar: "التيمم والمسح على الخفين", en: "Tayammum and Wiping Over the Socks" },
      { ar: "غزوة الأحزاب", en: "The Battle of Al-Ahzab" },
      { ar: "سورة الرحمن (1-25)", en: "Surat Ar-Rahman (1-25)" },
      { ar: "القلب وصلاح الإنسان", en: "The Heart and Human Righteousness" },
      { ar: "الدين يسر", en: "Religion Is Ease" },
      { ar: "التفكر في الإسلام", en: "Reflection in Islam" },
      { ar: "العمل عبادة وحضارة", en: "Work Is Worship and Civilization" },
      { ar: "صلاة المسافر والمريض", en: "Prayer for the Traveler and the Sick" },
      { ar: "نعيم الحياة", en: "The Blessings of Life" },
      { ar: "كفالة اليتيم", en: "Caring for an Orphan" },
      { ar: "التواضع", en: "Humility" },
      { ar: "صلاة التطوع (الضحى والليل)", en: "Voluntary Prayer (Duha and Night Prayer)" },
      { ar: "جزاء الإحسان", en: "The Reward of Excellence" },
      { ar: "التعايش بين الناس", en: "Coexistence Among People" },
      { ar: "المجالس وآدابها", en: "Gatherings and Their Etiquette" },
      { ar: "السيدة رفيدة الأسلمية", en: "Lady Rufaydah Al-Aslamiyyah" },
      { ar: "الفقر في العالم الإسلامي", en: "Poverty in the Islamic World" },
    ],
  },
  {
    slug: "grade-8-year-9",
    grade: 8,
    year: 9,
    title: "Grade8/Year9",
    topics: [
      { ar: "صدق الرسول صلى الله عليه وسلم", en: "The Truthfulness of the Messenger ﷺ" },
      { ar: "أحكام المد - أولاً المد الأصلي", en: "Rules of Madd: The Original Madd First" },
      { ar: "الأعمال بالنيات", en: "Actions Are by Intentions" },
      { ar: "الإخلاص", en: "Sincerity" },
      { ar: "الكسب الطيب", en: "Halal Earning" },
      { ar: "نعمة الأمن", en: "The Blessing of Security" },
      { ar: "أصحاب القرية من 13-19 سورة يس", en: "The People of the Town from Surah Ya-Sin 13-19" },
      { ar: "التقرب إلى الله تعالى", en: "Drawing Closer to Allah" },
      { ar: "الإيمان بالقضاء والقدر", en: "Belief in Divine Decree" },
      { ar: "الصلوات ذات الأسباب", en: "Prayers with Specific Causes" },
      { ar: "الشفاء بنت عبد الله العدوية", en: "Ash-Shifa bint Abdullah Al-Adawiyyah" },
      { ar: "قصة مؤمن آل يس", en: "The Story of the Believer of Ya-Sin" },
      { ar: "أقدس المساجد", en: "The Holiest Mosques" },
      { ar: "فتح مكة", en: "The Conquest of Makkah" },
      { ar: "آداب السفر", en: "Etiquette of Travel" },
      { ar: "أحكام العمرة", en: "Rules of Umrah" },
      { ar: "قدرة الله تعالى (سورة يس 33-54)", en: "The Power of Allah (Surah Ya-Sin 33-54)" },
      { ar: "المد الفرعي", en: "Secondary Madd" },
      { ar: "تلاحم المجتمع", en: "Social Unity" },
      { ar: "فضائل المؤمن", en: "Virtues of the Believer" },
      { ar: "حرمة ترويع الإنسان", en: "The Prohibition of Frightening a Person" },
      { ar: "أنا خيركم لأهلي", en: "I Am the Best of You to My Family" },
      { ar: "الطريق إلى الجنة (سورة يس 55-68)", en: "The Path to Paradise (Surah Ya-Sin 55-68)" },
      { ar: "الاقتداء في الخير", en: "Following Good Examples" },
      { ar: "الأيمان والنذور", en: "Oaths and Vows" },
      { ar: "غزوة حنين", en: "The Battle of Hunayn" },
      { ar: "صحتي مسؤوليتي", en: "My Health Is My Responsibility" },
      { ar: "أدلة وحدانية الله تعالى وقدرته (سورة يس 69-83)", en: "Proofs of the Oneness and Power of Allah (Surah Ya-Sin 69-83)" },
      { ar: "صلة الأرحام", en: "Maintaining Family Ties" },
      { ar: "العلم نور ورفعة", en: "Knowledge Is Light and Elevation" },
      { ar: "اقرأ باسم ربي", en: "Read in the Name of My Lord" },
      { ar: "الإمام الشافعي رحمه الله", en: "Imam Ash-Shafi'i, May Allah Have Mercy on Him" },
    ],
  },
  {
    slug: "grade-9-year-10",
    grade: 9,
    year: 10,
    title: "Grade9/Year10",
    topics: [
      { ar: "مع الله ورسوله وولي الأمر", en: "With Allah, His Messenger, and the Guardian of Authority" },
      { ar: "السبع الموبقات", en: "The Seven Destructive Sins" },
      { ar: "الغفور العدل سبحانه", en: "The Forgiving, The Just, Glorified Is He" },
      { ar: "التناصح في الإسلام", en: "Mutual Advice in Islam" },
      { ar: "الزكاة في الإسلام", en: "Zakat in Islam" },
      { ar: "سلامة المجتمع ووحدة أبنائه", en: "The Safety of Society and the Unity of Its People" },
      { ar: "الحلال بين", en: "The Halal Is Clear" },
      { ar: "الدين النصيحة", en: "Religion Is Sincere Advice" },
      { ar: "الحج", en: "Hajj" },
      { ar: "حجة الوداع ووفاة النبي ﷺ", en: "The Farewell Pilgrimage and the Death of the Prophet ﷺ" },
      { ar: "الإيمان فضل من الله تعالى", en: "Faith Is a Blessing from Allah" },
      { ar: "للمجتمع رجاله ونساؤه", en: "Society Has Both Men and Women" },
      { ar: "العدل في الإسلام", en: "Justice in Islam" },
      { ar: "ما يحل وما يحرم من الطعام والشراب", en: "What Is Lawful and Unlawful in Food and Drink" },
      { ar: "الإمام مسلم رحمه الله", en: "Imam Muslim, May Allah Have Mercy on Him" },
      { ar: "الأمن والأمان", en: "Security and Safety" },
    ],
  },
  {
    slug: "grade-10-year-11",
    grade: 10,
    year: 11,
    title: "Grade10/Year11",
    topics: [
      { ar: "سورة الكهف 1-8", en: "Surat Al-Kahf 1-8" },
      { ar: "القرآن المكي والمدني", en: "Makkan and Madinan Quran" },
      { ar: "العقل في الإسلام", en: "The Intellect in Islam" },
      { ar: "المدارس الفقهية", en: "Schools of Jurisprudence" },
      { ar: "سكينة بنت الحسين", en: "Sakinah bint Al-Husayn" },
      { ar: "أصحاب الكهف", en: "The People of the Cave" },
      { ar: "مراحل جمع القرآن", en: "Stages of Compiling the Quran" },
      { ar: "منهجية التفكير في الإسلام", en: "Methodology of Thinking in Islam" },
      { ar: "الوقف عطاء ونماء", en: "Waqf as Giving and Growth" },
      { ar: "التنمية البشرية في الإسلام", en: "Human Development in Islam" },
      { ar: "صاحب الجنتين", en: "The Companion of the Two Gardens" },
      { ar: "السنة النبوية", en: "The Prophetic Sunnah" },
      { ar: "آداب اللباس", en: "Etiquette of Clothing" },
      { ar: "اختلاف الفقهاء", en: "Differences Among Jurists" },
      { ar: "منهج النبي في الدعوة", en: "The Prophet’s Method in Dawah" },
      { ar: "الدنيا دار عمل", en: "This World Is the Abode of Action" },
      { ar: "تدوين السنة", en: "Recording the Sunnah" },
      { ar: "العفة", en: "Chastity" },
      { ar: "أحكام الزواج", en: "Rules of Marriage" },
      { ar: "رعاية الرسول ﷺ لأهل بيته", en: "The Prophet’s Care for His Household ﷺ" },
      { ar: "موسى نبي الله", en: "Musa, the Prophet of Allah" },
      { ar: "جهود العلماء في حفظ السنة", en: "The Efforts of Scholars in Preserving the Sunnah" },
      { ar: "الإيمان بالغيب", en: "Belief in the Unseen" },
      { ar: "طاعة ولي الأمر", en: "Obedience to the Guardian of Authority" },
      { ar: "ذو القرنين الرجل الصالح", en: "Dhul-Qarnayn, the Righteous Man" },
      { ar: "التسامح", en: "Tolerance" },
      { ar: "الجهاد في سبيل الله (الجزء الأول)", en: "Jihad in the Cause of Allah (Part One)" },
      { ar: "الجهاد في سبيل الله (الجزء الثاني)", en: "Jihad in the Cause of Allah (Part Two)" },
      { ar: "الشيخ أحمد بن عبد العزيز (قدوة معاصرة)", en: "Shaykh Ahmad bin Abdul Aziz (A Contemporary Role Model)" },
    ],
  },
  {
    slug: "grade-11-year-12",
    grade: 11,
    year: 12,
    title: "Grade11/Year12",
    topics: [
      { ar: "الثبات على الحق", en: "Steadfastness Upon the Truth" },
      { ar: "العقل والنقل", en: "Reason and Revelation" },
      { ar: "الاستعفاف", en: "Seeking Chastity" },
      { ar: "العقود المالية في الإسلام", en: "Financial Contracts in Islam" },
      { ar: "اللغة والثقافة العربية", en: "Arabic Language and Culture" },
      { ar: "غزوة الأحزاب (الخندق)", en: "The Battle of Al-Ahzab (The Trench)" },
      { ar: "القرآن الكريم والإعجاز العلمي", en: "The Noble Quran and Scientific Miracles" },
      { ar: "أدب الحوار", en: "The Etiquette of Dialogue" },
      { ar: "مصادر التشريع الإسلامي", en: "Sources of Islamic Legislation" },
      { ar: "معالم التخطيط في حياة الرسول صلى الله عليه وسلم", en: "Features of Planning in the Life of the Prophet ﷺ" },
      { ar: "الاقتداء برسول الله ﷺ", en: "Following the Example of the Messenger of Allah ﷺ" },
      { ar: "أقسام الحديث الشريف", en: "Categories of Hadith" },
      { ar: "منهج الإسلام في بناء الأسرة", en: "Islam’s Method in Building the Family" },
      { ar: "أم سلمة رضي الله عنها", en: "Umm Salamah, May Allah Be Pleased with Her" },
      { ar: "وصايا وتوجيهات أخلاقية", en: "Moral Advice and Guidance" },
      { ar: "أقسام الحديث الشريف 2", en: "Categories of Hadith 2" },
      { ar: "الشورى في الإسلام", en: "Consultation in Islam" },
      { ar: "القواعد الفقهية", en: "Legal Maxims" },
      { ar: "الاستدامة في المنهج الإسلامي", en: "Sustainability in the Islamic Method" },
      { ar: "محمد صلى الله عليه وسلم خاتم النبيين", en: "Muhammad ﷺ, the Seal of the Prophets" },
      { ar: "أحكام وآداب بيت النبوة", en: "Rules and Etiquette of the Prophet’s Household" },
      { ar: "الإنصاف في الإسلام", en: "Fairness in Islam" },
      { ar: "المحرمات من النساء", en: "Women Forbidden in Marriage" },
      { ar: "رحمة الرسول صلى الله عليه وسلم", en: "The Mercy of the Messenger ﷺ" },
      { ar: "ضوابط اجتماعية", en: "Social Guidelines" },
      { ar: "الإنسان والأمانة", en: "Humanity and Trust" },
      { ar: "منهج التفكير في الإسلام", en: "The Method of Thinking in Islam" },
      { ar: "الإسلام والتواصل الاجتماعي", en: "Islam and Social Communication" },
      { ar: "الإمام البخاري أمير المؤمنين في الحديث الشريف", en: "Imam Al-Bukhari, Commander of the Faithful in Hadith" },
    ],
  },
  {
    slug: "grade-12-year-13",
    grade: 12,
    year: 13,
    title: "Grade12/Year13",
    topics: [
      { ar: "وقاية المجتمع من الجرائم الأخلاقية", en: "Protecting Society from Moral Crimes" },
      { ar: "مناهج المفسرين", en: "Methods of the Quran Commentators" },
      { ar: "الإسلام ينبذ التطرف", en: "Islam Rejects Extremism" },
      { ar: "الفراق بين الزوجين", en: "Separation Between Spouses" },
      { ar: "رسول الله ﷺ والحياة الاجتماعية", en: "The Messenger of Allah ﷺ and Social Life" },
      { ar: "حديث الإفك - عظة وعبرة", en: "The Hadith of the Slander: Lesson and Reflection" },
      { ar: "السنن الربانية", en: "Divine Laws" },
      { ar: "المسؤولية في الإسلام", en: "Responsibility in Islam" },
      { ar: "مقاصد التشريع الخمسة", en: "The Five Objectives of Islamic Law" },
      { ar: "الشيخة فاطمة بنت مبارك", en: "Sheikha Fatima bint Mubarak" },
      { ar: "التواصل الاجتماعي (آداب وأحكام)", en: "Social Communication (Etiquette and Rules)" },
      { ar: "المنهج النبوي في الرعاية الصحية", en: "The Prophetic Method in Healthcare" },
      { ar: "البيوع المحرمة", en: "Forbidden Sales" },
      { ar: "الخدمة الوطنية واجب شرعي ومطلب وطني", en: "National Service Is a Religious Duty and a National Need" },
      { ar: "الزواج طريق الاستعفاف", en: "Marriage as the Path to Chastity" },
      { ar: "التفكير الإبداعي في الإسلام", en: "Creative Thinking in Islam" },
      { ar: "فقه ترتيب الأعمال بحسب مقاصدها", en: "The Jurisprudence of Prioritizing Actions by Their Objectives" },
      { ar: "العولمة", en: "Globalization" },
      { ar: "الله نور السموات والأرض (سورة النور 35-45)", en: "Allah Is the Light of the Heavens and the Earth (Surat An-Nur 35-45)" },
      { ar: "الطاعة والامتثال طريق الإيمان (سورة النور 46-57)", en: "Obedience and Compliance Are the Path of Faith (Surat An-Nur 46-57)" },
      { ar: "التسامح مع المخالفين في العقيدة", en: "Tolerance with Those Who Differ in Belief" },
      { ar: "آداب الإسلام في الرؤى والأحلام", en: "Islamic Etiquette Regarding Visions and Dreams" },
      { ar: "النظام الاقتصادي في الإسلام", en: "The Economic System in Islam" },
      { ar: "بيوت طاهرة - مجتمع نقي (سورة النور 58-61)", en: "Pure Homes, Pure Society (Surat An-Nur 58-61)" },
      { ar: "الأدب مع الرسول ﷺ (سورة النور 62-64)", en: "Etiquette with the Messenger ﷺ (Surat An-Nur 62-64)" },
      { ar: "الاتباع والتقليد", en: "Following and Imitation" },
      { ar: "الشيخ زايد بن سلطان رحمه الله", en: "Sheikh Zayed bin Sultan, May Allah Have Mercy on Him" },
      { ar: "الإسلام واقتصاد المعرفة", en: "Islam and the Knowledge Economy" },
    ],
  },
];

export const uaeCurriculumBySlug = Object.fromEntries(
  uaeCurriculumGrades.map((grade) => [grade.slug, grade])
) as Record<string, GradeLessonGroup>;

export const topicSlugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/['’`]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
