import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_4: BuiltInLesson[] = [
  {
    id: "dhul-kifl",
    name: "Dhul-Kifl",
    arabicName: "ذُو الْكِفْل",
    title: "The prophet who kept every promise",
    emoji: "🤝",
  accent: "from-slate-600 to-slate-700",
    summary:
      "Dhul-Kifl is praised in the Qur'an among the patient and righteous prophets who kept their word.",
    story: [
      "Dhul-Kifl (peace be upon him) is mentioned twice in the Qur'an, always in the company of great prophets such as Ismail and Idris. Allah describes them together as people of patience and as righteous servants who were chosen by Him.",
      "His name is understood to mean the one who takes on a share or a guarantee, because he promised to carry out duties and never broke his word. It is said that he judged between people with fairness, kept himself away from anger, and spent his nights in worship. He accepted heavy responsibilities and fulfilled them without complaining.",
      "The Qur'an does not give a long account of his life, and that itself is a lesson: what matters most is not fame or detail, but that Allah counted him among the patient and the righteous. A believer can be almost unknown to people yet honoured by Allah.",
      `Is he a Prophet? — Allah the Almighty declared: — " Remember Ishmael and Idris and Dhul Kifl, all were from among those who observe patience." (Ch 21:85-86)`,
      `Immediately following Job's story in the Qur'an, Almighty Allah also directed: — "Remember Our slaves, Abraham, Isaac, and Jacob (all) owners of strength (in worshipping Us) and also of religious understanding.`,
      `Verily, We did choose them by granting them (a good thing ) the remembrance of the home (in the Hereafter and they used to make the people remember it and also they used to invite the people to obey Allah and to do good deeds for the Hereafter).`,
      `And they are in Our Sight, verily of the chosen and the best! Remember Ishmael, Elisha, and Dhul Kifl all are among the best." (Ch 38:45-48)`,
      `It is obvious from his being mentioned and praised in the Glorious Quran along with those other prophets that Dhul - Kifl was also a prophet.`,
      `However, some of the Quranic commentators assumed that he was not a prophet but that he was righteous and strictly just.`,
      `The meaning of Dhul Kifl — Ibn Jarir narrated that he was not a prophet but he was a righteous man. He supported his people to suffice their needs and administered justice among them. That is why he was called Dhul - Kifl.`,
      `(Dhul - Kifl literally means "possessor of, or giving, a double requital or portion".)`,
    ],
    lessons: [
      "Keeping your word is a mark of true faith.",
      "Patience and fairness are praised by Allah even without fame.",
      "Accept responsibility, then fulfil it properly.",
    ],
    questions: [
      {
        id: "dhul-kifl-1",
        question: "How many times is Dhul-Kifl mentioned in the Qur'an?",
        options: ["Twice", "Ten times", "Once", "Never"],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-2",
        question: "With which prophets is he mentioned?",
        options: [
          "Ismail and Idris",
          "Musa and Harun",
          "Isa and Yahya",
          "Nuh and Hud",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-3",
        question: "How does Allah describe him and those with him?",
        options: [
          "As patient and righteous servants",
          "As kings",
          "As wealthy men",
          "As warriors",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-4",
        question: "What does his name suggest?",
        options: [
          "One who takes on a share or guarantee",
          "One who travels",
          "One who writes",
          "One who fights",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-5",
        question: "What is he known for in the reports about him?",
        options: [
          "Judging fairly and keeping his promises",
          "Building cities",
          "Leading armies",
          "Collecting wealth",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-6",
        question: "How did he spend his nights?",
        options: ["In worship", "In trade", "In travel", "In meetings"],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-7",
        question: "How did he deal with anger?",
        options: [
          "He kept himself away from it",
          "He used it against enemies",
          "He ignored justice",
          "He punished quickly",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-8",
        question: "How did he treat heavy responsibilities?",
        options: [
          "He fulfilled them without complaining",
          "He refused them",
          "He passed them to others",
          "He delayed them",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-9",
        question: "Why is the shortness of his story itself a lesson?",
        options: [
          "Honour with Allah does not depend on fame",
          "His story was forgotten",
          "He did little good",
          "He lived a short life",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-10",
        question: "What quality should we copy from him?",
        options: [
          "Keeping our promises",
          "Speaking a lot",
          "Seeking praise",
          "Avoiding people",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "dawud",
    name: "Dawud",
    arabicName: "دَاوُد",
    title: "The young shepherd who defeated Jalut",
    emoji: "🎶",
  accent: "from-amber-600 to-yellow-700",
    summary:
      "Dawud defeated the giant Jalut, was given the Zabur and a beautiful voice, and ruled with justice.",
    story: [
      "Dawud (peace be upon him) was a young man in the army of Talut when Bani Israil faced the powerful warrior Jalut (Goliath). While the soldiers were afraid, Dawud trusted Allah, went forward with a sling and stones, and defeated Jalut. Allah then gave him kingship and prophethood together.",
      "Allah gave Dawud special gifts: the Zabur (Psalms), a voice so beautiful that the birds and mountains would join him in glorifying Allah, and the skill of shaping iron to make armour. He earned his own living from his craft instead of taking from the treasury. He fasted often, prayed at night, and judged between people with justice.",
      "Once two men came to him with a dispute and he judged quickly; Allah taught him to listen to both sides carefully, and Dawud turned to Allah in repentance immediately. He is remembered as a servant who was always thankful, always returning to his Lord, and a king who never let power make him proud.",
      `David Challenges Goliath — When the two armies faced each other, Goliath challenged any soldier from King Saul's army to single combat, as was the custom of battle in those days. Goliath also wanted to show off his strength. The men were terrorized, and no one had enough courage to volunteer.`,
      `The king offered the hand of his pretty daughter in marriage to the man who would fight Goliath, but even this tempting offer did not change the deadly silence among his soldiers.`,
      `Then, to everyone's surprise, a youth stepped forward. A roar of laughter echoed from the enemy's side, and even Saul's men shook their heads. The young man was David (Dawud), from the city of Bethlehem. His elderly father had chosen three of his sons to join Saul's army.`,
      `He had instructed the youngest one, David, not to take part in the fighting but to help the army in other ways and to report to his father daily on what was happening on the war front.`,
      `Although Saul was very impressed by the youth's courage, he said: "I admire your courage, but you are no match for that mighty warrior. Let the strong men come forward." David, however, had already decided and was willing to meet the challenge.`,
      `Proudly, he told the king that only the day before he had killed a lion which had threatened his father's sheep, and on another occasion he had killed a bear. He asked Saul not to judge him by his appearance, for he feared no man or wild beast.`,
      `Saul, surprised by young David's brave stance, agreed: "My brave soldier, if you are willing, then may Allah guard you and grant you strength!"`,
      `David and Goliath Fight — The king dressed David in battle armor and handed him a sword, but David was not used to wearing battle dress. He felt uncomfortable in it, and it obstructed his movements. He removed the armor, then collected a few pebbles and filled his leather pouch with them.`,
      `He slung it over his shoulder next to his sling. With his wooden staff in hand, he began to walk towards the enemy.`,
      `Saul was worried and asked him how on earth, with a sling and a couple of stones was he going to defend himself against the giant? David replied: "Allah Who protected me from the claws of the bear and the fangs of the lion will certainly protect me from this brute!"`,
      `When Goliath set eyes on the lean young man who looked like a boy, he laughed loudly and roared: "Are you out to play war with one of your playmates, or are you tired of your life? I will simply cut off your head with one swipe of my sword!" David shouted back: "You may have armor, shield, and sword, but I face you in the name of Allah, the Lord of the Israelites, Whose laws you have mocked.`,
      `Today you will see that it is not the sword that kills but the will and power of Allah!" So saying, he took his sling and placed in it a pebble from his pouch. He swung and aimed it at Goliath.`,
      `The pebble shot from the whirling sling with the speed of an arrow and hit Goliath's head with great force. Blood gushed out, and Goliath thumped to the ground, lifeless, before he had a chance to draw his sword. When the rest of his men saw their mighty hero slain, they took to their heels.`,
      `The Israelites followed in hot pursuit, taking revenge for their years of suffering at the hands of their enemy, killing every soldier they could lay hands on. In this battle the Israelites regained the glory and honor that had been lost for a long time.`,
      `David became a hero overnight. Saul kept his word and married his daughter Michal (Miqel) to the young warrior and took him under his wing as one of his chief advisors.`,
      `Allah Gives David the Kingdom — Almighty Allah declared: — "So they routed them by Allah's Leave and David killed Goliath, and Allah gave him (David) the kingdom (after the death of Saul and Samuel) and wisdom, and taught him of that which He willed.`,
      `And if Allah did not check one set of people by means of another, the earth would indeed be full of mischief. But Allah is full of Bounty to the Alamin (mankind, jinns and all that exist). (Ch 2:251 Quran).`,
      `David Becomes a Prophet — David became the most famous man among the Israelites. However, he was not inveigled by this; he was not a prisoner of fame or leadership but a prisoner of Allah's love.`,
      `Therefore, after killing Goliath he went out into the desert in the company of nature, glorifying Almighty Allah and contemplating His favors.`,
      `"Verily, We made the mountains to glorify Our Praises with him (David) in the Ashi (after the mid-day till sunset) and Ishraq (after the sunrise till mid-day). And (so did) the birds assembled: all with him (David) did turn (to Allah, glorified His Praises).`,
      `We made his kingdom strong and gave him wisdom and sound judgment in speech and decision. (Ch 38:18-20 Quran) Creatures such as the plants, birds, beasts, and even the mountains responded to his voice glorifying Allah. Allah had chosen David to be a prophet and revealed the Psalms to him.`,
      `As He the Almighty said: "And to David We gave the Psalms." (Ch 17:55 Quran).`,
      `David is Granted the Language of Animals — David recited his scripture and glorified Allah while the mountains joined him praise and the birds rallied around him. Almighty Allah directed:`,
      `Be patient (O Muhammad) of what they say, and remember Our slave David, endured with power. Verily, he was ever oft-returning in all matters and in repentance toward Allah. (Ch 38:17 Quran).`,
    ],
    lessons: [
      "Courage comes from trust in Allah, not from body size.",
      "Earning your own halal living is honourable.",
      "Justice means listening carefully to both sides.",
    ],
    questions: [
      {
        id: "dawud-1",
        question: "Whom did Dawud defeat as a young man?",
        options: ["Jalut", "Pharaoh", "Samiri", "Namrud"],
        correctIndex: 0,
      },
      {
        id: "dawud-2",
        question: "What did he use in the battle?",
        options: ["A sling and stones", "A long spear", "A chariot", "A bow of iron"],
        correctIndex: 0,
      },
      {
        id: "dawud-3",
        question: "Which army was he part of?",
        options: ["The army of Talut", "The army of Egypt", "The army of Madyan", "The army of Rome"],
        correctIndex: 0,
      },
      {
        id: "dawud-4",
        question: "Which book was given to Dawud?",
        options: ["The Zabur", "The Tawrah", "The Injil", "The Qur'an"],
        correctIndex: 0,
      },
      {
        id: "dawud-5",
        question: "What happened when he glorified Allah?",
        options: [
          "The birds and mountains joined him",
          "The sea parted",
          "Rain fell",
          "The sun stopped",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-6",
        question: "Which craft was he taught?",
        options: [
          "Shaping iron to make armour",
          "Building ships",
          "Weaving cloth",
          "Making glass",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-7",
        question: "How did he earn his living as a king?",
        options: [
          "From his own craft, not the treasury",
          "From taxes only",
          "From gifts of other kings",
          "He did not work",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-8",
        question: "What acts of worship was he known for?",
        options: [
          "Frequent fasting and night prayer",
          "Only charity",
          "Only fasting in Ramadan",
          "Only reciting poetry",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-9",
        question: "What did Allah teach him about judging?",
        options: [
          "To listen carefully to both sides",
          "To judge quickly",
          "To follow the stronger party",
          "To leave judging to others",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-10",
        question: "How is Dawud remembered?",
        options: [
          "A thankful servant who always returned to Allah",
          "A proud king",
          "A silent worshipper",
          "A wealthy trader",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "sulayman",
    name: "Sulayman",
    arabicName: "سُلَيْمَان",
    title: "The king who understood the language of animals",
    emoji: "🐜",
  accent: "from-emerald-600 to-teal-700",
    summary:
      "Sulayman was given a mighty kingdom, control of the wind and jinn, and the speech of animals — and stayed grateful.",
    story: [
      "Sulayman (peace be upon him) was the son of Dawud and inherited both prophethood and kingship. He asked Allah for a kingdom that no one after him would have, and Allah answered him. The wind carried his command, the jinn worked for him, and he understood the speech of birds and animals. He never let these gifts make him arrogant; he said openly that all of it was from the favour of his Lord.",
      "One day, while marching with his army, he heard an ant warning the others to hide so they would not be crushed. Sulayman smiled and thanked Allah for teaching him to be gentle. Another time the hoopoe bird brought news of the people of Saba who worshipped the sun. Sulayman sent them a letter inviting them to worship Allah alone. Their queen, Bilqis, came to visit, saw his wisdom and the throne prepared for her, and accepted faith in Allah.",
      "Sulayman also built and repaired places of worship and ruled with justice. He died standing, leaning on his staff, and the jinn kept working until a small creature ate through the staff and he fell — showing everyone that even the greatest king is a servant of Allah, and only Allah knows the unseen.",
      `Solomon's Knowledge — Solomon inherited David's prophethood and dominion. This was not a material inheritance, as prophets do not bequeath their property. It is given away to the poor and needy, not to their relatives.`,
      `Prophet Muhammad (pbuh) said: "The prophets' property will not be inherited, and whatever we leave is to be used for charity." (Sahih Al-Bukhari).`,
      `"And indeed We gave knowledge to David and Solomon, and they both said: "All the praises and thanks be to Allah, Who has preferred us above many of His believing slaves!" And Solomon inherited (the knowledge of) David.`,
      `He said: "O mankind! We have been taught the language of birds, and on us have been bestowed all things. This, verily, is an evident grace (from Allah)." And there were gathered before Solomon his hosts of jinns and men, and birds, and they were all set in battle order (marching forwards).`,
      `(Ch 27:15-17 Quran).`,
      `Solomon Becomes King — After his father's death, Solomon became king. He begged Allah for a kingdom such as none after him would have, and Allah granted his wish. Besides wisdom, Allah had blessed Solomon with many abilities. He could command the winds and understand and talk to birds and animals.`,
      `Allah directed him to teach both men and jinns to mine the earth and extract its minerals to make tools and weapons. He also favored him with a mine of copper, which was a rare metal in those days.`,
      `Solomon's Admiration of Horses — During his time horses were the common mode of transportation. They were very essential for defense, to carry soldiers and cart provisions and weapons of war. The animals were well cared for and well trained. One day Solomon was reviewing a parade of his stable.`,
      `The fitness, beauty and posture of the horses fascinated him so much that he kept on stroking and admiring them. The sun was nearly setting, and the time for the middle prayer was passing by.`,
      `When he realized this, he exclaimed: "I surely love the finer things of life than the service of my Lord! Return them to me."`,
      `Allah's Gifts to Solomon - Quranic — Almighty Allah revealed: — "And to David We gave Solomon.`,
      `How excellent a slave! Verily, he was ever oft returning in repentance (to Us)! When there were displayed before him, in the afternoon, well-trained horses of the highest breed (for jihad in Allah's cause).`,
      `And he said: "Alas! I did love the good (these horses) instead of remembering my Lord (in my 'Asr prayer)" till the time was over, and the sun had hidden in the veil of the night.`,
      `Then he said: "Bring them (horses) back to me." Then he began to pass his hand over their legs and their necks (till the end of the display).`,
      `And indeed We did try Solomon and We placed on his throne Jasadan (a devil, so he lost his kingdom for a while) but he did return (to his throne and kingdom by the Grace of Allah and he did return) to Allah with obedience and in repentance.`,
      `He said: "My Lord! Forgive me, and bestow upon me a kingdom such as shall not belong to any other after me.`,
      `Verily, You are the Bestower." So, We subjected to him the wind, it blew gently to his order whithersoever he willed, and also the devils from the jinns including every kind of builder and diver, and also other bound in fetters.`,
      `(Saying of Allah to Solomon): "This is Our gift, so spend you or withhold, no account will be asked." And verily, he enjoyed a near access to Us, and a good final return Paradise. (Ch38:30-40 Quran).`,
      `Solomon Hears the Ant's Warning — One day Solomon gathered his army, which had different battalions of men, jinns, birds, and animals. He marched them to the country of Askalon.`,
      `While they were passing through a valley, an ant saw the approaching army and cried out to warn the other ants: "Run to your homes! Otherwise, unaware, Solomon and his army might crush you!" Solomon, hearing the cry of the ant, smiled.`,
      `He was glad that the ant knew him to be a prophet who would not intentionally harm Allah's creation. He thanked Allah for saving the ants' lives.`,
      `Solomon Hears the Conversation of Ants - Quranic — Allah the Almighty narrated: And there were gathered before Solomon his hosts of jinns and men, and birds, and they all were set in battle order (marching forwards).`,
      `Till, when they came to a valley of the ants, one of the ants said: "O ants! Enter your dwellings, lest Solomon and his hosts crush you, while they perceive not." So he (Solomon) smiled, amused at her speech and said: "My Lord! Inspire and bestow upon me the power and ability that I maybe grateful for Your Favors which You have bestowed on me and on my parents, and that I may do righteous good deeds that will please You, and admit me by Your Mercy among Your righteous slaves." (Ch 27:17-19 Quran).`,
      `Solomon's Travels — In Jerusalem, on a huge rock, Solomon built a beautiful temple to draw the people to worship Allah. Today this building is known as "The Dome of the Rock." From there, a large band of followers joined Solomon on pilgrimage to the Holy Mosque in Mecca.`,
    ],
    lessons: [
      "Great blessings should increase gratitude, not pride.",
      "Kindness includes even the smallest creatures.",
      "Wisdom invites people to the truth gently.",
    ],
    questions: [
      {
        id: "sulayman-1",
        question: "Who was Sulayman's father?",
        options: ["Dawud", "Yaqub", "Ishaq", "Musa"],
        correctIndex: 0,
      },
      {
        id: "sulayman-2",
        question: "What did Sulayman ask Allah for?",
        options: [
          "A kingdom that no one after him would have",
          "Endless wealth only",
          "A long life",
          "An army of men",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-3",
        question: "Which creatures worked for him by Allah's permission?",
        options: ["The jinn", "The angels", "The birds only", "Sea creatures"],
        correctIndex: 0,
      },
      {
        id: "sulayman-4",
        question: "What did he understand that others could not?",
        options: [
          "The speech of birds and animals",
          "The future",
          "Every language of men only",
          "The thoughts of people",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-5",
        question: "What did the ant say?",
        options: [
          "It warned the other ants to hide",
          "It asked for food",
          "It praised the army",
          "It called for rain",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-6",
        question: "Which bird brought news of Saba?",
        options: ["The hoopoe", "An eagle", "A crow", "A dove"],
        correctIndex: 0,
      },
      {
        id: "sulayman-7",
        question: "What were the people of Saba worshipping?",
        options: ["The sun", "Idols of stone", "Fire", "The moon"],
        correctIndex: 0,
      },
      {
        id: "sulayman-8",
        question: "Who was the queen who came to visit him?",
        options: ["Bilqis", "Asiya", "Sarah", "Maryam"],
        correctIndex: 0,
      },
      {
        id: "sulayman-9",
        question: "How did Sulayman treat his great blessings?",
        options: [
          "He thanked Allah and said they were from His favour",
          "He became proud",
          "He hid them",
          "He gave up his kingdom",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-10",
        question: "How did the jinn learn that he had died?",
        options: [
          "A small creature ate his staff and he fell",
          "An angel told them",
          "He wrote a letter",
          "The wind stopped",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ilyas",
    name: "Ilyas",
    arabicName: "إِلْيَاس",
    title: "The prophet who stood against Ba'l worship",
    emoji: "⛈️",
  accent: "from-sky-600 to-blue-700",
    summary:
      "Ilyas warned his people against worshipping the idol Ba'l and called them back to Allah alone.",
    story: [
      "Ilyas (peace be upon him) was sent to a people of Bani Israil who had left the way of Musa and started worshipping an idol they called Ba'l. Their leaders encouraged this, and the ordinary people followed without thinking.",
      "Ilyas stood before them and asked a simple question: will you worship Ba'l and leave the best of creators — Allah, your Lord and the Lord of your forefathers? He warned them of the consequences of shirk and reminded them of the blessings they enjoyed.",
      "Most of them rejected him, and only a small group believed. Allah saved Ilyas and the believers, and the Qur'an says that peace be upon Ilyas and that Allah left a good remembrance of him among later generations. His story shows that a believer's duty is to speak the truth clearly, even to a whole society that has gone the wrong way.",
    ],
    lessons: [
      "Following the crowd is not an excuse before Allah.",
      "Speak the truth clearly even when few will accept it.",
      "Allah preserves a good name for those who stand for Him.",
    ],
    questions: [
      {
        id: "ilyas-1",
        question: "Which idol were the people of Ilyas worshipping?",
        options: ["Ba'l", "Al-Lat", "The golden calf", "The sun"],
        correctIndex: 0,
      },
      {
        id: "ilyas-2",
        question: "To which nation was Ilyas sent?",
        options: ["A people of Bani Israil", "The people of 'Ad", "Thamud", "Quraysh"],
        correctIndex: 0,
      },
      {
        id: "ilyas-3",
        question: "What question did he ask them?",
        options: [
          "Will you worship Ba'l and leave the best of creators?",
          "Why do you not build temples?",
          "Where is your king?",
          "Why do you not travel?",
        ],
        correctIndex: 0,
      },
      {
        id: "ilyas-4",
        question: "Whose way had they abandoned?",
        options: ["The way of Musa", "The way of Isa", "The way of Nuh", "The way of Ibrahim only"],
        correctIndex: 0,
      },
      {
        id: "ilyas-5",
        question: "Who encouraged the idol worship?",
        options: ["Their leaders", "Their prophets", "Travellers", "Their children"],
        correctIndex: 0,
      },
      {
        id: "ilyas-6",
        question: "How did most people respond to Ilyas?",
        options: ["They rejected him", "They believed", "They asked for a sign", "They left the city"],
        correctIndex: 0,
      },
      {
        id: "ilyas-7",
        question: "What happened to Ilyas and the believers?",
        options: ["Allah saved them", "They were destroyed", "They were exiled", "They were imprisoned"],
        correctIndex: 0,
      },
      {
        id: "ilyas-8",
        question: "What does the Qur'an say about Ilyas?",
        options: [
          "Peace be upon him, and a good remembrance was left of him",
          "That he was a king",
          "That he wrote a book",
          "That he had a large army",
        ],
        correctIndex: 0,
      },
      {
        id: "ilyas-9",
        question: "Why did the ordinary people follow the idol?",
        options: [
          "They followed their leaders without thinking",
          "They were forced by another nation",
          "They had no prophet",
          "They could not read",
        ],
        correctIndex: 0,
      },
      {
        id: "ilyas-10",
        question: "What is the lesson for us?",
        options: [
          "We must speak the truth even if society disagrees",
          "We should always follow the majority",
          "Idols are harmless",
          "Prophets only warn kings",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "al-yasa",
    name: "Al-Yasa'",
    arabicName: "الْيَسَع",
    title: "The chosen successor of Ilyas",
    emoji: "🌿",
  accent: "from-green-600 to-emerald-700",
    summary:
      "Al-Yasa' continued the mission of Ilyas and is praised by Allah as one of the chosen and excellent servants.",
    story: [
      "Al-Yasa' (peace be upon him) lived among Bani Israil and was a companion and student of Ilyas. When Ilyas' mission ended, Al-Yasa' carried it on, calling the people back to the worship of Allah alone after they had turned to idols.",
      "The Qur'an mentions him twice, listing him with Ismail and Dhul-Kifl, and describing them as chosen ones and among the excellent. This means his patience and sincerity were accepted by Allah, even though the details of his life are not narrated at length.",
      "He continued teaching, reminding and warning his people, and he faced the same stubbornness that earlier prophets faced. His story shows that the message of tawhid never stops: when one caller passes, another takes up the responsibility, and every generation needs people who remind it of Allah.",
      `Elisha's Mission — "And remember Our slaves, Abraham, Isaac, and Jacob, (all) owners of strength (in worshipping Us) and (also) of religious understanding.`,
      `Verily, We did choose them by granting them (a good thing ) the remembrance of the home (in the Hereafter and they used to make the people remember it, and also they used to invite the people to obey Allah and to do good deeds for the Hereafter).`,
      `And they are in Our Sight, verily, of the chosen and the best! And remember Ishmael, Elisha, and Dhul-Kifl, all are among the best. (Ch 38:45-48 Quran).`,
      `Ibn Ishaaq said that Elisha (pbuh) was sent to the children after Elijah (pbuh). He lived among his people, calling them to Allah and abiding by the message and laws of Elijah until he passed away. Then dissension rose among them, and events took momentum.`,
      `Sins increased everywhere, and the tyrants increased and killed the prophets.`,
      `The Family History of Elisha — According to Al-Hafiz Abu Al-Qasim Ibn Asaker, Elisha was Ibn Adi, Ibn Shultam, Ibn Aphraem, Ibn Joseph, Ibn Isaac, Ibn Abraham. It was said that he was the cousin of Elijah.`,
      `Other sources said also that he had been hiding with Elijah in a cave in Mount Qasium to escape from the King of Ba'alabak, and when Elijah died, he Elisha succeeded him as a prophet among his people.`,
    ],
    lessons: [
      "Good work should be continued by the next generation.",
      "Learning from a righteous teacher shapes a righteous life.",
      "Allah counts sincerity, even when people forget your details.",
    ],
    questions: [
      {
        id: "al-yasa-1",
        question: "Whose mission did Al-Yasa' continue?",
        options: ["Ilyas", "Musa", "Dawud", "Yunus"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-2",
        question: "Among which people did he live?",
        options: ["Bani Israil", "'Ad", "Thamud", "Madyan"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-3",
        question: "How does the Qur'an describe him?",
        options: [
          "Among the chosen and the excellent",
          "As a king",
          "As a rich merchant",
          "As a warrior",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-4",
        question: "With which prophets is he listed?",
        options: [
          "Ismail and Dhul-Kifl",
          "Musa and Harun",
          "Isa and Yahya",
          "Nuh and Hud",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-5",
        question: "What was his main call?",
        options: [
          "To worship Allah alone",
          "To build a temple",
          "To fight the neighbours",
          "To collect wealth",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-6",
        question: "What had the people turned to before him?",
        options: ["Idols", "Farming", "Trade", "Poetry"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-7",
        question: "What relationship did he have with Ilyas?",
        options: [
          "He was his companion and student",
          "He was his enemy",
          "He never met him",
          "He was his king",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-8",
        question: "How many times is he mentioned in the Qur'an?",
        options: ["Twice", "Once", "Seven times", "Never"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-9",
        question: "What difficulty did he face?",
        options: [
          "The stubbornness of his people",
          "Loss of memory",
          "A long journey",
          "Loss of his kingdom",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-10",
        question: "What lesson does his story give us?",
        options: [
          "Every generation needs people who remind it of Allah",
          "Only famous people matter",
          "Teaching is easy",
          "Prophets did not have students",
        ],
        correctIndex: 0,
      },
    ],
  },
];
