import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_1: BuiltInLesson[] = [
  {
    id: "adam",
    name: "Adam",
    arabicName: "آدَم",
    title: "The first human and the first prophet",
    emoji: "🌍",
  accent: "from-emerald-600 to-teal-700",
    summary:
      "Allah created Adam from clay, taught him the names of everything, and made him the first prophet.",
    story: [
      "Allah created Adam (peace be upon him) from clay and breathed life into him. He was the first human being and the father of all people. Allah taught Adam the names of everything, so his knowledge was greater than that of the angels. When Allah asked the angels to prostrate to Adam out of respect, they all obeyed except Iblis, who refused out of pride and was expelled from Allah's mercy.",
      "Adam lived in Paradise with his wife Hawwa (Eve). Allah allowed them to enjoy everything there but told them not to eat from one particular tree. Iblis whispered to them again and again, promising that the tree would make them live forever. In the end they ate from it, and they immediately realised they had disobeyed their Lord.",
      "Adam and Hawwa were sorry for what they had done. They turned to Allah with a beautiful dua, asking for forgiveness, and Allah forgave them. They were sent down to live on earth, where Adam became the first prophet, teaching his children to worship Allah alone. His story shows that everyone makes mistakes, but the person who repents sincerely is loved by Allah.",
      `Informing the Angels About Adam — Allah the Almighty revealed: — "Remember when your Lord said to the angels: 'Verily, I am going to place mankind generations after generations on earth.' They said: 'Will You place therein those who will make mischief therein and shed blood, while we glorify You with praises and thanks (exalted be You above all that they associate with You as partners) and sanctify You.' Allah said: 'I know that which you do not know.' Allah taught Adam all the names of everything, then He showed them to the angels and said: "Tell Me the names of these if you are truthful." They (angels) said: "Glory be to You, we have no knowledge except what You have taught us.`,
      `Verily, it is You, the All-Knower, the All-Wise."`,
      `He said: "O Adam! Inform them of their names," and when he had informed them of their names, He said: "Did I not tell you that I know the unseen in the heavens and the earth, and I know what you reveal and what you have been hiding?"`,
      `Remember when We said to the angels: "Prostrate yourself before Adam" They prostrated except Iblis, he refused and was proud and was one of the disbelievers(disobedient to Allah)."`,
      `We said: "O Adam! Dwell you and your wife in the Paradise and both of you freely with pleasure and delight of things therein as wherever you will but come not near this tree or you both will be of the Zalimeen (wrongdoers)." Then the Satan made them slip therefrom (the Paradise), and got them out from that in which they were.`,
      `We said: "Get you down all with enmity between yourselves. On earth will be a dwelling place for you and an enjoyment for a time." Then Adam received from his Lord Words. His Lord pardoned him (accepted his repentance). Verily He is the One Who forgives (accepts repentance), the most Merciful.`,
      `We said: "Get down all of you from this place (the Paradise), then whenever there comes to you Guidance from Me, and whoever follows My Guidance there shall be no fear on them, nor shall they grieve.`,
      `But those who disbelieve and belie Our Ayah (proofs, evidences, verses, lessons, and signs and revelations, etc) such are the dwellers of the Fire, they shall abide therein forever." (Chapter 2:30-39, Qur'an).`,
      `Almighty Allah also revealed: — "And surely, We created you (your father Adam) and then gave you shape (the noble shape of a human being), then We told the angels, "Prostrate to Adam", and they prostrated, except Iblis, he refused to be those who prostrate.`,
      `Allah said: "What prevented you (O Iblis) that you did not postrate when I commanded you?"`,
      `Iblis said: "I am better than him (Adam), You created me from fire and him You created from clay."`,
      `Allah said: "O Iblis get down from this (Paradise), it is not for you to be arrogant here. Get out for you are of those humiliated and disgraced." Iblis said: "Allow me respite till the Day they are raised up (Day of Resurrection)."`,
      `Allah said: "You are of those allowed respite." — Iblis said: "Because You have sent me astray, surely I will sit in wait against them (human beings) on Your Straight Path.`,
      `Then I will come to them from before them and behind them, from their right and from their left and You will not find most of them as thankful ones (they will not be dutiful to You)." Allah said: "Get out from Paradise, disgraced and expelled.`,
      `Whoever of them (mankind) will follow you, then surely I will fill Hell with you all." "And O Adam! Dwell you and your wife in Paradise, and eat thereof as you both wish, but approach not this tree otherwise you both will be of the Zalimeen (unjust and wrongdoers)." “Then Satan whispered suggestions to them both in order to uncover that which was hidden from them of their private parts before, he said:" Your Lord did not forbid you this tree save you should become angels or become of the immortals." Satan swore by Allah to them both saying: "Verily I am one of the sincere well wishers for you both." So he misled them with deception.`,
      `Then when they tasted of the tree, that which was hidden from them of their shame (private parts) became manifest to them and they began to stick together the leaves of Paradise over themselves (in order to cover their shame).`,
      `Their Lord called out to them saying "Did I not forbid you that tree and tell you, Verily Satan is an open enemy unto you?" They said: "Our Lord! We have wronged ourselves.`,
      `If You forgive us not, and bestow not upon us Your Mercy, we shall certainly be of the losers." Allah said: "Get down one of you an enemy to the other (i.e. Adam, Eve, and Satan etc).`,
      `On earth will be a dwelling place for you and an enjoyment, for a time." He said: "therein you shall live, and therein you shall die, and from it you shall be brought out (resurrected)." (Chapter 7:11-25 Qur'an).`,
      `We imagine when Allah the Almighty decided to create Adam: He addressed His angels and told them to prostrate before him. He did not mean to ask their opinion or take their advice, for He is above that.`,
      `Allah the Exalted told them that He was going to create a vicegerent on the earth who would have children and grandchildren who would corrupt the earth and shed each other's blood.`,
      `That is why the angels said to Allah the Almighty: "Will You place therein those who will make mischief therein and shed blood!" (Chapter 2:30 Quran). There are old traditions about the angels before the creation of Adam.`,
      `According to Ibn Qatadah, it was said that the angels were informed about the creation of Adam and his progency by the jinn who lived before Adam. Abdullah Ibn Umar said that the jinn had existed for about 2000 years before Adam and then shed blood.`,
      `Therefore Allah sent on them an army of angels that drove them out to the depths of the seas.`,
    ],
    lessons: [
      "Pride is what destroyed Iblis — humility keeps our hearts clean.",
      "Knowledge is a gift from Allah and it raises a person's rank.",
      "When we slip, we repent straight away instead of despairing.",
    ],
    questions: [
      {
        id: "adam-1",
        question: "What was Adam (peace be upon him) created from?",
        options: ["Clay", "Light", "Fire", "Water only"],
        correctIndex: 0,
      },
      {
        id: "adam-2",
        question: "Which creature refused to prostrate to Adam?",
        options: ["Jibril", "Iblis", "Mikail", "A jinn who later believed"],
        correctIndex: 1,
      },
      {
        id: "adam-3",
        question: "Why did Iblis refuse to obey Allah's command?",
        options: [
          "He was confused",
          "He was afraid",
          "He was proud and arrogant",
          "He did not hear the command",
        ],
        correctIndex: 2,
      },
      {
        id: "adam-4",
        question: "What special knowledge did Allah give Adam?",
        options: [
          "The names of everything",
          "The ability to fly",
          "The language of animals only",
          "The future of every person",
        ],
        correctIndex: 0,
      },
      {
        id: "adam-5",
        question: "What was the name of Adam's wife?",
        options: ["Maryam", "Asiya", "Hawwa", "Sarah"],
        correctIndex: 2,
      },
      {
        id: "adam-6",
        question: "What did Allah tell Adam and Hawwa not to do in Paradise?",
        options: [
          "Not to speak to the angels",
          "Not to eat from one tree",
          "Not to leave their home",
          "Not to drink from the rivers",
        ],
        correctIndex: 1,
      },
      {
        id: "adam-7",
        question: "How did Iblis trick them?",
        options: [
          "He forced them",
          "He whispered and made false promises",
          "He changed the tree",
          "He hid the command from them",
        ],
        correctIndex: 1,
      },
      {
        id: "adam-8",
        question: "What did Adam and Hawwa do after their mistake?",
        options: [
          "They blamed each other",
          "They hid from Allah",
          "They repented and asked Allah for forgiveness",
          "They gave up hope",
        ],
        correctIndex: 2,
      },
      {
        id: "adam-9",
        question: "Did Allah accept Adam's repentance?",
        options: [
          "Yes, Allah forgave him",
          "No, never",
          "Only after many years of punishment",
          "The story does not say",
        ],
        correctIndex: 0,
      },
      {
        id: "adam-10",
        question: "Why is Adam called the first prophet?",
        options: [
          "He was the strongest man",
          "He built the first city",
          "He taught his children to worship Allah alone",
          "He wrote the first book",
        ],
        correctIndex: 2,
      },
    ],
  },
  {
    id: "idris",
    name: "Idris",
    arabicName: "إِدْرِيس",
    title: "The patient prophet raised to a high station",
    emoji: "📜",
  accent: "from-sky-600 to-indigo-700",
    summary:
      "Idris was known for truthfulness and patience, and Allah raised him to a high place.",
    story: [
      "Idris (peace be upon him) came after Adam, in a time when many people had started to forget the way of their father Adam. The Qur'an describes Idris with two beautiful qualities: he was truthful and he was patient. He never lied, and he never gave up when calling people to the worship of Allah.",
      "Idris spent his days worshipping Allah and teaching people. He is remembered as one of the earliest people to write with a pen and to study carefully the signs of Allah in the world. He reminded people that this life is short and that everything they do is recorded.",
      "Allah praised him in the Qur'an and said that He raised him to a high station. Because of his patience and truthfulness, his rank with Allah became very high. His story teaches us that steady worship, honesty and patience raise a believer even when the people around them are heedless.",
      `Allah has praised Enoch, describing him as being a prophet and truthful: — "Mention in the Book (Quran) Idris (Enoch). Verily! He was a man of truth (and) a prophet. We raised him to a high station". (Ch 19:56-57 Quran).`,
      `Birth and Teachings — Enoch was born and raised in Babylon following the teachings and religion of Prophet Adam (pbuh) and his son Seth (pbuh). Enoch was the 5th generation of the Prophet Adam.`,
      `He called the people back to his forefathers religion, but only a few listened to him, while the majority turned away.`,
      `Prophet Enoch and his followers left Babylon for Egypt. There he carried on his mission, calling people to what is just and fair, teaching them certain prayers and instructing them to fast on certain days and to give a portion of their wealth to the poor.`,
      `The Wise Sayings of Prophet Enoch — He was the first of the Children of Adam to be given prophethood after Adam and Seth (peace upon them). It is reported that he was the 1st to invent the basic form of writing. Some of his wise sayings are:`,
      `"Happy is he who looks at his own deeds and appoints them as pleaders to his Lord."`,
      `"None can show better gratitude for Allah's favors than he who shares them with others."`,
      `"Do not envy people for what they have as they will only enjoy it for a short while."`,
      `"He who indulges in excess will not benefit from it." — "The real joy of life is to have wisdom."`,
    ],
    lessons: [
      "Truthfulness in small things builds a trustworthy character.",
      "Patience with people is part of calling them to good.",
      "Allah raises those who are steady in worship.",
    ],
    questions: [
      {
        id: "idris-1",
        question: "Which two qualities does the Qur'an mention about Idris?",
        options: [
          "Truthfulness and patience",
          "Strength and wealth",
          "Speed and courage",
          "Kingship and power",
        ],
        correctIndex: 0,
      },
      {
        id: "idris-2",
        question: "When did Idris live?",
        options: [
          "After Adam",
          "After Musa",
          "At the same time as Isa",
          "After the Prophet Muhammad",
        ],
        correctIndex: 0,
      },
      {
        id: "idris-3",
        question: "What did Allah do for Idris because of his high character?",
        options: [
          "Gave him a kingdom",
          "Raised him to a high station",
          "Made him rich",
          "Gave him a large army",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-4",
        question: "What is Idris remembered for using early on?",
        options: ["The pen and writing", "The sword", "Ships", "Iron tools only"],
        correctIndex: 0,
      },
      {
        id: "idris-5",
        question: "What did Idris remind people about this life?",
        options: [
          "That it lasts forever",
          "That it is short and our deeds are recorded",
          "That only rich people succeed",
          "That it has no purpose",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-6",
        question: "How did Idris behave when people ignored his message?",
        options: [
          "He stopped calling them",
          "He stayed patient and continued",
          "He punished them",
          "He left the earth",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-7",
        question: "What did the people of his time begin to forget?",
        options: [
          "The way of Adam and the worship of Allah",
          "How to farm",
          "How to build houses",
          "Their own names",
        ],
        correctIndex: 0,
      },
      {
        id: "idris-8",
        question: "Being truthful means that a person:",
        options: [
          "Says what people like to hear",
          "Never lies",
          "Speaks only in public",
          "Stays silent always",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-9",
        question: "What raises a believer's rank according to this story?",
        options: [
          "Wealth and fame",
          "Patience, honesty and steady worship",
          "Winning arguments",
          "Having many followers",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-10",
        question: "Idris was one of the prophets who:",
        options: [
          "Was sent only to one family",
          "Called his people to worship Allah alone",
          "Never spoke to anyone",
          "Refused prophethood",
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: "nuh",
    name: "Nuh",
    arabicName: "نُوح",
    title: "The prophet of the ark and the great flood",
    emoji: "🚢",
  accent: "from-blue-600 to-cyan-700",
    summary:
      "Nuh called his people for 950 years, then built an ark by Allah's command and was saved from the flood.",
    story: [
      "The people of Nuh (peace be upon him) had begun to worship idols made of stone and wood. Allah sent Nuh to warn them and to call them back to the worship of the One Lord. He called them day and night, in public and in private, for about 950 years. Only a small group believed; the rest mocked him, called him a liar, and even put their fingers in their ears so they would not hear him.",
      "Allah then commanded Nuh to build a huge ark. The people laughed as he built a ship far from any sea. When the ark was ready, Allah told Nuh to carry the believers and a pair of every kind of animal on board. Then water burst from the earth and poured from the sky, and a great flood covered the land.",
      "Nuh called out to his own son to come aboard, but the son refused and said he would climb a mountain instead. He drowned with the disbelievers. The ark floated safely and finally settled on Mount Judi. Nuh and the believers came down and thanked Allah. His story teaches patience over long years and that faith, not family name, is what saves a person.",
      `Variation on the Birth of Noah — He was Noah Ibn Lamik, Ibn Mitoshilkh, Ibn Enoch, Ibn yard, Ibn Mahlabeel, Ibn Qinan, Ibn Anoush, Ibn Seth, Ibn Adam the Father of Mankind (PBUH).`,
      `According to the history of the People of the Book, (refers to the Jews, and Christians, so called by Allah because they received Revealed Books, Taurat, Zabur and Injeel. These names are translated 'Torah, Psalms, and Gospels' respectively, but the books that are extent are corrupt.`,
      `Of the Revealed Books, ONLY the Quran remains exactly as it was revealed).`,
      `The period between the birth of Noah and the death of Adam was 146 years. (According to Genesis 5 (new Revised Standard Version), Noah was born one hundred and twenty six years after the death of Adam.`,
      `Ibn Abbas narrated that the Prophet Muhammad (PBUH) said: "The period between Adam and Noah was ten centuries." (Sahih Bukhari, Noah was born 1056 years after Adam's creation (or after he left the Garden of Eden).`,
      `Thus, this hadith does not contradict the previous statement from the People of the Book as it may first appear to do. The reader should keep in mind, however that any statement or narratives taken from the People of the Book are not necessarily credible. This was taken from Genesis 5).`,
      `Noah's People - Idolaters — For many generations Noah's people had been worshipping statues that they called gods. They believed that these gods would bring them good, protect them from evil and provide all their needs.`,
      `They gave their idols names such as Waddan, Suwa'an, Yaghutha, Ya'auga, and Nasran, (These idols represented, respectively, manly power; mutability, beauty; brute strength, swiftness, sharp sight, insight) according to the power they thought these gods possessed. Allah the Almighty revealed:`,
      `"They (idolaters) have said: "You shall not leave your gods nor shall you leave Wadd, nor Suwa, nor Yaghuth, nor Ya uq nor Nasr (names of the idols)." (CH 71:23 Quran).`,
      `Originally these were the names of good people who had lived among them. After their deaths, statues of them were erected to keep their memories alive. After sometime, however, people began to worship these statues.`,
      `Later generations did not even know why they had been erected; they only knew their parents had prayed to them. That is how idol worshipping developed. Since they had no understanding of Allah the Almighty Who would punish them for their evil deeds, they became cruel and immoral.`,
      `Various Hadith describing the Origin of Idolatry — Ibn Abbas explained: "Following upon the death of those righteous men, Satan inspired their people to erect statues in the places where they used to sit.`,
      `They did this, but these statues were not worshiped until the coming generations deviated from the right way of life. Then they worshipped them as their idols."`,
      `In his version, Ibn Jarir narrated: "There were righteous people who lived in the period between Adam and Noah and who had followers who held them as models.`,
      `After their death, their friends who used to emulate them said: 'If we make statues of them, it will be more pleasing to us in our worship and will remind us of them.' So they built statues of them, and , after they had died and others came after them, Iblis crept into their minds saying:'Your forefathers used to worship them, and through that worship they got rain.' So they worshipped them."`,
      `Ibn Abi Hatim related this story: "Waddan was a righteous man who was loved by his people. When he died, they withdrew to his grave in the land of Babylonia and were overwhelmed by sadness.`,
      `When Iblis saw their sorrow caused by his death, he disguised himself in the form of a man saying: 'I have seen your sorrow because of this man's death; can I make a statue like him which could be put in your meeting place to make you remember him?' They said: 'Yes.' So he made the statue like him.`,
      `They put it in their meeting place in order to be reminded of him. When Iblis saw their interest in remembering him, he said: 'Can I build a statue of him in the home of each one of you so that he would be in everyone's house and you could remember him?' They agreed.`,
      `Their children learned about and saw what they were doing. They also learned about their remembrance of him instead of Allah. So the first to be worshipped instead of Allah was Waddan, the idol which they named thus."`,
      `The essence of this point is that every idol from those earlier mentioned was worshipped by a certain group of people.`,
      `It was mentioned that people made picture sand as the ages passed they made these pictures into statues, so that their forms could be fully recognized; afterwards they were worshipped instead of Allah.`,
      `It was narrated that Umm Salmah and Umm Habibah told Allah's Prophet Muhammad (PBUH) about the church called "Maria" which they had seen in the land of Abyssinia. They described its beauty and the pictures therein.`,
      `He said: "Those are the people who build places of worship on the grave of every dead man who was righteous and then make therein those pictures. Those are the worst of creation unto Allah." (Sahih al Bukhari).`,
      `Commentary - Idolatry — Worshipping anything other than Allah is a tragedy that results not only in the loss of freedom; its serious effect reaches man's mind and destroys it as well.`,
    ],
    lessons: [
      "Patience in doing good even when results take a long time.",
      "Obeying Allah can look strange to others — obey anyway.",
      "Faith is personal: being related to a righteous person is not enough.",
    ],
    questions: [
      {
        id: "nuh-1",
        question: "What were the people of Nuh worshipping?",
        options: ["Idols", "Angels", "The prophets", "Nothing at all"],
        correctIndex: 0,
      },
      {
        id: "nuh-2",
        question: "For roughly how long did Nuh call his people?",
        options: ["40 years", "100 years", "950 years", "10 years"],
        correctIndex: 2,
      },
      {
        id: "nuh-3",
        question: "How did most of his people respond?",
        options: [
          "They believed quickly",
          "They mocked him and refused to listen",
          "They asked for more proof and then believed",
          "They left the city",
        ],
        correctIndex: 1,
      },
      {
        id: "nuh-4",
        question: "What did Allah command Nuh to build?",
        options: ["A city", "A mosque", "An ark", "A wall"],
        correctIndex: 2,
      },
      {
        id: "nuh-5",
        question: "Who and what did Nuh take on board?",
        options: [
          "Only his family",
          "The believers and pairs of animals",
          "All the people of the town",
          "Only the animals",
        ],
        correctIndex: 1,
      },
      {
        id: "nuh-6",
        question: "How did the flood begin?",
        options: [
          "Water came from the earth and the sky",
          "A river changed direction",
          "The sea dried up",
          "Rain fell for one hour",
        ],
        correctIndex: 0,
      },
      {
        id: "nuh-7",
        question: "What happened to the son who refused to board?",
        options: [
          "He was saved on a mountain",
          "He drowned",
          "He believed at the last moment",
          "He built his own boat",
        ],
        correctIndex: 1,
      },
      {
        id: "nuh-8",
        question: "Where did the ark finally settle?",
        options: ["Mount Judi", "Mount Sinai", "Mount Uhud", "Mount Arafat"],
        correctIndex: 0,
      },
      {
        id: "nuh-9",
        question: "Why did the people laugh while Nuh was building?",
        options: [
          "He was building far from water",
          "He was building very slowly",
          "The wood was broken",
          "He was building at night",
        ],
        correctIndex: 0,
      },
      {
        id: "nuh-10",
        question: "What is the main lesson from the story of Nuh?",
        options: [
          "Patience in calling to Allah, and that faith saves a person",
          "Boats are important",
          "Rain is dangerous",
          "Long life is a reward",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "hud",
    name: "Hud",
    arabicName: "هُود",
    title: "The prophet sent to the mighty people of 'Ad",
    emoji: "🏜️",
  accent: "from-amber-600 to-orange-700",
    summary:
      "Hud warned the strong people of 'Ad about their pride, and they were destroyed by a fierce wind.",
    story: [
      "The people of 'Ad were tall, strong and skilled builders. They lived in a land of gardens and tall pillars, and they thought no one could ever defeat them. Their strength made them proud, and they worshipped idols instead of the One who had given them all that power.",
      "Allah sent them Hud (peace be upon him), a man from among themselves. He told them clearly: worship Allah alone, do not be arrogant, and remember the favours you have been given. They answered that he was foolish and that their idols would protect them. They challenged him to bring the punishment he warned them about.",
      "Then rain stopped falling and a cloud appeared. They were happy, thinking it would bring rain, but it carried a furious wind that blew for several days and nights. The proud people of 'Ad were destroyed, while Hud and the believers were saved by Allah's mercy. Their story warns us that strength and wealth are tests, not proof that Allah is pleased with us.",
      `Description of the People of Ad — The people of 'Ad lived many years in the windswept hills of an area between Yemen and Oman. They were physically well built and renowned for their craftsmanship especially in the construction of tall buildings with lofty towers.`,
      `They were outstanding among all the nations in power and wealth, which, unfortunately, made them arrogant and boastful. Their political power was held in the hand of unjust rulers, against whom no one dared to raise a voice.`,
      `They were not ignorant of the existence of Allah, nor did they refuse to worship Him. What they did refuse was to worship Allah alone. They worshipped other gods, also, including idols. This is one sin Allah does not forgive.`,
      `Description of Hud — Allah wanted to guide and discipline these people so He sent a prophet from among them. This prophet was Hud (PBUH), a noble man who handled this task with great resoluteness and tolerance.`,
      `Ibn Jarir reported that he was Hud Ibn Shalikh, Ibn Arfakhshand, Ibn Sam, Ibn Noah (PBUH).`,
      `He also reported that Prophet Hud (PBUH) was from a tribe called Ad Ibn Us Ibn Sam Ibn Noah, who were Arabs living in Al Ahqaf in Yemen between Oman and Hadramaut, on a land called Ashar stretching out into the sea.`,
      `The name of their valley was Mughiith Some traditions claimed that Hud (PBUH) was the first person who spoke Arabic while others claimed that Noah (PBUH) was the first. It was also said that Adam was the first.`,
      `Commentary - Hud's Appeal to his People — Hud (PBUH) condemned idol worship and admonished his people. "MY people, what is the benefit of these stones that you carve with your own hands and worship? In reality it is an insult to the intellect.`,
      `There is only One Deity worthy of worship and that is Allah. Worship of Him and Him alone, is compulsory on you.`,
      `He created you, He provides for you and He is the One Who will cause you to die. He gave you wonderful physiques and blessed you in many ways.`,
      `So believe in Him and do not be blind to His favors, or the same fate that destroyed Noah's people will overtake you." With such reasoning Hud hoped to instill faith in them, but they refused to accept his message.`,
      `His people asked him: "Do you desire to be our master with your call? What payment do you want?"Hud tried to make them understand that he would receive his payment (reward) from Allah; he did not demand anything from them except that they let the light of truth touch their minds and hearts.`,
      `Hud's Appeal to His People - Quranic — Allah the Almighty states: — "And to Ad people We sent their brother Hud. He said: "O my people! Worship Allah! You have no other Ilah (god) but Him; Certainly, you do nothing but invent (lies)! O my people I ask of you no reward for it (the Message).`,
      `My reward is only from Him Who created me.`,
      `Will you not then understand? And O my people! Ask forgiveness of your Lord and then repent to Him, He will send you (from the sky) abundant rain, and add strength to your strength, so do not turn away as Mujrimeen (criminals, disbeliveers in the Oneness of Allah)." They said: "O Hud! No evidence have you brought us and we shall not leave our gods for your mere saying! We are not believers in you.`,
      `All that we say is that some of our gods (false deities) have seized you with evil (madness)." HE said: "I call Allah to witness and bear you witness that I am free from that which you ascribe as partners in worship, and with Him (Allah). SO plot against me, all of you, and give me no respite.`,
      `I put my trust in Allah, my Lord and your Lord! There is not a moving (living) creature but HE has grasp of its forelock. Verily, my Lord is on the Straight Path (the truth). SO if you turn away, still I have conveyed the Message with which I was sent to you.`,
      `My Lord will make another people succeed you, and you will not harm Him in the least. Surely, my Lord is Guardian over all things."(Ch 11:50-57 Quran)`,
      `Hud (pbuh) explains the Day of Judgement — Hud tried to speak to them and to explain about Allah's blessings: how Allah the Almighty had made them Noah's successors, how He had given them strength and power, and how HE sent them rain to revive the soil.`,
      `Hud's people looked about them and found they were the strongest on earth, so they become prouder and more obstinate. Thus they argued a lot with Hud.`,
      `They asked "O Hud! Do you say that later we die and turn into dust, we will be resurrected?" He replied, "Yes, you will come back on the Day of Judgment and each of you will be asked about what you did."`,
      `A peal of laughter was heard after the last statement. "How strange Hud's claims are!" The disbeliveers muttered among themselves. They believed that when man dies his body decays and turns into dust, which is swept away by the wind.`,
      `How could that return to its original state? Then what is the significance of the Day of Judgment? Why does the dead return to life? All these questions were patiently received by Hud. He then addressed his people concerning the Day of Judgment.`,
      `he explained that belief in the Day of Judgment is essential to Allah's justice, teaching them the same thing that every prophet taught about it.`,
    ],
    lessons: [
      "Strength and skill are gifts from Allah, not reasons for arrogance.",
      "Blessings should lead to gratitude, not heedlessness.",
      "Allah's help protects the believers even when they are few.",
    ],
    questions: [
      {
        id: "hud-1",
        question: "Which people was Hud sent to?",
        options: ["'Ad", "Thamud", "Madyan", "Bani Israil"],
        correctIndex: 0,
      },
      {
        id: "hud-2",
        question: "What were the people of 'Ad famous for?",
        options: [
          "Their strength and tall buildings",
          "Their ships",
          "Their books",
          "Their armies of elephants",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-3",
        question: "What was their main sin?",
        options: [
          "Arrogance and worshipping idols",
          "Farming badly",
          "Travelling too much",
          "Building houses",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-4",
        question: "Where did Hud come from?",
        options: [
          "From among the people of 'Ad themselves",
          "From another country",
          "From Egypt",
          "From Madyan",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-5",
        question: "What did Hud call them to do?",
        options: [
          "Worship Allah alone and leave arrogance",
          "Build higher towers",
          "Fight their neighbours",
          "Move to a new land",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-6",
        question: "How did they reply to Hud?",
        options: [
          "They called him foolish and trusted their idols",
          "They believed at once",
          "They asked him to lead them",
          "They stayed silent",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-7",
        question: "What did they think the cloud would bring?",
        options: ["Rain", "Birds", "Darkness", "Snow"],
        correctIndex: 0,
      },
      {
        id: "hud-8",
        question: "What was the punishment of 'Ad?",
        options: [
          "A furious wind",
          "A flood",
          "An earthquake",
          "A swarm of locusts",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-9",
        question: "What happened to Hud and the believers?",
        options: [
          "Allah saved them",
          "They were destroyed too",
          "They were taken prisoner",
          "They lost their faith",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-10",
        question: "What lesson do we take from the people of 'Ad?",
        options: [
          "Power and wealth are tests from Allah",
          "Tall buildings are forbidden",
          "Wind is always a punishment",
          "Strong people are always wrong",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "salih",
    name: "Salih",
    arabicName: "صَالِح",
    title: "The prophet of Thamud and the she-camel",
    emoji: "🐪",
  accent: "from-rose-600 to-pink-700",
    summary:
      "Salih was sent to Thamud, who carved homes in mountains; they killed the she-camel sign and were destroyed.",
    story: [
      "Thamud came after 'Ad. They were clever people who carved beautiful homes into solid mountains and had plenty of water and crops. Like those before them, they worshipped idols and thought their skill made them safe from any harm.",
      "Allah sent Salih (peace be upon him) to call them to worship Allah alone. They asked him for a sign, so Allah sent a special she-camel. Salih told them that the camel must be left alone to drink and graze, and that they must not harm her. For a while they obeyed, but the arrogant leaders grew tired of the test and plotted against her.",
      "A group of them killed the she-camel and then dared Salih to bring the punishment. He told them they had only three days. On the third day a mighty blast and earthquake struck their homes, and the strong carved houses could not protect them. Salih and the believers were saved. Their story shows that clear signs mean nothing to a heart that refuses to be humble.",
      `Description of the People of Thamud — After the destruction of the Ad, the tribe of Thamud succeeded them in power and glory. They also fell to idol-worshipping. As their material wealth increased so, too, did their evil ways while their virtue decreased.`,
      `Like the people of Ad, they erected huge buildings on the plains and hewed beautiful homes out of the hills. Tyranny and oppression became prevalent as evil men ruled the land.`,
      `Description of Salih — So Allah sent unto them His Prophet Salih (PBUH), a man from among them. His name was Salih Ibn Ubeid, Ibn Maseh, Ibn Ubeid, Ibn Hader, Ibn Thamud, Ibn Ather, Ibn Eram, Ibn Noah. He called his people to worship Allah alone, and to not associate partners with Him.`,
      `While some of them believed him, the majority of them disbelieved and harmed him by both words and deeds. Salih directed them:`,
      `"O my people! Worship Allah, you have no other Ilah (god) but Him." (Ch 11:61) Salih was known for his wisdom, purity and goodness and had been greatly respected by his people before Allah's revelation came to him. Salih's people said to him:`,
      `"O Salih! You have been among us as a figure of good hope and we wished for you to be our chief, till this, new thing which you have brought that we leave our gods and worship your God (Allah) alone! Do you now forbid us the worship of what our fathers have worshipped? But we are really in grave doubt as to that which you invite us to monotheism." (CH 11:62 Quran).`,
      `Salih's People Demand a Miracle — They merely wanted to worship the same gods as their fathers had, with no reason, no proof, no thought. The proof of Salih's (PBUH) message was evident, but despite this it was obvious that most of his people did not believe him.`,
      `They doubted his words, thinking he was charmed, and they saw that he would not stop preaching. Fearing that his followers would increase, they tried to put him off by assigning him an important task; to prove that he was a messenger of Allah by performing a miracle.`,
      `Let a unique she camel issue from the mountains. Allah granted Salih this miracle and a huge, unique, she camel appeared from the direction of the mountain.`,
      `The Quranic commentators said that the people of Thamud gathered on a certain day at their meeting place, and the prophet Salih (PBUH) came and addressed them to believe in Allah, reminding them of the favors Allah had granted them.`,
      `Then pointing at a rock, they demanded: "Ask your Lord to make a she camel, which must be 10 months pregnant, tall and attractive, issue from the rock for us." Salih replied: "Look now! If Allah sends you what you have requested, just as you have described, will you believe in that which I have come to you with and have faith in the message I have been sent with?"`,
      `They answered: "Yes." — So he took a vow from them on this, then prayed to Allah the Almighty to grant their request. Allah ordered the distant rock to split asunder, to bringing forth a great ten month pregnant she camel. When their eyes set on it, they were amazed.`,
      `They saw a great thing, a wonderful sight, a dazzling power and clear evidence!`,
      `A number of Salih's people believed, yet most of them continued in their disbelief, stubbornness, and going astray. Allah the Almighty said:`,
      `"We sent the she camel to Thamud as a clear sign, but they did her wrong. (Ch 17:59)`,
      `"Verily the dwellers of Al Hijr (the rocky tract) denied the Messengers. We gave them Our Signs, but they were averse to them. (Ch 15:80-81 Quran)`,
      `There are a number of ancient accounts of this camel and its miraculous nature. It was said that the she camel was miraculous because a rock in the mountain split open and it came forth from it, followed by its young offspring.`,
      `Other accounts said that the she camel used to drink all the water in the wells in one day, and no other animals could approach the water. Still others claimed that the she camel produced milk sufficient for all the people to drink, on the same day that it drank all the water, leaving none for them.`,
      `At first, the people of Thamud were greatly surprised when the she camel issued from the mountain rocks. It was a blessed camel, and its milk sufficient for thousands of men, women and children. If it slept in a place that place was abandoned by other animals.`,
      `Thus it was obvious that is was not an ordinary camel, but one of Allah's signs. It lived among Salih's people, some of whom believed in Allah while the majority continued in their obstinacy and disbelief. Their hatred of Salih turned towards the blessed she camel and became centered on it.`,
      `A conspiracy started to be hatched against the camel by the disbeliveers, and they secretly plotted against it.`,
      `Salih feared that they might kill the camel, so he warned them: — "O my people! This she camel of Allah is a sign to you, leave her to feed on Allah's earth, and touch her not with evil lest a near torment will seize you." (Ch 11:64 Quran)`,
      `For awhile, Salih's people let the camel graze and drink freely, but in their hearts they hated it. However, the miraculous appearance of the unique camel caused many to become Salih's followers, and they clung to their belief in Allah.`,
      `Stories About the She-camel — The disbeliveers now began complaining that this huge she camel with its unusual qualities drank most of the water and frightened their cattle. They laid a plot to kill the camel, and sought the help of their women folk to tempt the men to carry out their commands.`,
    ],
    lessons: [
      "Signs from Allah must be honoured, not tested and mocked.",
      "Kindness to animals is part of taqwa.",
      "Clever people can still be foolish if they reject the truth.",
    ],
    questions: [
      {
        id: "salih-1",
        question: "Which people was Salih sent to?",
        options: ["Thamud", "'Ad", "Madyan", "Quraysh"],
        correctIndex: 0,
      },
      {
        id: "salih-2",
        question: "What were Thamud skilled at?",
        options: [
          "Carving houses in mountains",
          "Sailing ships",
          "Making paper",
          "Riding elephants",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-3",
        question: "What sign did Allah give them?",
        options: ["A she-camel", "A staff", "A cloud", "A river"],
        correctIndex: 0,
      },
      {
        id: "salih-4",
        question: "What were they told about the she-camel?",
        options: [
          "To leave her to drink and graze, and not harm her",
          "To ride her every day",
          "To sell her",
          "To keep her in a house",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-5",
        question: "What did the arrogant group do?",
        options: [
          "They killed the she-camel",
          "They hid her",
          "They followed Salih",
          "They freed her in the desert",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-6",
        question: "How long were they given after that?",
        options: ["Three days", "One year", "Forty days", "One hour"],
        correctIndex: 0,
      },
      {
        id: "salih-7",
        question: "What punishment came to Thamud?",
        options: [
          "A mighty blast and earthquake",
          "A flood",
          "A famine only",
          "A strong wind for eight days",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-8",
        question: "Did their carved homes protect them?",
        options: [
          "No, nothing could protect them",
          "Yes, they were safe inside",
          "Only the largest houses survived",
          "The story does not say",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-9",
        question: "What happened to Salih and the believers?",
        options: [
          "Allah saved them",
          "They were destroyed",
          "They stayed in the city",
          "They lost their faith",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-10",
        question: "What lesson does the she-camel teach us?",
        options: [
          "To respect Allah's signs and be kind to animals",
          "To keep camels as pets",
          "To avoid mountains",
          "To dig more wells",
        ],
        correctIndex: 0,
      },
    ],
  },
];
