import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_2: BuiltInLesson[] = [
  {
    id: "ibrahim",
    name: "Ibrahim",
    arabicName: "إِبْرَاهِيم",
    title: "The friend of Allah who broke the idols",
    emoji: "🕋",
    accent: "from-violet-400 to-purple-500",
    summary:
      "Ibrahim argued against idol worship, survived the fire, and built the Ka'bah with his son Ismail.",
    story: [
      "Ibrahim (peace be upon him) grew up among people who worshipped idols, including his own father who carved them. Even as a young man he used his mind: he looked at the stars, the moon and the sun and understood that none of them could be his Lord, because they all disappear. He knew his Lord was the One who created everything.",
      "He asked his people why they worshipped statues that could not hear, see or help. One day, while they were away at a festival, he broke their idols and left the largest one standing. When they accused him, he told them to ask the big idol — and they had to admit that idols cannot speak. Instead of accepting the truth, they lit a huge fire and threw him into it. Allah commanded the fire to be cool and safe, and Ibrahim walked out unharmed.",
      "Ibrahim was tested again and again: he left his homeland, he was tested with the command about his son, and he passed every test with trust in Allah. With his son Ismail he raised the walls of the Ka'bah in Makkah and prayed that his family and the people who came after would remain in worship of Allah. Allah honoured him with the title Khalilullah, the close friend of Allah.",
    ],
    lessons: [
      "Use your mind — real faith is built on understanding, not blind habit.",
      "Stand for the truth even when you are the only one standing.",
      "Trusting Allah in hard tests brings the greatest honour.",
    ],
    questions: [
      {
        id: "ibrahim-1",
        question: "What did Ibrahim's people worship?",
        options: ["Idols", "The Ka'bah", "Angels", "Fire only"],
        correctIndex: 0,
      },
      {
        id: "ibrahim-2",
        question: "What did Ibrahim notice about the stars, moon and sun?",
        options: [
          "They are beautiful so they must be gods",
          "They disappear, so they cannot be the Lord",
          "They can hear duas",
          "They created the earth",
        ],
        correctIndex: 1,
      },
      {
        id: "ibrahim-3",
        question: "What did Ibrahim do to the idols?",
        options: [
          "He cleaned them",
          "He sold them",
          "He broke them and left the largest one",
          "He hid them",
        ],
        correctIndex: 2,
      },
      {
        id: "ibrahim-4",
        question: "What did he tell his people to do when they accused him?",
        options: [
          "Ask the big idol",
          "Rebuild the idols",
          "Wait for the king",
          "Bring more statues",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-5",
        question: "How did his people try to punish him?",
        options: [
          "They threw him into a fire",
          "They put him in prison forever",
          "They took his wealth",
          "They exiled him to the sea",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-6",
        question: "What happened in the fire?",
        options: [
          "Allah made it cool and safe",
          "It burned him badly",
          "It rained heavily",
          "The people put it out",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-7",
        question: "Which building did Ibrahim raise with his son?",
        options: ["The Ka'bah", "Masjid al-Aqsa", "A palace", "A tower"],
        correctIndex: 0,
      },
      {
        id: "ibrahim-8",
        question: "Which son helped him build it?",
        options: ["Ismail", "Ishaq", "Yaqub", "Yusuf"],
        correctIndex: 0,
      },
      {
        id: "ibrahim-9",
        question: "What honourable title was Ibrahim given?",
        options: [
          "Khalilullah — the close friend of Allah",
          "Kalimullah",
          "Ruhullah",
          "Amin",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-10",
        question: "What do we learn from Ibrahim's tests?",
        options: [
          "Trusting Allah in difficulty raises our rank",
          "Tests only come to bad people",
          "We should avoid all difficulty",
          "Faith needs no patience",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "lut",
    name: "Lut",
    arabicName: "لُوط",
    title: "The prophet who left a corrupt city",
    emoji: "🌋",
    accent: "from-orange-400 to-red-500",
    summary:
      "Lut warned his people against shameless sins and cruelty to guests; only he and his followers were saved.",
    story: [
      "Lut (peace be upon him) was a nephew of Ibrahim and believed in his message. Allah sent him as a prophet to the cities of Sodom, whose people had fallen into open sin. They were shameless in their immorality, they robbed travellers, and they treated guests cruelly instead of honouring them.",
      "Lut called them for many years to fear Allah and to leave their evil habits. They mocked him and threatened to drive him out of the town. Even his own wife did not believe in his message and sided with the people of the city.",
      "One night angels came in the form of guests. When the people of the town came to harm them, the angels told Lut that they had been sent to destroy the city, and ordered him to leave with his believing family and not look back. At dawn the city was overturned and a rain of stones fell upon it. Lut and the believers were saved, but his wife stayed behind and was destroyed with them. The story shows that Allah's punishment falls on stubborn sin, and that hospitality and modesty are part of faith.",
    ],
    lessons: [
      "Modesty and shame are protections given by Allah.",
      "Honouring guests is a sign of a believing heart.",
      "Family ties cannot save a person who rejects the truth.",
    ],
    questions: [
      {
        id: "lut-1",
        question: "How was Lut related to Ibrahim?",
        options: ["His nephew", "His brother", "His son", "His cousin's son"],
        correctIndex: 0,
      },
      {
        id: "lut-2",
        question: "What were the sins of Lut's people?",
        options: [
          "Open immorality, robbery and harming guests",
          "Farming on holy days",
          "Building tall towers",
          "Refusing to pay taxes",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-3",
        question: "How did the people respond to Lut's warnings?",
        options: [
          "They mocked him and threatened to expel him",
          "They repented",
          "They asked for a sign and believed",
          "They left the city",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-4",
        question: "Who came to Lut in the form of guests?",
        options: ["Angels", "Traders", "Kings", "Travellers from Egypt"],
        correctIndex: 0,
      },
      {
        id: "lut-5",
        question: "What did the angels order Lut to do?",
        options: [
          "Leave the city with the believers and not look back",
          "Fight the people",
          "Stay and warn them again",
          "Hide inside his house",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-6",
        question: "What happened to the city?",
        options: [
          "It was overturned and stones rained on it",
          "It was flooded",
          "It was burned by an army",
          "It sank into the sea",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-7",
        question: "What happened to Lut's wife?",
        options: [
          "She stayed behind and was destroyed",
          "She was saved",
          "She became a believer at the end",
          "She travelled to Egypt",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-8",
        question: "Why did the people of the city deserve punishment?",
        options: [
          "They stubbornly refused to leave their sins",
          "They were poor",
          "They lived in the desert",
          "They had no prophet",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-9",
        question: "What good manners does this story highlight?",
        options: [
          "Honouring guests and keeping modesty",
          "Eating a lot",
          "Speaking loudly",
          "Travelling at night",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-10",
        question: "What does Lut's wife teach us?",
        options: [
          "Being close to a prophet does not save someone who rejects faith",
          "Women cannot be believers",
          "Family always follows the truth",
          "Looking back is a small matter",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ismail",
    name: "Ismail",
    arabicName: "إِسْمَاعِيل",
    title: "The patient son and builder of the Ka'bah",
    emoji: "💧",
    accent: "from-teal-400 to-emerald-500",
    summary:
      "Ismail trusted Allah in the greatest test, and the well of Zamzam sprang for him as a baby.",
    story: [
      "Ismail (peace be upon him) was the son of Ibrahim and Hajar. By Allah's command, Ibrahim left them in the empty valley of Makkah with a little food and water. When the water ran out, Hajar ran between the hills of Safa and Marwah searching for help. Allah caused water to gush from the ground near the baby, and that spring is the well of Zamzam, which still flows today.",
      "As Ismail grew, Ibrahim saw in a dream that he was commanded to sacrifice his beloved son. He told Ismail about it, and Ismail answered with amazing calm: do what you have been commanded, and you will find me patient. When they both submitted, Allah called out that the test was complete and sent a ram to be sacrificed instead. Muslims remember this act of obedience every year in Eid al-Adha.",
      "Father and son later raised the walls of the Ka'bah together, praying that Allah accept their work. Ismail became a prophet to the people of that region and was known for keeping his promises. From his descendants came the final Prophet, Muhammad (peace be upon him).",
    ],
    lessons: [
      "Trust that Allah provides even in an empty desert.",
      "Real obedience is calm and willing, not forced.",
      "Keeping promises is a prophetic quality.",
    ],
    questions: [
      {
        id: "ismail-1",
        question: "Who were Ismail's parents?",
        options: [
          "Ibrahim and Hajar",
          "Ibrahim and Sarah",
          "Yaqub and Rahil",
          "Nuh and his wife",
        ],
        correctIndex: 0,
      },
      {
        id: "ismail-2",
        question: "Where were Hajar and baby Ismail left?",
        options: [
          "The valley of Makkah",
          "Egypt",
          "Madyan",
          "Jerusalem",
        ],
        correctIndex: 0,
      },
      {
        id: "ismail-3",
        question: "Between which two hills did Hajar search for help?",
        options: ["Safa and Marwah", "Uhud and Badr", "Judi and Sinai", "Arafat and Mina"],
        correctIndex: 0,
      },
      {
        id: "ismail-4",
        question: "What is the name of the spring that appeared?",
        options: ["Zamzam", "Kawthar", "Salsabil", "Tasnim"],
        correctIndex: 0,
      },
      {
        id: "ismail-5",
        question: "How did Ibrahim learn about the command to sacrifice his son?",
        options: ["Through a dream", "From a letter", "From an angel in the market", "From his people"],
        correctIndex: 0,
      },
      {
        id: "ismail-6",
        question: "How did Ismail respond?",
        options: [
          "He told his father to do as he was commanded and promised patience",
          "He ran away",
          "He asked for a delay",
          "He refused",
        ],
        correctIndex: 0,
      },
      {
        id: "ismail-7",
        question: "What did Allah send in place of Ismail?",
        options: ["A ram", "A camel", "A cow", "A bird"],
        correctIndex: 0,
      },
      {
        id: "ismail-8",
        question: "Which Eid remembers this event?",
        options: ["Eid al-Adha", "Eid al-Fitr", "Eid al-Ghadir", "Laylat al-Qadr"],
        correctIndex: 0,
      },
      {
        id: "ismail-9",
        question: "What did Ismail build with his father?",
        options: ["The Ka'bah", "A palace", "A city wall", "A ship"],
        correctIndex: 0,
      },
      {
        id: "ismail-10",
        question: "Which final prophet came from Ismail's descendants?",
        options: ["Muhammad (peace be upon him)", "Isa", "Musa", "Dawud"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ishaq",
    name: "Ishaq",
    arabicName: "إِسْحَاق",
    title: "The good news given to Ibrahim in old age",
    emoji: "🌟",
    accent: "from-lime-400 to-green-500",
    summary:
      "Ishaq was born to Ibrahim and Sarah in their old age and became a prophet after his father.",
    story: [
      "Ibrahim and his wife Sarah had grown very old and had no child together. One day guests came to Ibrahim's home, and he quickly prepared food for them, as generous people do. The guests were angels, and they brought news that Sarah would have a son. Sarah was astonished and laughed, asking how she could have a child at her age. The angels replied that this was the decree of Allah, and nothing is difficult for Him.",
      "The promised son was Ishaq (peace be upon him). He grew up in a household built on worship, honesty and generosity, and Allah made him a prophet. He carried on the message of his father, calling people to worship Allah alone and to keep good character.",
      "Allah blessed Ishaq with a son, Yaqub, who also became a prophet. Through this family a long line of prophets continued among Bani Israil. The story reminds us that Allah answers duas in His own time, and that His promise never fails even when it seems impossible.",
    ],
    lessons: [
      "Nothing is impossible for Allah — never lose hope in dua.",
      "Generosity to guests is a habit of the righteous.",
      "A home built on worship raises righteous children.",
    ],
    questions: [
      {
        id: "ishaq-1",
        question: "Who were Ishaq's parents?",
        options: [
          "Ibrahim and Sarah",
          "Ibrahim and Hajar",
          "Yaqub and Rahil",
          "Lut and his wife",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-2",
        question: "Who brought the good news of his birth?",
        options: ["Angels in the form of guests", "A merchant", "A king", "A neighbour"],
        correctIndex: 0,
      },
      {
        id: "ishaq-3",
        question: "How did Ibrahim treat the guests?",
        options: [
          "He quickly prepared food for them",
          "He sent them away",
          "He ignored them",
          "He asked them for money",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-4",
        question: "Why was Sarah astonished?",
        options: [
          "She and Ibrahim were very old",
          "She did not know the guests",
          "She was travelling",
          "She had many children already",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-5",
        question: "What did the angels say about Allah's decree?",
        options: [
          "Nothing is difficult for Allah",
          "It might change",
          "It depends on people",
          "It was only a hope",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-6",
        question: "What did Ishaq become?",
        options: ["A prophet", "A king only", "A merchant", "A judge only"],
        correctIndex: 0,
      },
      {
        id: "ishaq-7",
        question: "Which prophet was Ishaq's son?",
        options: ["Yaqub", "Yusuf", "Musa", "Harun"],
        correctIndex: 0,
      },
      {
        id: "ishaq-8",
        question: "What message did Ishaq carry?",
        options: [
          "To worship Allah alone and keep good character",
          "To collect wealth",
          "To build large cities",
          "To fight neighbouring tribes",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-9",
        question: "Through this family, which nation received many prophets?",
        options: ["Bani Israil", "The people of 'Ad", "Thamud", "Madyan"],
        correctIndex: 0,
      },
      {
        id: "ishaq-10",
        question: "What lesson does the birth of Ishaq teach?",
        options: [
          "Allah answers dua in His own time and His promise never fails",
          "Old age prevents blessings",
          "Guests should not be fed",
          "Laughing is forbidden",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "yaqub",
    name: "Yaqub",
    arabicName: "يَعْقُوب",
    title: "The patient father of Yusuf",
    emoji: "🕊️",
    accent: "from-cyan-400 to-blue-500",
    summary:
      "Yaqub, also called Israil, showed beautiful patience when he lost his beloved son Yusuf.",
    story: [
      "Yaqub (peace be upon him) was the son of Ishaq and the grandson of Ibrahim. He is also called Israil, and his twelve sons became the tribes of Bani Israil. He raised his children to worship Allah alone and, when he was dying, his final advice to them was to hold on to Islam — submission to Allah.",
      "Yaqub loved his son Yusuf dearly. When Yusuf told him about a dream of eleven stars, the sun and the moon prostrating to him, Yaqub understood that his son would be given something great and told him not to tell his brothers. Later the brothers took Yusuf away and returned with a shirt stained with blood, claiming a wolf had eaten him. Yaqub did not believe them, but he did not despair either. He said he would be patient and seek help from Allah alone.",
      "For many years he grieved, yet he kept telling his sons never to lose hope in Allah's mercy. In the end Allah reunited him with Yusuf in Egypt, and his eyesight and joy were restored. His story is the finest example of 'beautiful patience' — sadness that does not turn into complaint against Allah.",
    ],
    lessons: [
      "Beautiful patience means grieving without complaining against Allah.",
      "Never lose hope in Allah's mercy, no matter how long the test.",
      "A parent's most important gift is teaching tawhid.",
    ],
    questions: [
      {
        id: "yaqub-1",
        question: "Who was Yaqub's father?",
        options: ["Ishaq", "Ismail", "Ibrahim", "Yusuf"],
        correctIndex: 0,
      },
      {
        id: "yaqub-2",
        question: "By which other name is Yaqub known?",
        options: ["Israil", "Kalimullah", "Ruhullah", "Al-Amin"],
        correctIndex: 0,
      },
      {
        id: "yaqub-3",
        question: "How many sons did he have?",
        options: ["Twelve", "Seven", "Four", "Twenty"],
        correctIndex: 0,
      },
      {
        id: "yaqub-4",
        question: "What was his final advice to his sons?",
        options: [
          "To hold on to Islam and worship Allah alone",
          "To divide his wealth",
          "To travel to Egypt",
          "To build a temple",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-5",
        question: "What did Yusuf see in his dream?",
        options: [
          "Eleven stars, the sun and the moon prostrating",
          "Seven cows",
          "A ship on the sea",
          "A garden of palm trees",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-6",
        question: "Why did Yaqub tell Yusuf not to tell his brothers?",
        options: [
          "He feared their jealousy",
          "The dream was unimportant",
          "They would not understand dreams",
          "He wanted to tell them himself",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-7",
        question: "What did the brothers claim happened to Yusuf?",
        options: [
          "A wolf had eaten him",
          "He was lost in a storm",
          "He travelled to Egypt",
          "He fell ill",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-8",
        question: "How did Yaqub react to the news?",
        options: [
          "With patience, seeking help from Allah",
          "With anger and revenge",
          "By giving up faith",
          "By punishing his sons",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-9",
        question: "What did he keep telling his sons about Allah's mercy?",
        options: [
          "Never to lose hope in it",
          "That it is only for prophets",
          "That it had ended",
          "That it needs no dua",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-10",
        question: "How did his long test end?",
        options: [
          "Allah reunited him with Yusuf in Egypt",
          "He never saw Yusuf again",
          "He moved to Makkah",
          "His sons left him",
        ],
        correctIndex: 0,
      },
    ],
  },
];
