import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_3: BuiltInLesson[] = [
  {
    id: "yusuf",
    name: "Yusuf",
    arabicName: "يُوسُف",
    title: "From the well to the treasury of Egypt",
    emoji: "👑",
    accent: "from-yellow-400 to-amber-500",
    summary:
      "Yusuf was thrown into a well, sold as a slave, jailed unjustly, then made a minister who forgave his brothers.",
    story: [
      "Yusuf (peace be upon him) was the beloved son of Yaqub. As a boy he dreamt of eleven stars, the sun and the moon prostrating to him. His brothers became jealous, threw him into a well, and told their father that a wolf had eaten him. A passing caravan found Yusuf and sold him in Egypt, where he grew up in the house of a powerful man.",
      "Allah gave Yusuf beauty, wisdom and the ability to explain dreams. When he was tempted to sin, he refused and chose prison over disobeying Allah. He spent years in jail although he was innocent, and he used that time to call his fellow prisoners to worship Allah alone. Then the king had a strange dream about seven fat cows eaten by seven thin ones, and seven green ears of corn and seven dry ones. Yusuf explained it: seven years of plenty would be followed by seven years of drought, so grain must be stored carefully.",
      "The king was so impressed that he freed Yusuf and put him in charge of the treasury of Egypt. During the famine his brothers came to buy food and did not recognise him. When he finally revealed himself, he did not take revenge; he said there was no blame on them and asked Allah to forgive them. He was reunited with his father, and his childhood dream came true.",
    ],
    lessons: [
      "Choose obedience to Allah even when sin is easy and hidden.",
      "Patience and skill turn hardship into leadership.",
      "Forgiveness is stronger than revenge.",
    ],
    questions: [
      {
        id: "yusuf-1",
        question: "What did Yusuf see in his childhood dream?",
        options: [
          "Eleven stars, the sun and the moon prostrating",
          "Seven thin cows",
          "A caravan in the desert",
          "A river of milk",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-2",
        question: "What did his brothers do to him?",
        options: [
          "Threw him into a well",
          "Sent him to school",
          "Took him to Makkah",
          "Left him in a garden",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-3",
        question: "What did they tell Yaqub?",
        options: [
          "That a wolf had eaten him",
          "That he had run away",
          "That he was in prison",
          "That he had drowned",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-4",
        question: "Where was Yusuf taken and sold?",
        options: ["Egypt", "Madyan", "Yemen", "Shaam"],
        correctIndex: 0,
      },
      {
        id: "yusuf-5",
        question: "What special knowledge did Allah give him?",
        options: [
          "Explaining dreams",
          "Healing the sick",
          "Speaking to animals",
          "Controlling the wind",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-6",
        question: "What did Yusuf choose when he was tempted to sin?",
        options: [
          "Prison rather than disobeying Allah",
          "To run away from Egypt",
          "To keep silent",
          "To ask the king for help",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-7",
        question: "What did he do while in prison?",
        options: [
          "Called the prisoners to worship Allah alone",
          "Refused to speak",
          "Planned revenge",
          "Wrote letters to the king",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-8",
        question: "What did the king's dream mean?",
        options: [
          "Seven years of plenty then seven years of drought",
          "A war was coming",
          "The Nile would dry up forever",
          "The king would travel",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-9",
        question: "What position was Yusuf given?",
        options: [
          "In charge of the treasury and food stores of Egypt",
          "Chief of the army",
          "A judge in prison",
          "A teacher of children",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-10",
        question: "How did Yusuf treat his brothers at the end?",
        options: [
          "He forgave them and asked Allah to forgive them",
          "He punished them",
          "He sent them away",
          "He put them in prison",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ayyub",
    name: "Ayyub",
    arabicName: "أَيُّوب",
    title: "The prophet of patience through illness and loss",
    emoji: "🌾",
    accent: "from-emerald-400 to-green-600",
    summary:
      "Ayyub lost his wealth, children and health, yet never stopped praising Allah — and was restored.",
    story: [
      "Ayyub (peace be upon him) was a prophet who had been given great blessings: wealth, land, a large family and good health. He was grateful, generous to the poor, and constant in worship. Then Allah tested him: his wealth was lost, his children died, and his body was struck by a long illness so that people avoided him.",
      "Through all of it, Ayyub never complained against his Lord. He remembered that the same Allah who gave the blessings had the right to take them back. His wife stayed loyal and cared for him, and he continued to remember Allah with a thankful heart for many years.",
      "At last he made a gentle dua: 'Indeed, hardship has struck me, and You are the Most Merciful of the merciful.' Allah answered him. He was told to strike the ground with his foot, and a spring appeared from which he washed and drank, and his health returned. Allah restored his family and wealth, and praised him in the Qur'an as an excellent servant who always turned back to Him.",
    ],
    lessons: [
      "Gratitude in good times prepares the heart for hard times.",
      "Complaining is different from making dua — dua is worship.",
      "Allah's relief comes after true patience.",
    ],
    questions: [
      {
        id: "ayyub-1",
        question: "What blessings did Ayyub have at first?",
        options: [
          "Wealth, family and good health",
          "A kingdom and army",
          "Only knowledge",
          "Only land",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-2",
        question: "What was taken from him in his test?",
        options: [
          "His wealth, his children and his health",
          "Only his money",
          "Only his health",
          "His home only",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-3",
        question: "How did Ayyub behave during the test?",
        options: [
          "He stayed patient and kept praising Allah",
          "He complained loudly",
          "He stopped praying",
          "He blamed his family",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-4",
        question: "Who stayed loyal and cared for him?",
        options: ["His wife", "His neighbours", "The king", "His servants"],
        correctIndex: 0,
      },
      {
        id: "ayyub-5",
        question: "What did his dua include?",
        options: [
          "That Allah is the Most Merciful of the merciful",
          "A demand for his wealth back",
          "A complaint about people",
          "A request for a kingdom",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-6",
        question: "What was he told to do to find a cure?",
        options: [
          "Strike the ground with his foot",
          "Travel to Egypt",
          "Fast for a month",
          "Climb a mountain",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-7",
        question: "What appeared from the ground?",
        options: ["A spring of water", "A tree", "Gold", "A camel"],
        correctIndex: 0,
      },
      {
        id: "ayyub-8",
        question: "What did Allah restore to him?",
        options: [
          "His health, family and wealth",
          "Only his health",
          "Only his wealth",
          "Nothing in this life",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-9",
        question: "How does the Qur'an describe Ayyub?",
        options: [
          "An excellent servant who always turned back to Allah",
          "A strong warrior",
          "A wealthy king",
          "A skilled builder",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-10",
        question: "What is the main lesson of his story?",
        options: [
          "Patience with gratitude brings Allah's relief",
          "Illness is a punishment",
          "Wealth is bad",
          "Duas are not answered",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "shuayb",
    name: "Shu'ayb",
    arabicName: "شُعَيْب",
    title: "The prophet of honest trade in Madyan",
    emoji: "⚖️",
    accent: "from-indigo-400 to-blue-600",
    summary:
      "Shu'ayb called the people of Madyan to worship Allah and to stop cheating in weights and measures.",
    story: [
      "The people of Madyan were traders on a busy route. They worshipped idols, and in their markets they cheated: they gave people less than they paid for, and took more than was due. They also frightened travellers and spread corruption in the land.",
      "Allah sent Shu'ayb (peace be upon him) to them. He was such a clear and gentle speaker that scholars call him the 'orator of the prophets'. He told them two things together: worship Allah alone, and give full measure and weight. He reminded them that whatever remains with Allah is better for them than dishonest profit, and that he did not want to become a policeman over them — he wanted them to fear Allah in their own hearts.",
      "Most of them refused and mocked him, saying his prayer had no power over their business. In the end a terrible punishment struck them: a mighty blast and shaking that left their homes empty. Shu'ayb and the believers were saved. His story teaches that honest work is part of faith; a person cannot pray in the masjid and cheat in the market.",
    ],
    lessons: [
      "Honesty in business is a direct command from Allah.",
      "Worship and good manners cannot be separated.",
      "Small daily fairness is a great act of faith.",
    ],
    questions: [
      {
        id: "shuayb-1",
        question: "Which people was Shu'ayb sent to?",
        options: ["Madyan", "'Ad", "Thamud", "Egypt"],
        correctIndex: 0,
      },
      {
        id: "shuayb-2",
        question: "What was their main wrongdoing in the market?",
        options: [
          "Cheating in weights and measures",
          "Closing early",
          "Selling only to travellers",
          "Charging no tax",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-3",
        question: "What title do scholars give Shu'ayb?",
        options: [
          "The orator of the prophets",
          "The friend of Allah",
          "The spirit of Allah",
          "The seal of the prophets",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-4",
        question: "What two things did he call them to?",
        options: [
          "Worship Allah alone and trade honestly",
          "Pay more tax and travel less",
          "Build a temple and fast",
          "Move to a new land and farm",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-5",
        question: "What did he say is better than dishonest profit?",
        options: [
          "What remains with Allah",
          "Borrowing money",
          "A bigger shop",
          "More customers",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-6",
        question: "How did most of his people respond?",
        options: [
          "They mocked him and refused",
          "They repented immediately",
          "They asked him to lead the city",
          "They closed their markets",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-7",
        question: "What else were the people of Madyan doing wrong?",
        options: [
          "Frightening travellers and spreading corruption",
          "Building ships",
          "Farming on the road",
          "Teaching their children",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-8",
        question: "What punishment came to them?",
        options: [
          "A mighty blast and shaking",
          "A flood",
          "A wind for eight days",
          "A rain of birds",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-9",
        question: "What happened to Shu'ayb and the believers?",
        options: ["They were saved", "They were destroyed", "They were exiled", "They were imprisoned"],
        correctIndex: 0,
      },
      {
        id: "shuayb-10",
        question: "What lesson do we take for our own lives?",
        options: [
          "Being honest in work and money is part of worship",
          "Trade is not allowed",
          "Only prayer matters",
          "Measuring is unnecessary",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "musa",
    name: "Musa",
    arabicName: "مُوسَى",
    title: "The prophet who spoke with Allah",
    emoji: "🌊",
    accent: "from-blue-500 to-indigo-600",
    summary:
      "Musa was saved as a baby, given the staff and the Tawrah, and led Bani Israil through the parted sea.",
    story: [
      "Pharaoh ruled Egypt and claimed to be a god. When he ordered the baby boys of Bani Israil to be killed, the mother of Musa (peace be upon him) placed her baby in a basket on the Nile, trusting Allah. The basket reached Pharaoh's own palace, and his wife Asiya loved the child and raised him. Musa grew up strong, and after defending a man and leaving Egypt, he worked for years in Madyan and married there.",
      "On his way back, at the valley of Tuwa, Allah spoke to him directly from a blessed tree — which is why he is called Kalimullah, the one who spoke with Allah. Allah gave him two great signs: his staff, which became a snake, and his hand, which shone white. Allah also gave him his brother Harun as a helper, and sent them both to Pharaoh with the message: worship Allah alone and free Bani Israil.",
      "Pharaoh refused, gathered his magicians and challenged Musa. When the magicians saw the staff swallow their tricks, they believed in Allah at once. Later Musa led his people out of Egypt. When the sea blocked their path and Pharaoh's army closed in, Allah told Musa to strike the sea with his staff; it parted and they crossed safely, while Pharaoh and his army drowned. Musa received the Tawrah and continued to guide his people with patience.",
    ],
    lessons: [
      "Trust in Allah's plan even when it looks frightening.",
      "Truth is stronger than magic and propaganda.",
      "Leaders must be patient with the people they guide.",
    ],
    questions: [
      {
        id: "musa-1",
        question: "Why did Musa's mother place him in the river?",
        options: [
          "Pharaoh ordered baby boys of Bani Israil to be killed",
          "She was travelling",
          "She was poor",
          "The city was flooded",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-2",
        question: "Who raised Musa in the palace?",
        options: [
          "Asiya, Pharaoh's wife",
          "His aunt in Madyan",
          "A priest of Egypt",
          "A merchant family",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-3",
        question: "Where did Musa work after leaving Egypt?",
        options: ["Madyan", "Yemen", "Shaam", "Makkah"],
        correctIndex: 0,
      },
      {
        id: "musa-4",
        question: "Why is Musa called Kalimullah?",
        options: [
          "Allah spoke to him directly",
          "He wrote many books",
          "He was very brave",
          "He led an army",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-5",
        question: "What were the two signs given to him?",
        options: [
          "The staff and his shining hand",
          "A ring and a cloak",
          "A book and a pen",
          "A cloud and rain",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-6",
        question: "Who was sent with him as a helper?",
        options: ["His brother Harun", "Yusha", "Shu'ayb", "Dawud"],
        correctIndex: 0,
      },
      {
        id: "musa-7",
        question: "What did the magicians do when they saw the truth?",
        options: [
          "They believed in Allah",
          "They ran away",
          "They attacked Musa",
          "They asked for money",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-8",
        question: "How did Bani Israil cross the sea?",
        options: [
          "Allah parted it when Musa struck it with his staff",
          "They used boats",
          "They built a bridge",
          "They walked around it",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-9",
        question: "What happened to Pharaoh and his army?",
        options: ["They drowned", "They turned back", "They believed", "They stayed in Egypt"],
        correctIndex: 0,
      },
      {
        id: "musa-10",
        question: "Which book was revealed to Musa?",
        options: ["The Tawrah", "The Injil", "The Zabur", "The Qur'an"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "harun",
    name: "Harun",
    arabicName: "هَارُون",
    title: "The eloquent brother and helper of Musa",
    emoji: "🗣️",
    accent: "from-purple-400 to-fuchsia-500",
    summary:
      "Harun was given to Musa as a helper; he spoke clearly and stayed gentle when his people went astray.",
    story: [
      "When Allah sent Musa to Pharaoh, Musa made a dua asking for his brother Harun (peace be upon him) to be sent with him, because Harun spoke more clearly and would strengthen him. Allah accepted the dua and made Harun a prophet too. They went together to the greatest tyrant of their time and delivered the message with courage and good words.",
      "Harun supported his brother in every difficulty. He helped guide Bani Israil out of Egypt and taught them what Allah had revealed. When Musa left for the mountain to receive the Tawrah, he put Harun in charge of the people.",
      "During that time a man called Samiri made a golden calf, and many people began to worship it. Harun warned them strongly that this was a test and that their Lord was Ar-Rahman, but they refused to listen and threatened him. He avoided fighting them so the nation would not split, and waited for Musa to return. Musa was angry at first, but understood, and both prayed for forgiveness. Their story teaches the value of teamwork, gentleness and holding a community together.",
    ],
    lessons: [
      "Ask Allah for helpers — good work needs teamwork.",
      "Speak clearly and kindly when calling to the truth.",
      "Wisdom sometimes means avoiding a fight to protect unity.",
    ],
    questions: [
      {
        id: "harun-1",
        question: "Who asked for Harun to be sent as a helper?",
        options: ["Musa", "Pharaoh", "Bani Israil", "Shu'ayb"],
        correctIndex: 0,
      },
      {
        id: "harun-2",
        question: "Why was Harun a good helper?",
        options: [
          "He spoke very clearly",
          "He was a soldier",
          "He was a builder",
          "He was a merchant",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-3",
        question: "Was Harun also a prophet?",
        options: ["Yes", "No", "Only a teacher", "Only a leader"],
        correctIndex: 0,
      },
      {
        id: "harun-4",
        question: "Who did they both go to warn?",
        options: ["Pharaoh", "The people of 'Ad", "Thamud", "The people of Madyan"],
        correctIndex: 0,
      },
      {
        id: "harun-5",
        question: "Who was left in charge when Musa went to the mountain?",
        options: ["Harun", "Samiri", "Yusha", "Pharaoh's wife"],
        correctIndex: 0,
      },
      {
        id: "harun-6",
        question: "What did Samiri make?",
        options: ["A golden calf", "A temple", "A ship", "An idol of stone"],
        correctIndex: 0,
      },
      {
        id: "harun-7",
        question: "What did Harun tell the people?",
        options: [
          "That it was a test and their Lord is Ar-Rahman",
          "That the calf was allowed",
          "To wait silently",
          "To leave the camp",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-8",
        question: "Why did Harun avoid fighting them?",
        options: [
          "So the nation would not split apart",
          "He was afraid of Samiri",
          "He agreed with them",
          "He was ill",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-9",
        question: "What did Musa do when he returned?",
        options: [
          "He was angry, then understood and prayed for forgiveness",
          "He left the people",
          "He worshipped the calf",
          "He punished Harun",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-10",
        question: "What lesson do we learn from Harun?",
        options: [
          "Good work needs teamwork, gentle speech and unity",
          "Leaders should be harsh",
          "Speaking clearly is unimportant",
          "It is fine to worship images",
        ],
        correctIndex: 0,
      },
    ],
  },
];
