import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_5: BuiltInLesson[] = [
  {
    id: "yunus",
    name: "Yunus",
    arabicName: "يُونُس",
    title: "The prophet of the whale and the city that repented",
    emoji: "🐋",
    accent: "from-cyan-500 to-blue-600",
    summary:
      "Yunus left his people, was swallowed by a great fish, made dua in the darkness and was saved.",
    story: [
      "Yunus (peace be upon him) was sent to the people of Nineveh. He called them to worship Allah alone, but they kept refusing. Feeling that they would never believe, he left the city before Allah gave him permission to do so, and boarded a ship.",
      "A violent storm struck the ship. The sailors drew lots, and Yunus was thrown into the sea, where a great fish swallowed him. In that total darkness he did not despair; he called out: 'There is no god except You; glory be to You. Indeed, I was among the wrongdoers.' Allah heard his dua, and the fish released him onto the shore. Allah says that if Yunus had not been among those who glorify Allah, he would have remained there.",
      "Meanwhile, his people saw the signs of punishment approaching and repented together, sincerely turning to Allah — and Allah removed the punishment from them. Yunus returned to a city full of believers. His story teaches that dua in the hardest moment is never wasted, and that sincere repentance can change a nation's fate.",
      `Description of Jonah's People — Prophet Jonah (Yunus) (pbuh) also known as Dhan-Nun. About his people Almighty Allah said:`,
      `"Was there any town community that believed after seeing the punishment, and its Faith at that moment, saved it from the punishment? (the answer is none)--except the people of Jonah; when they believed, We removed from them the torment of disgrace in the life of the present world, and permitted them to enjoy for a while.`,
      `(Ch 10:98 Quran)`,
      `The inhabitants of the town of Nineveh were idolaters who lived a shameless life. Prophet Jonah (pbuh) was sent to teach them the worship of Allah. The people disliked his interference in their way of worship, so they argued.`,
      `"We and our forefathers have worshipped these gods for many years and no harm has come to us."`,
      `Jonah Leaves His People — Try as he might to convince them of the foolishness of idolatry and of the goodness of Allah's laws, the ignored him. He warned them that if they kept on with their foolishness, Allah's punishment would soon follow.`,
      `Instead of fearing Allah, they told Jonah that they were not afraid of his threats. "Let it happen," they told him. Jonah was disheartened. "in that case, I will leave you to your misery!" so saying, he left Nineveh, fearing that Allah's anger would soon follow.`,
      `"Remember Dhan Nun (Jonah), when he went off in anger, and imagined that We shall not punish him (the calamities which had befallen him)! (ch 21:87)`,
      `The People are Forgiven — Hardly had he left the city when the skies began to change color and looked as if they were on fire. The people were filled with fear by this sight. They recalled the destruction of the people of 'Ad, Thamud and Noah.`,
      `Was theirs to be a similar fate? Slowly faith penetrated their hearts. They all gathered on the mountain and started to beseech Allah for His mercy and forgiveness. The mountains echoed with their cries. It was a momentous hour, filled with sincere repentance.`,
      `Allah removed His wrath and showered His blessings upon them once again. When the threatening storm was lifted, they prayed for the return of Jonah so that he could guide them.`,
      `The Storm at Sea — Meanwhile, Jonah had boarded a small ship in the company of other passengers. It sailed all day in calm waters with a good wind blowing at the sails. When night came, the sea suddenly changed. A horrible storm blew as if it were going to split the ship into pieces.`,
      `The waves looked wild. They rose up as high as mountains then plunged down like valleys, tossing the ship and sweeping over the deck. Behind the ship, a large whale was splitting the water and opening its mouth.`,
      `A command had been issued from Almighty Allah to one of the greatest whales of the sea to surface. It obeyed. The whale hurried to the surface of the sea and followed the ship as it had been commanded. The tempest continued and the chief crewman asked the crew to lighten the ship's heavy load.`,
      `They threw their baggage overboard, but this was not enough. Their safety lay in reducing the weight further, so they decided among themselves to lighten their load by removing at least one person.`,
      `Jonah Jumps into the Sea — The captain directed: We will make lots with all of the travelers' names. The one whose name is drawn will be thrown into the sea." Jonah knew this was one of the seamen's traditions when facing a tempest.`,
      `It was a strange polytheistic tradition, but it was practiced at that time. Jonah's affliction and crisis began. Here was the prophet, subjected to polytheistic rules that considered the sea and the wind to have gods that riot. The captain had to please these gods.`,
      `Jonah reluctantly participated in the lot, and his name was added to the other travelers' names. The lot was drawn and "Jonah" appeared. Since they knew him to be the most honorable among them, they did not wish to throw him into the angry sea. Therefore, they decided to draw a second lot.`,
      `Again Jonah's name was drawn. They gave him a final chance and drew a third lot. Unfortunately for Jonah, his name came up again. Jonah realized that Allah's hand was in all this, for he had abandoned his mission without Allah's consent.`,
      `The matter was over, and it was decided that Jonah should throw himself into the water. Jonah stood at the edge of the ship looking at the furious sea. It was night and there was no moon. The stars were hidden behind a black fog.`,
      `But before he could be thrown overboard, Jonah kept mentioning Allah's name as he jumped into the raging sea and disappeared beneath the huge waves.`,
      `The Whale Swallows Jonah — The whale found Jonah floating on the waves before it. It swallowed Jonah into its furious stomach and shut its ivory teeth on him as if they were white bolts locking the door of his prison.`,
      `The whale dived to the bottom of the sea, the sea that runs in the abyss of darkness. Three layers of darkness enveloped him, one above the other; the darkness of the whale's stomach, the darkness of the bottom of the sea, the darkness of the night.`,
      `Jonah imaged himself to be dead, but his senses became alert when he found he could move. He knew that he was alive and imprisoned in the midst of three layers of darkness. His heart was moved by remembering Allah. His tongue released soon after saying:`,
    ],
    lessons: [
      "Never give up on people too quickly.",
      "Dua works even in the darkest situation.",
      "Sincere collective repentance brings Allah's mercy.",
    ],
    questions: [
      {
        id: "yunus-1",
        question: "To which city was Yunus sent?",
        options: ["Nineveh", "Makkah", "Egypt", "Madyan"],
        correctIndex: 0,
      },
      {
        id: "yunus-2",
        question: "Why did he leave his people?",
        options: [
          "He felt they would never believe",
          "He was ill",
          "He was exiled",
          "He wanted to trade",
        ],
        correctIndex: 0,
      },
      {
        id: "yunus-3",
        question: "What happened to the ship he boarded?",
        options: [
          "A violent storm struck it",
          "It sank at once",
          "It was attacked",
          "It reached Egypt safely",
        ],
        correctIndex: 0,
      },
      {
        id: "yunus-4",
        question: "What swallowed Yunus?",
        options: ["A great fish", "A wave", "A crocodile", "A shark's net"],
        correctIndex: 0,
      },
      {
        id: "yunus-5",
        question: "What did he say in the darkness?",
        options: [
          "There is no god except You; glory be to You; I was among the wrongdoers",
          "Nothing at all",
          "He complained about the sailors",
          "He asked for wealth",
        ],
        correctIndex: 0,
      },
      {
        id: "yunus-6",
        question: "What does Allah say would have happened without his glorification?",
        options: [
          "He would have remained inside the fish",
          "The ship would have sunk",
          "The city would be destroyed",
          "The sea would dry up",
        ],
        correctIndex: 0,
      },
      {
        id: "yunus-7",
        question: "How was he saved?",
        options: [
          "The fish released him onto the shore",
          "A boat found him",
          "He swam out",
          "An angel carried him",
        ],
        correctIndex: 0,
      },
      {
        id: "yunus-8",
        question: "What did his people do while he was away?",
        options: [
          "They repented sincerely",
          "They built idols",
          "They left the city",
          "They fought each other",
        ],
        correctIndex: 0,
      },
      {
        id: "yunus-9",
        question: "What happened to the punishment they feared?",
        options: [
          "Allah removed it from them",
          "It destroyed the city",
          "It was delayed one year",
          "It struck only the leaders",
        ],
        correctIndex: 0,
      },
      {
        id: "yunus-10",
        question: "What is the main lesson of this story?",
        options: [
          "Dua and sincere repentance are always accepted by Allah",
          "Sailing is dangerous",
          "People never change",
          "Prophets do not make dua",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "zakariyya",
    name: "Zakariyya",
    arabicName: "زَكَرِيَّا",
    title: "The prophet whose quiet dua was answered",
    emoji: "🤲",
    accent: "from-teal-400 to-cyan-600",
    summary:
      "Zakariyya prayed secretly for a righteous child in his old age, and Allah gave him Yahya.",
    story: [
      "Zakariyya (peace be upon him) served in the house of worship among Bani Israil and cared for Maryam when she was young. He noticed that Allah provided for her in a wonderful way, and this increased his hope in Allah's power.",
      "He was very old and his wife could not have children, yet he called upon his Lord with a quiet, secret dua: 'My Lord, do not leave me alone, and You are the best of inheritors,' asking for a righteous heir who would continue calling people to Allah. He never let his age make him think that Allah's power was limited.",
      "Allah answered him and gave him a son, Yahya, and made him pure and obedient. As a sign, Zakariyya did not speak to people for three days except by gestures. He fell into prostration and thanked Allah. His story teaches us to make dua humbly, privately and with certainty that Allah hears.",
      `Description of Zakariyah — The years had taken their toll on the Prophet Zakariyah (pbuh). He was now old and bent with age, in his nineties. Despite his feebleness, he went to the temple daily to deliver his sermons. Zakariyah was not a rich man, but he was always ready to help those in need.`,
      `His one disappointment in life was that he had no children, for his wife was barren. This worried him, for he feared there was no one after him to carry out his work.`,
      `The people needed a strong leader, for it they were left on their own, they would move away from Allah's teachings and change the Holy Laws to suit themselves.`,
      `Zakariyah Talks to Mary — During one of his visits to the temple, he went to check on Mary, who was living in a secluded room of the temple. He was surprised to find fresh out of season fruit in her room. Besides him, no one had entry to her room.`,
      `When he inquired, she told him that the fruit was from Allah. She found it every morning. But why was he so surprised, she asked him. Did he not know that Allah provides without measure for whom He wills? This noble girl had opened this eyes to a startling idea.`,
      `Could he not ask his Lord to bless him with a child in his old age? Even if his wife was past childbearing age, nothing was impossible for his Gracious Lord!`,
      `Zakariyah Asks for a Son - Quranic — Allah the Almighty revealed: — 'Kaf, Ha, Ya, Ain, Sad, (These letters are one of the miracles of the Quran, and none but Allah Alone knows their meanings). This is a mention of the Mercy of your Lord to His slave Zakariyah.`,
      `When he called out his Lord (Allah) - a call in secret, saying: "My Lord! Indeed my bones have grown feeble, and gray hair has spread on my head, and I have never been unblest in my invocation to You, O my Lord! And Verily! I fear my relatives after me, since my wife is barren.`,
      `So give me from Yourself an heir, - who shall inherit me, and inherit also the posterity of Jacob (inheritance of the religious knowledge and Prophethood, not the wealth, etc.) And make him, my Lord, one with whom You are Well-pleased!" Allah said: "O Zakariyah! Verily, We give you the glad tidings of a son.`,
      `His name will be Yahya (John). We have given that name to none before him." He said: "My Lord! How can I have a son, when my wife is barren, and I have reached the extreme old age." He said: "So (it will be). Your Lord says, It is easy for Me.`,
      `Certainly I have created you before, when you had been nothing." Zakariyah said: "My Lord! Appoint for me a sign." He said: "Your sign is that you shall not speak unto mankind for three nights, though having no bodily defect." Then he came out to his people from Al Mihrab (a praying place or a private room, etc.), he told them by signs to glorify Allah's Praises in the morning and in the afternoon.`,
      `It was said to his son: "O John! Hold fast to the Scripture (The Torah)." And We gave him wisdom while yet a child, and made him sympathetic to men as a mercy or a grant from Us, and pure from sins (John) and he was righteous, and dutiful towards his parents, and he was neither an arrogant nor disobedient (to Allah or to his parents).`,
      `And Salamun (peace) on him the day he was born, the day he dies, and the day he will be raised up to life again! (Ch 19:1-15 Quran)`,
      `Almighty Allah also said: — "At that time Zakariyah invoked his Lord, saying: "O my Lord! Grant me from You, a good offspring.`,
      `You are indeed the All-Hearer of invocation." Then the angels called him, while he was standing in prayer in Al- Mihrab ( a praying place or a private room), saying: "Allah gives you glad tidings of John confirming (believing in) the Word from Allah ("Be!" - and he was! (i.e.`,
      `the creation of Isa (Jesus), son of Mariam (Mary), noble keeping away from sexual relations with women, a Prophet, from among the righteous." He said: "O my Lord! How can I have a son when I am very old, and my wife is barren?" Allah said: "Thus Allah does what He wills." He said: "O my Lord! Make a sign for me." Allah said: "Your sign is that you shall not speak to mankind for three days except with signals.`,
      `And remember your Lord much (by praising Him again and again), and glorify Him in the afternoon and in the morning." (Ch 3:38-41 Quran).`,
    ],
    lessons: [
      "Dua in private, with humility, is beloved to Allah.",
      "Never think a situation is too late for Allah's help.",
      "Ask Allah for righteous family, not just worldly things.",
    ],
    questions: [
      {
        id: "zakariyya-1",
        question: "Where did Zakariyya serve?",
        options: [
          "In the house of worship among Bani Israil",
          "In a palace",
          "In a market",
          "In an army camp",
        ],
        correctIndex: 0,
      },
      {
        id: "zakariyya-2",
        question: "Whom did he take care of?",
        options: ["Maryam", "Asiya", "Sarah", "Bilqis"],
        correctIndex: 0,
      },
      {
        id: "zakariyya-3",
        question: "What did he notice about her?",
        options: [
          "Allah provided for her in a wonderful way",
          "She could read quickly",
          "She never spoke",
          "She was very wealthy",
        ],
        correctIndex: 0,
      },
      {
        id: "zakariyya-4",
        question: "What did he ask Allah for?",
        options: [
          "A righteous child and heir",
          "Great wealth",
          "A kingdom",
          "A long life only",
        ],
        correctIndex: 0,
      },
      {
        id: "zakariyya-5",
        question: "How did he make his dua?",
        options: [
          "Quietly and secretly",
          "In a loud gathering",
          "In writing",
          "Through a messenger",
        ],
        correctIndex: 0,
      },
      {
        id: "zakariyya-6",
        question: "Why did it seem impossible?",
        options: [
          "He was very old and his wife could not have children",
          "He had no home",
          "He was travelling",
          "He was ill",
        ],
        correctIndex: 0,
      },
      {
        id: "zakariyya-7",
        question: "Which son was he given?",
        options: ["Yahya", "Isa", "Ishaq", "Ismail"],
        correctIndex: 0,
      },
      {
        id: "zakariyya-8",
        question: "What sign was given to him?",
        options: [
          "He could not speak to people for three days except by gestures",
          "A star appeared",
          "Rain fell for three days",
          "His staff turned green",
        ],
        correctIndex: 0,
      },
      {
        id: "zakariyya-9",
        question: "How did he react to the good news?",
        options: [
          "He prostrated and thanked Allah",
          "He doubted it",
          "He kept it secret forever",
          "He asked for another sign",
        ],
        correctIndex: 0,
      },
      {
        id: "zakariyya-10",
        question: "What do we learn about dua from him?",
        options: [
          "To ask humbly, privately and with certainty",
          "To ask only for money",
          "To ask once and stop",
          "That dua has limits",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "yahya",
    name: "Yahya",
    arabicName: "يَحْيَى",
    title: "The pure prophet given wisdom as a child",
    emoji: "🕯️",
    accent: "from-lime-400 to-emerald-500",
    summary:
      "Yahya was given his unique name by Allah, was wise from childhood, and was kind to his parents.",
    story: [
      "Yahya (peace be upon him) was the answer to his father Zakariyya's dua. Allah Himself chose his name, a name no one had been given before him. From the Qur'an we learn that Allah gave him wisdom while he was still a boy, and made him pure, gentle and God-fearing.",
      "Yahya was dutiful to his parents and never arrogant or disobedient. He held on to the Book of Allah with strength, spoke the truth openly, and lived simply, away from the love of luxury. He confirmed the message of Isa and told people to prepare for it.",
      "He faced a cruel ruler and did not soften the truth to please him, and he was eventually killed for standing firm. Allah sent peace upon him on the day he was born, the day he dies and the day he will be raised. His life shows that youth is no barrier to greatness, and that truth is worth more than the approval of the powerful.",
      `John's Childhood — John (pbuh) was born a stranger to the world of children who used to amuse themselves, as he was serious all the time. Most children took delight in torturing animals whereas, he was merciful to them.`,
      `He fed the animals from his food until there was nothing left for him, and he just ate fruit or leaves of trees. John loved reading since childhood. When he grew up, Allah the Exalted called upon him:`,
      `"O John! Hold fast to the Scripture (The Torah)." And We gave him wisdom while yet a child. (Ch 19:12 Quran).`,
      `John's Qualities — Allah guided him to read the Book of Jurisprudence closely; thus, he became the wisest and most knowledgeable man of that time.`,
      `Therefore, Allah the Almighty endowed him with the faculties of passing judgments on people's affairs, interpreting the secrets of religion, guiding people to the right path, and warning them against the wrong one. John reached maturity.`,
      `His compassion for his parents, as well as for all people and all creatures, increased greatly. He called people to repent their sins. There are quite a number of traditions told about John. Ibn Asaker related that one time his parents were looking for him and found him at the Jordan River.`,
      `When they met him, they wept sorely, seeing his great devotion to Allah, Great and Majestic. Ibn Wahb said that, according to Malik, grass was the food of John Ibn Zakariyah, and he wept sorely in fear of Allah.`,
      `A chain of narrators reported that Idris Al Khawlawi said: "Shall I not tell you he who had the best food? It is John Ibn Zakariyah, who joined the beasts at dinner, fearing to mix with men."`,
      `Why John Always Wept — Ibn Mubarak stated that Wahb Ibn Al-Ward narrated that Zakariayah did not see his son for three days. He found him weeping inside a grave which he had dug and in which he resided.`,
      `"My son, I have been searching for you, and you are dwelling in this grave weeping!" "O father, did you not tell me that between Paradise and Hell is only a span, and it will not be crossed except by tears of weepers?" He said to him: "Weep then, my son." Then they wept together.`,
      `Other narrations say that John (pbuh) said: "The dwellers of Paradise are sleepless out of the sweetness of Allah's bounty; that is why the faithful must be sleepless because of Allah's love in their hearts.`,
      `How far between the two luxuries, how far between them?" They say John wept so much that tears marked his cheeks.`,
      `John's Love of Nature — He found comfort in the open and never cared about food. He ate leaves, herbs, and sometimes locusts. He slept anywhere in the mountains or in holes in the ground.`,
      `He sometimes would find a lion or a bear as he entered a cave, but being deeply absorbed in praising Allah, he never heeded them. The beasts easily recognized John as the prophet who cared for all the creatures, so they would leave the cave, bowing their heads.`,
      `John sometimes fed those beasts, out of mercy, from his food and was satisfied with prayers as food for his soul. He would spend the night crying and praising Allah for His blessings.`,
      `When John called people to worship Allah, he made them cry out of love and submission, arresting their hearts with the truthfulness of his words. A conflict took place between John and the authorities at that time.`,
      `A tyrant king, Herod Antipas, the ruler of Palestine, was in love with Salome, his brother's daughter. He was planning to marry his beautiful niece. The marriage was encouraged by her mother and by some of the learned men of Zion, either out of fear or to gain favor with the ruler.`,
      `On hearing the ruler's plan, John pronounced that such a marriage would be incestuous. He would not approve it under any circumstance, as it was against the Law of the Torah.`,
      `John's Cruel Death — John's pronouncement spread like wildfire. Salome was angry, for it was her ambition to rule the kingdom with her uncle. She plotted to achieve her aim. Dressing attractively, she sang and danced before her uncle. Her arousing Herod's lust.`,
      `Embracing her, he offered to fulfill whatever she desired. At once she told him: "I would love to have the head of John, because he has defiled your honor and mine throughout the land.`,
      `If you grant me this wish, I shall be very happy and will offer myself to you." Bewitched by her charm, he submitted to her monstrous request. John was executed and his head was brought to Salome. The cruel woman gloated with delight. But the death of Allah's beloved prophet was avenged.`,
      `Not only she, but all the children of Israel were severely punished by invading armies which destroyed their kingdom.`,
    ],
    lessons: [
      "Wisdom and worship can begin in childhood.",
      "Being good to parents is part of being close to Allah.",
      "Never change the truth to please powerful people.",
    ],
    questions: [
      {
        id: "yahya-1",
        question: "Whose dua was Yahya the answer to?",
        options: ["Zakariyya's", "Ibrahim's", "Musa's", "Dawud's"],
        correctIndex: 0,
      },
      {
        id: "yahya-2",
        question: "What was special about his name?",
        options: [
          "Allah chose it and no one had it before him",
          "It was his father's name",
          "It meant king",
          "It was chosen by his people",
        ],
        correctIndex: 0,
      },
      {
        id: "yahya-3",
        question: "When was he given wisdom?",
        options: ["While he was still a boy", "After he turned forty", "In old age", "Only at the end of his life"],
        correctIndex: 0,
      },
      {
        id: "yahya-4",
        question: "How was he with his parents?",
        options: [
          "Dutiful and kind",
          "Distant",
          "Disobedient",
          "Always arguing",
        ],
        correctIndex: 0,
      },
      {
        id: "yahya-5",
        question: "How did he treat the Book of Allah?",
        options: [
          "He held on to it with strength",
          "He read it rarely",
          "He hid it",
          "He copied it only",
        ],
        correctIndex: 0,
      },
      {
        id: "yahya-6",
        question: "Whose message did he confirm?",
        options: ["Isa's", "Musa's alone", "Dawud's", "Yunus'"],
        correctIndex: 0,
      },
      {
        id: "yahya-7",
        question: "How did he live?",
        options: [
          "Simply, away from luxury",
          "In a palace",
          "As a wealthy trader",
          "As a soldier",
        ],
        correctIndex: 0,
      },
      {
        id: "yahya-8",
        question: "How did he deal with a cruel ruler?",
        options: [
          "He spoke the truth and did not soften it",
          "He stayed silent",
          "He praised him",
          "He ran away",
        ],
        correctIndex: 0,
      },
      {
        id: "yahya-9",
        question: "On which days did Allah send peace upon him?",
        options: [
          "The day he was born, the day he dies and the day he is raised",
          "Only the day he was born",
          "Fridays",
          "The day of his marriage",
        ],
        correctIndex: 0,
      },
      {
        id: "yahya-10",
        question: "What does his life teach young people?",
        options: [
          "Youth is no barrier to greatness in faith",
          "Wisdom comes only with age",
          "It is better to stay quiet",
          "Simplicity is a weakness",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "isa",
    name: "Isa",
    arabicName: "عِيسَى",
    title: "The Messiah who spoke in the cradle",
    emoji: "🌤️",
    accent: "from-sky-400 to-blue-500",
    summary:
      "Isa was born miraculously to Maryam, spoke as a baby, healed by Allah's permission, and was raised up.",
    story: [
      "Isa (peace be upon him) was born to Maryam, a pure and worshipping woman, without a father — by the command of Allah, who says 'Be' and it is. When people accused Maryam, the baby Isa spoke in the cradle and declared that he was a servant of Allah who had been given the Scripture and made a prophet.",
      "Allah gave Isa the Injil and great miracles by His permission: he healed the blind and the lepers, brought the dead back to life, and made a bird from clay that flew. He also told his people about hidden things. With every miracle he made it clear that the power came from Allah and that he was calling people to worship Allah alone, confirming the Tawrah and bringing good news of a final messenger.",
      "The leaders plotted to kill him, but Allah tells us that they did not kill or crucify him; it only appeared so to them, and Allah raised Isa to Himself. Muslims believe he will return before the Day of Judgement. His story teaches that Allah's power has no limits, and that a miracle is a sign pointing to Allah, never a reason to worship the messenger.",
      `Allah Declares He Has No Son — In many verses of the Glorious Qur'an Allah the Exalted denied the claim of the Christians that He has a son.`,
      `A delegation from Nagran came to the Prophet Muhammad (pbuh). They began to talk about their claim about the Trinity, which is that Allah is three in one, the Father, the Son, and the Holy Spirit, with some disagreement among their sects.`,
      `That is why Allah affirmed in many verses of the Qur'an that Jesus is a slave of Allah, whom He molded in the womb of his mother like any other of His creatures, and that He created him without a father, as He created Adam without a father or a mother.`,
      `Almighty Allah had chosen Isa to be one of his messengers to humanity.`,
      `The Birth of Mary - Quranic — Allah the Almighty said: — "Allah chose Adam, Noah, the family of Abraham and the family of Imran above the Alamin (mankind and jinns)(of their times). Offspring, one of theo other, and Allah is All-Hearer, All-Knower.`,
      `Remember when the wife of Imran said: "O my Lord! I have vowed to You what (the child that) is in my womb to be dedicated for Your services (free from all worldly work; to serve Your Place of worship), so accept this, from me.`,
      `Verily, You are the All-Hearer, the All Knowing." Then when she delivered her (child Mary), she said: "O my Lord! I have delivered a female child," and Allah knew better what she delivered, - "and the male is not like the female, and I have named her Mary, and I seek refuge with You (Allah) for her and for her offspring from Satan, the outcast."`,
      `Mary's Sustenance - Quranic — So her Lord (Allah) accepted her with goodly acceptance. He made her grow in a good manner and put her under the care of Zechariah. Every time he entered Al-Mihrab (a praying place or a private room), he found her supplied with sustenance.`,
      `As Allah recounted in the Glorious Quran:`,
      `She said: "From Allah. Verily, Allah provides sustenance to whom He wills, without limit." (Ch 3:37 Quran)`,
      `Mary's Family History Allah declared that He had elected Adam (pbuh) and the elite of his offspring who obey Allah. Then He specified the family of Abraham (pbuh), which includes the sons of Ishmael (pbuh), and the family of Imran, the father of Mary.`,
      `Muhammad Ibn Ishaaq stated that he was Imran Ibn Bashim, Ibn Amun, Ibn Misha, Ibn Hosqia, Ibn Ahriq, Ibn Mutham, Ibn Azazia, Ibn Amisa, Ibn Yamish, Ibn Ahrihu, Ibn Yazem, Ibn Yahfashat, Ibn Eisha, Ibn Iyam, Ibn Rahba am, Ibn David (Dawud).`,
      `Mary's Birth - Longer Version — Prophet Zakariyah's (pbuh) wife's sister had a daughter named Hannah. She was married to Imran, a leader of the Israelites. For many years, the couple remained childless. Whenever Hannah saw another woman with a child, her longing for a baby increased.`,
      `Although years had passed, she never lost hope. She believed that one day Allah would bless her with a child, on whom she would shower all her motherly love.`,
      `She turned to the Lord of the heavens and the earth and pleaded with Him for a child. She would offer the child in the service of Allah's house, in the temple of Jerusalem. Allah granted her request.`,
      `When she learned that she was pregnant, she was the happiest woman alive, and thanked Allah for His gift. Her overjoyed husband Imran also thanked Allah for His mercy. However, while she was pregnant her husband passed away. Hannah wept bitterly.`,
      `Alas, Imran did not live to see their child for whom they had so longed. She gave birth to a girl, and again turned to Allah in prayer:`,
      `"O my Lord, I have delivered a female child," and the male is not like the female, and I have named her Mary, and I seek refuge with You (Allah) for her and her offspring from Satan, the outcast." (Ch 3:36 Quran)`,
      `Zechariah Becomes Mary's Guardian — Hannah had a big problem in reference to her promise to Allah, for females were not accepted into the temple, and she was very worried.`,
      `Her sister's husband Zakariyah, comforted her, saying that Allah knew best what she had delivered and appreciated fully what she had offered in His service. She wrapped the baby in a shawl and handed it over to the temple elders.`,
      `As the baby was a girl, the question of her guardianship posed a problem for the elders. This was a child of their late and beloved leader, and everyone was eager to take care of her.`,
      `Zakariyah said to the elders: "I am the husband of her maternal aunt and her nearest relation in the temple; therefore, I will be more mindful of her than all of you."`,
      `As it was their custom to draw lots to solve disagreements, they followed this course. Each one was given a reed to throw into the river. They had agreed that whoever's reed remained afloat would be granted guardianship of the girl. All the reeds sank to the bottom except Zakariyah's.`,
      `With this sign, they all surrendered to the will of Allah and made him the guardian.`,
    ],
    lessons: [
      "Miracles come only by Allah's permission and point to Him.",
      "Honour righteous mothers — Maryam is praised in the Qur'an.",
      "Never raise a prophet above his true position as a servant of Allah.",
    ],
    questions: [
      {
        id: "isa-1",
        question: "Who was the mother of Isa?",
        options: ["Maryam", "Asiya", "Sarah", "Hajar"],
        correctIndex: 0,
      },
      {
        id: "isa-2",
        question: "What was miraculous about his birth?",
        options: [
          "He was born without a father by Allah's command",
          "He was born in a palace",
          "He was born speaking Arabic",
          "He was born on a mountain",
        ],
        correctIndex: 0,
      },
      {
        id: "isa-3",
        question: "What did baby Isa do when people accused Maryam?",
        options: [
          "He spoke in the cradle",
          "He cried loudly",
          "He walked",
          "He stayed silent",
        ],
        correctIndex: 0,
      },
      {
        id: "isa-4",
        question: "Which book was given to Isa?",
        options: ["The Injil", "The Tawrah", "The Zabur", "The Qur'an"],
        correctIndex: 0,
      },
      {
        id: "isa-5",
        question: "Which miracle is mentioned about him?",
        options: [
          "Healing the blind and reviving the dead by Allah's permission",
          "Splitting the sea",
          "Controlling the wind",
          "Understanding animals",
        ],
        correctIndex: 0,
      },
      {
        id: "isa-6",
        question: "Where did the power for his miracles come from?",
        options: ["From Allah's permission", "From his own strength", "From the Injil", "From his followers"],
        correctIndex: 0,
      },
      {
        id: "isa-7",
        question: "What did Isa call people to?",
        options: [
          "To worship Allah alone",
          "To worship him",
          "To build temples",
          "To leave their homes",
        ],
        correctIndex: 0,
      },
      {
        id: "isa-8",
        question: "Whose coming did he give good news about?",
        options: [
          "The final messenger, Muhammad (peace be upon him)",
          "A new king",
          "Yahya",
          "Musa",
        ],
        correctIndex: 0,
      },
      {
        id: "isa-9",
        question: "What does the Qur'an say about the plot to kill him?",
        options: [
          "They did not kill or crucify him; Allah raised him to Himself",
          "They succeeded",
          "He escaped to Egypt",
          "He was imprisoned",
        ],
        correctIndex: 0,
      },
      {
        id: "isa-10",
        question: "What do Muslims believe about Isa's return?",
        options: [
          "He will return before the Day of Judgement",
          "He will not return",
          "He returned already",
          "Nothing is said about it",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "muhammad",
    name: "Muhammad",
    arabicName: "مُحَمَّد",
    title: "The final messenger and mercy to the worlds",
    emoji: "🌙",
    accent: "from-emerald-500 to-green-700",
    summary:
      "Muhammad (peace be upon him) received the Qur'an, built a community on mercy and justice, and completed the message.",
    story: [
      "Muhammad (peace be upon him) was born in Makkah, from the descendants of Ismail. He grew up an orphan, was known as Al-Amin — the trustworthy — and never took part in the idol worship or dishonesty around him. At the age of forty, while worshipping alone in the cave of Hira, the angel Jibril brought him the first revelation: 'Read, in the name of your Lord who created.'",
      "For thirteen years in Makkah he called people to worship Allah alone, and he and his companions were mocked, boycotted and harmed. He answered harm with patience and good manners. Then Allah commanded the Hijrah to Madinah, where he built a community: a masjid, a brotherhood between the Muhajirun and Ansar, treaties with neighbours, and laws built on justice for rich and poor alike.",
      "He taught that the strong must protect the weak, that neighbours, orphans, women, workers and even animals have rights, and that character is the heaviest thing on the scale of good deeds. When he returned to Makkah victorious, he forgave the people who had driven him out. The Qur'an, revealed over twenty-three years, was completed with him, and Allah calls him a mercy to all the worlds and the seal of the prophets.",
      `Description of Muhammad — Muhammad (pbuh) was born in Mecca ( Makkah), Arabia, on Monday, 12 Rabi' Al-Awal (2 August A.D. 570). His mother, Aminah, was the daughter of Wahb Ibn Abdu Manaf of the Zahrah family. His father, 'Abdullah, was the son of Abdul Muttalib.`,
      `His genealogy has been traced to the noble house of Ishmael, the son of Prophet Abraham in about the fortieth descend. Muhammad's father died before his birth.`,
      `Before he was six years old his mother died, and the doubly orphaned Muhammad was put under the charge of his grandfather Abdul Muttalib who took the most tender care of him. But the old chief died two years afterwards.`,
      `On his deathbed he confided to his son Abu Talib the charge of the little orphan.`,
      `Journey to Busra - Christian Monk merits Muhammad — When Muhammad was twelve years old, he accompanied his uncle Abu Talib on a mercantile journey to Syria, and they proceeded as far as Busra. The journey lasted for some months. It was at Busra that the Christian monk Bahira met Muhammad.`,
      `He is related to have said to Abu Talib: 'Return with this boy and guard him against the hatred of the Jews, for a great career awaits your nephew."`,
      `Muhammad's honest and honorable character — After this journey, the youth of Muhammad seems to have been passed uneventfully, but all authorities agree in ascribing to him such correctness of manners and purity of morals as were rare among the people of Mecca.`,
      `The fair character and the honorable bearing of the unobtrusive youth won the approbation of the citizens of Mecca, and b y common consent he received the title of "Al Ameen," The Faithful. In his early years, Muhammad was not free from the cares of life.`,
      `He had to watch the flocks of his uncle, who, like the rest of the Bani Hashim, had lost the greater part of his wealth.`,
      `Solitary lifestyle of Muhammad's youth — From youth to manhood he led an almost solitary life.`,
      `The lawlessness rife among the Meccans, the sudden outbursts of causeless and bloody quarrels among the tribes frequenting the Fair of Okadh (The Arabian Olympia), and the immorality and skepticism of the Quraish, naturally caused feelings of pity and sorrow in the heart of the sensitive youth.`,
      `Such scenes of social misery and religious degradation were characteristic of a depraved age.`,
      `Muhammad's marriage to Khadijah — When Muhammad was twenty five years old, he traveled once more to Syria as a factor of a noble and rich Quraishi widow named Khadijah; and, having proved himself faithful in the commercial interests of that lady, he was soon rewarded with her hand in marriage.`,
      `This marriage proved fortunate and singularly happy. Khadijah was much the senior of her husband, but in spite of the disparity of age between them, the most tender devotion on both sides existed.`,
      `This marriage gave him the loving heart of a woman who was ever ready to console him in his despair and to keep alive within him the feeble, flickering flame of hope when no man believed in him and the world appeared gloomy in his eyes.`,
      `Troubled, lawless times for the Makkans — Until he reached thirty years of age, Muhammad was almost a stranger to the outside world. Since the death of his grandfather, authority in Mecca was divided among the ten senators who constituted the governing body of the Arabian Commonwealth.`,
      `There was no such accord among them as to ensure the safety of individual rights and property. Though family relations afforded some degree of protection to citizens, yet strangers were frequently exposed to persecution and oppression.`,
      `In many cases they were robbed, not only of their goods, but even of their wives and daughters.`,
      `At the instigation of the faithful Muhammad, an old league called the Federation of Fudul, i.e., favors was revived with the object of repressing lawlessness and defending every weak individual - whether Meccan or stranger, free or slave - against any wrong or oppression to which he might be the victim within the territories of Mecca.`,
      `When Muhammad reached thirty-five years, he settled by his judgment a grave dispute, which threatened to plunge the whole of Arabia into a fresh series of her oft-recurring wars. In rebuilding the Sacred House of the Ka'ba in A.D.`,
      `605, the question arose as to who should have the honor of raising the black stone, the most holy relic of that House, into its proper place. Each tribe claimed that honor. The senior citizen advised the disputants to accept for their arbitrator the first man to enter from a certain gate.`,
      `The proposal was agreed upon, and the first man who entered the gate was Muhammad "Al-Ameen." His advice satisfied all the contending parties. He ordered the stone to be placed on a piece of cloth and each tribe to share the honor of lifting it up by taking hold of a part of the cloth.`,
      `The stone was thus deposited in its place, and the rebuilding of the House was completed without further interruption.`,
      `Muhammad thwarts intention of the Romans to control Makka — It is related that, about this time, a certain Usman, Ibn Huwairith, supported by Byzantine gold, made an attempt to convert the territory of Hijaz into a Roman dependency, but the attempt failed, chiefly through the instrumentality of Muhammad.`,
    ],
    lessons: [
      "Trustworthiness and good character are the heart of Islam.",
      "Answer harm with patience and forgiveness.",
      "Faith builds a community of justice and mercy, not just rituals.",
    ],
    questions: [
      {
        id: "muhammad-1",
        question: "In which city was the Prophet Muhammad born?",
        options: ["Makkah", "Madinah", "Taif", "Jerusalem"],
        correctIndex: 0,
      },
      {
        id: "muhammad-2",
        question: "From whose descendants was he?",
        options: ["Ismail", "Ishaq", "Yaqub", "Harun"],
        correctIndex: 0,
      },
      {
        id: "muhammad-3",
        question: "What was he known as before prophethood?",
        options: ["Al-Amin, the trustworthy", "Al-Malik", "Al-Faris", "Al-Hakim"],
        correctIndex: 0,
      },
      {
        id: "muhammad-4",
        question: "Where did he receive the first revelation?",
        options: ["The cave of Hira", "Mount Uhud", "The Ka'bah", "Madinah"],
        correctIndex: 0,
      },
      {
        id: "muhammad-5",
        question: "Which angel brought the revelation?",
        options: ["Jibril", "Mikail", "Israfil", "Malik"],
        correctIndex: 0,
      },
      {
        id: "muhammad-6",
        question: "What were the first revealed words?",
        options: [
          "Read, in the name of your Lord who created",
          "Praise be to Allah",
          "Say: He is Allah, the One",
          "By the pen and what they write",
        ],
        correctIndex: 0,
      },
      {
        id: "muhammad-7",
        question: "What is the migration to Madinah called?",
        options: ["The Hijrah", "The Isra", "The Fath", "The Bay'ah"],
        correctIndex: 0,
      },
      {
        id: "muhammad-8",
        question: "What did he do when he returned to Makkah victorious?",
        options: [
          "He forgave the people who had harmed him",
          "He punished everyone",
          "He left the city",
          "He destroyed the houses",
        ],
        correctIndex: 0,
      },
      {
        id: "muhammad-9",
        question: "Over how many years was the Qur'an revealed to him?",
        options: ["About twenty-three years", "Ten years", "Forty years", "Five years"],
        correctIndex: 0,
      },
      {
        id: "muhammad-10",
        question: "How does the Qur'an describe him?",
        options: [
          "A mercy to all the worlds and the seal of the prophets",
          "A king of Arabia",
          "One of many messengers still to come",
          "A poet",
        ],
        correctIndex: 0,
      },
    ],
  },
];
