import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_3: BuiltInLesson[] = [
  {
    id: "yusuf",
    name: "Yusuf",
    arabicName: "يُوسُف",
    title: "From the well to the treasury of Egypt",
    emoji: "👑",
    accent: "from-yellow-400 to-amber-500",
    summary:
      "Yusuf was thrown into a well, sold as a slave, jailed unjustly, then made a minister who forgave his brothers.",
    story: [
      "Yusuf (peace be upon him) was the beloved son of Yaqub. As a boy he dreamt of eleven stars, the sun and the moon prostrating to him. His brothers became jealous, threw him into a well, and told their father that a wolf had eaten him. A passing caravan found Yusuf and sold him in Egypt, where he grew up in the house of a powerful man.",
      "Allah gave Yusuf beauty, wisdom and the ability to explain dreams. When he was tempted to sin, he refused and chose prison over disobeying Allah. He spent years in jail although he was innocent, and he used that time to call his fellow prisoners to worship Allah alone. Then the king had a strange dream about seven fat cows eaten by seven thin ones, and seven green ears of corn and seven dry ones. Yusuf explained it: seven years of plenty would be followed by seven years of drought, so grain must be stored carefully.",
      "The king was so impressed that he freed Yusuf and put him in charge of the treasury of Egypt. During the famine his brothers came to buy food and did not recognise him. When he finally revealed himself, he did not take revenge; he said there was no blame on them and asked Allah to forgive them. He was reunited with his father, and his childhood dream came true.",
      `Introduction to Joseph's Story — This is the most detailed and fascinating story in the Quran, involving both human weaknesses such as jealousy, hatred, pride, passion, deception, intrigue, cruelty, and terror as well as noble qualities such as patience, loyalty, bravery, nobility, and compassion.`,
      `It is related that among the reasons for its revelation is that the Jews asked the Prophet Muhammad (pbuh) to tell them about Joseph (pbuh) who was one of their old prophets. His story had been distorted in parts and marred in others with interpolation and exclusions.`,
      `Therefore it was revealed in the Book of Allah (Quran), complete in its minute and careful details.`,
      `Allah the Almighty declared: — "We relate unto you (Muhammad) the best of stories through Our Revelations unto you, of this Quran. And before this (i.e. before the coming of Divine Inspiration to you), you were among those who knew nothing about it (the Quran). ( Ch 12:3 Quran)`,
      `Almighty Allah also decreed: — "Thus We relate to you (O Muhammad) some information of what happened before, And indeed We have give you from Us a Reminder (this Quran). Whoever turns away from it (this Quran--i.e.`,
      `does not believe in it, nor acts on its orders), verily they will bear a heavy burden (of sins) on the Day of Resurrection. They will abide in that (state in the Fire of Hell), and evil indeed will it be that load for them on the Day of Resurrection.(Ch 20:99-101)`,
      `The story of Joseph (pbuh) moves in a stream from beginning to end; its substance and form are equally coherent. It inspires you with a feeling for the depth of Allah's power and supremacy and the execution of His rulings despite the challenge of human intervention.`,
      `"And Allah has full power and control over His Affairs, but most of men know not. (Ch 12:21) This is what the story of Joseph (pbuh), confirms categorically, for it ends with comfort and marvels.`,
      `Summary of Joseph's Story — Joseph lived all his life confronting schemes made by the people closest to him. His brothers plotted to kill him, but they amended it to exiling him. This happened to him while he was a boy.`,
      `He was sold into the slave market in Egypt, where he was bought for a nominal sum. Then he fell victim to the attempted seduction by a great man's wife who, when her wish was foiled, sent him to prison, where he remained for some time.`,
      `In spite of all of this, he at length approached close to the Egyptian throne and became the king's chief minister. He then began his call to Allah from the position of the ruling authority.`,
      `Allah's plans were carried out, and the matter ended. This is the substance (theme) of the story. As for the form (style) in which it is presented, it is a landmark of wonder.`,
      `The Story's Presentation — The story is presented in a sequence of episodes. It gives you scene after scene and the transition is inspiring, informative, and stirring to the imagination.`,
      `There are also artistic loopholes, which leave it to the imagination of the reader to complete the sense, as well as the depth of the picture, the like of which no human artist can bring forth.`,
      `Joseph's Childhood — The story begins with a dream and ends with its interpretation. As the sun appeared over the horizon, bathing the earth in its morning glory, Joseph (pbuh), son of the Prophet Jacob (pbuh) awoke from his sleep, delighted by a pleasant dream he had had.`,
      `Filled with excitement he ran to his father and related it.`,
      `"O my father! Verily, I saw (in a dream) eleven stars and the sun and the moon, I saw them prostrating themselves to me." (Ch 12:4)`,
      `His father's face lit up. He foresaw that Joseph would be one through whom the prophecy of his grandfather, Prophet Abraham (pbuh), would be fulfilled, in that his offspring would keep the light of Abraham's house alive and spread Allah's message to mankind.`,
      `Therefore, it was narrated that Allah's Messenger Muhammad (pbuh) was asked: "Who is the most honorable amongst the people?" He replied: "The most God-fearing." The people said: "We do not want to ask you about this." He said: "The most honorable person is Joseph Allah's prophet, the son of Allah's prophet, the son of the faithful friend of Allah (Abraham)." (Sahih Al-Bukhari) However, the father was well aware of the jealousy of Joseph's brothers, so he warned him against telling his dream to his brothers.`,
      `"O my son! Relate not your vision to your brothers, lest they arrange a plot against you.`,
      `Verily! Satan is to man an open enemy! Thus will your Lord choose you and teach you the interpretation of dreams (an other things) and perfect His Favor on you and on the offspring of Jacob, as He perfected it on your fathers, Abraham, and Isaac aforetime! Verily! your Lord is All-Knowing, All-Wise." (Ch 12:5-6)`,
      `Joseph heeded his father's warning. He did not tell his brothers what he had seen. It is well known that they hated him so much that it was difficult for him to feel secure telling them what was in his heart and in his dreams.`,
      `Description of Joseph — Joseph was eighteen years old, very handsome and robust, with a gentle temperament. He was respectful, kind and considerate. His brother Benjamin was equally pleasant. Both were from one mother, Rachel.`,
      `Because of their refined qualities, the father loved the two more than his other children, and would not let them out of his sight. To protect them, he kept them busy with work in the house garden.`,
    ],
    lessons: [
      "Choose obedience to Allah even when sin is easy and hidden.",
      "Patience and skill turn hardship into leadership.",
      "Forgiveness is stronger than revenge.",
    ],
    questions: [
      {
        id: "yusuf-1",
        question: "What did Yusuf see in his childhood dream?",
        options: [
          "Eleven stars, the sun and the moon prostrating",
          "Seven thin cows",
          "A caravan in the desert",
          "A river of milk",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-2",
        question: "What did his brothers do to him?",
        options: [
          "Threw him into a well",
          "Sent him to school",
          "Took him to Makkah",
          "Left him in a garden",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-3",
        question: "What did they tell Yaqub?",
        options: [
          "That a wolf had eaten him",
          "That he had run away",
          "That he was in prison",
          "That he had drowned",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-4",
        question: "Where was Yusuf taken and sold?",
        options: ["Egypt", "Madyan", "Yemen", "Shaam"],
        correctIndex: 0,
      },
      {
        id: "yusuf-5",
        question: "What special knowledge did Allah give him?",
        options: [
          "Explaining dreams",
          "Healing the sick",
          "Speaking to animals",
          "Controlling the wind",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-6",
        question: "What did Yusuf choose when he was tempted to sin?",
        options: [
          "Prison rather than disobeying Allah",
          "To run away from Egypt",
          "To keep silent",
          "To ask the king for help",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-7",
        question: "What did he do while in prison?",
        options: [
          "Called the prisoners to worship Allah alone",
          "Refused to speak",
          "Planned revenge",
          "Wrote letters to the king",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-8",
        question: "What did the king's dream mean?",
        options: [
          "Seven years of plenty then seven years of drought",
          "A war was coming",
          "The Nile would dry up forever",
          "The king would travel",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-9",
        question: "What position was Yusuf given?",
        options: [
          "In charge of the treasury and food stores of Egypt",
          "Chief of the army",
          "A judge in prison",
          "A teacher of children",
        ],
        correctIndex: 0,
      },
      {
        id: "yusuf-10",
        question: "How did Yusuf treat his brothers at the end?",
        options: [
          "He forgave them and asked Allah to forgive them",
          "He punished them",
          "He sent them away",
          "He put them in prison",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ayyub",
    name: "Ayyub",
    arabicName: "أَيُّوب",
    title: "The prophet of patience through illness and loss",
    emoji: "🌾",
    accent: "from-emerald-400 to-green-600",
    summary:
      "Ayyub lost his wealth, children and health, yet never stopped praising Allah — and was restored.",
    story: [
      "Ayyub (peace be upon him) was a prophet who had been given great blessings: wealth, land, a large family and good health. He was grateful, generous to the poor, and constant in worship. Then Allah tested him: his wealth was lost, his children died, and his body was struck by a long illness so that people avoided him.",
      "Through all of it, Ayyub never complained against his Lord. He remembered that the same Allah who gave the blessings had the right to take them back. His wife stayed loyal and cared for him, and he continued to remember Allah with a thankful heart for many years.",
      "At last he made a gentle dua: 'Indeed, hardship has struck me, and You are the Most Merciful of the merciful.' Allah answered him. He was told to strike the ground with his foot, and a spring appeared from which he washed and drank, and his health returned. Allah restored his family and wealth, and praised him in the Qur'an as an excellent servant who always turned back to Him.",
      `Job's Family History — Ibn Ishaaq stated that he was a man of Rum. His name was Job, Ibn Mose, Ibn Razeh, Ibn Esau, Ibn Isaac (pbuh), Ibn Abraham (pbuh). Someone else said he was Job, Ibn Mose, Ibn Rimil, Ibn Esau, Ibn Isaac, Ibn Jacob. There have also been other statements on his lineage.`,
      `Ibn Asaker narrated that his mother was a daughter of Lot (pbuh). It was said, also that his father was one who believed in Abraham (pbuh) when he was cast into the fire. The first opinion is the most plausible, because he was a descendant of Abraham's offspring as`,
      `Allah Almighty declared: — "That was Our proof which We gave Abraham against his people. We raise whom We will in degrees. Certainly your Lord is All-Wise, All Knowing.`,
      `And We bestowed upon him Isaac and Jacob, each of them We guided and before him, We guided Noah, and among his progeny David, Solomon, Job, Joseph, Moses, and Aaron. Thus do We reward the good doers. (Ch 6:83-84)`,
      `Allah's Praises of Job — Allah the Almighty praised His worshipper Job in His Glorious Quran:`,
      `"Truly! We found him patient. How excellent a slave! Verily, he was ever oft returning in repentance to Us!" (Ch 38:44)`,
      `Job (pbuh) was repentant, remembering Allah with thankfulness, patience, and steadfastness. This was the cause of his rescue and the secret of Allah's praising him.`,
      `A group of angels were discussing Allah's other human creatures, how those who were humble earned Allah's pleasure, while those who were arrogant incurred His displeasure.`,
      `One of the angels remarked: "The best creature on earth today is Job, a man of noble character who displays great patience and always remembers his Generous Lord. He is an excellent model for the worshippers of Allah.`,
      `In return, his Lord has blessed him with a long life and plenty of servants, as well as the needy and the poor share in his good fortune; he feeds and clothes the poor and buys slaves to set them free. He makes those who receive his charity feel as if they are favoring him so kind and gentle is he."`,
      `Iblis' Jealousy of Job — Iblis overhearing all of this, became annoyed. He planned to tempt Job to corruption and disbelief, so he hastened to him.`,
      `He tried to distract Job from his prayers by whispering him about the good things in life but Job was a true believer and would not let evil thoughts tempt him. This disturbed Iblis even more; thus he began to hate Job even more.`,
      `Iblis Destroys Job's Wealth — Iblis complained to Allah about Job. He said that although he was continuously glorifying Allah he was not doing so out of his sincerity but to satisfy Allah so that his wealth should not be taken away. It was all a show, all out of greed.`,
      `"If You remove his wealth then You will find that his tongue will no longer mention Your name and his praying will stop." Allah told Iblis that Job was one of His most sincere devotees.`,
      `He did not worship Him because of the favors; his worship stemmed from his heart and had nothing to do with material things. But to prove to Iblis the depth of Job's sincerity and patience, Allah allowed him to do whatever he and his helpers wished with Job's wealth. Iblis was very happy.`,
      `he gathered his helpers and set about destroying Job's cattle, servants and farms until he was left with no possessions.`,
      `Rubbing his hands in glee, Iblis appeared before Job in the guise of a wise old man and said to him: "All your wealth is lost, some people say that it is because you gave too much charity and that you are wasting your time with your continuous prayers to Allah.`,
      `Others say that Allah has brought this upon you in order to please your enemies. If Allah had the capacity to prevent harm, then He would have protected your wealth." True to his belief, Job replied: "What Allah has taken away from me belongs to Him. I was only its trustee for awhile.`,
      `He gives to whom He wills and withholds from whom He wills." With these words, Job again prostrated to his Lord.`,
      `Iblis Destroys Job's Children — When Iblis saw this, he felt frustrated, so he again addressed Allah: "I have stripped Job of all his possessions, but he still remains grateful to You. However he is only hiding his disappointment, for he places great store by his many children.`,
      `The real test of a parent is through his children. You will see how Job will reject You." Allah granted Iblis authority but warned him that it would not reduce Job' faith in His Lord nor his patience. Iblis again gathered his helpers and set about his evil deeds.`,
      `He shook the fountain of the house in which Job's children were living and sent the building crashing, killing all of them. Then he went to Job disguised as a man who had come to sympathize with him. In a comforting tone he said to Job: "The circumstances under which your children died were sad.`,
      `Surely, your Lord is not rewarding you properly for all your prayers." Having said this, Iblis waited anxiously hoping Job was now ready to reject Allah. But again Job disappointed him by replying: "Allah sometimes gives and sometimes takes.`,
      `He is sometimes pleased and sometimes displeased with our deeds. Whether a thing is beneficial or harmful to me, I will remain firm in my belief and remain thankful to my Creator." then Job prostrated to his Lord. At this Iblis was extremely vexed.`,
    ],
    lessons: [
      "Gratitude in good times prepares the heart for hard times.",
      "Complaining is different from making dua — dua is worship.",
      "Allah's relief comes after true patience.",
    ],
    questions: [
      {
        id: "ayyub-1",
        question: "What blessings did Ayyub have at first?",
        options: [
          "Wealth, family and good health",
          "A kingdom and army",
          "Only knowledge",
          "Only land",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-2",
        question: "What was taken from him in his test?",
        options: [
          "His wealth, his children and his health",
          "Only his money",
          "Only his health",
          "His home only",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-3",
        question: "How did Ayyub behave during the test?",
        options: [
          "He stayed patient and kept praising Allah",
          "He complained loudly",
          "He stopped praying",
          "He blamed his family",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-4",
        question: "Who stayed loyal and cared for him?",
        options: ["His wife", "His neighbours", "The king", "His servants"],
        correctIndex: 0,
      },
      {
        id: "ayyub-5",
        question: "What did his dua include?",
        options: [
          "That Allah is the Most Merciful of the merciful",
          "A demand for his wealth back",
          "A complaint about people",
          "A request for a kingdom",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-6",
        question: "What was he told to do to find a cure?",
        options: [
          "Strike the ground with his foot",
          "Travel to Egypt",
          "Fast for a month",
          "Climb a mountain",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-7",
        question: "What appeared from the ground?",
        options: ["A spring of water", "A tree", "Gold", "A camel"],
        correctIndex: 0,
      },
      {
        id: "ayyub-8",
        question: "What did Allah restore to him?",
        options: [
          "His health, family and wealth",
          "Only his health",
          "Only his wealth",
          "Nothing in this life",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-9",
        question: "How does the Qur'an describe Ayyub?",
        options: [
          "An excellent servant who always turned back to Allah",
          "A strong warrior",
          "A wealthy king",
          "A skilled builder",
        ],
        correctIndex: 0,
      },
      {
        id: "ayyub-10",
        question: "What is the main lesson of his story?",
        options: [
          "Patience with gratitude brings Allah's relief",
          "Illness is a punishment",
          "Wealth is bad",
          "Duas are not answered",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "shuayb",
    name: "Shu'ayb",
    arabicName: "شُعَيْب",
    title: "The prophet of honest trade in Madyan",
    emoji: "⚖️",
    accent: "from-indigo-400 to-blue-600",
    summary:
      "Shu'ayb called the people of Madyan to worship Allah and to stop cheating in weights and measures.",
    story: [
      "The people of Madyan were traders on a busy route. They worshipped idols, and in their markets they cheated: they gave people less than they paid for, and took more than was due. They also frightened travellers and spread corruption in the land.",
      "Allah sent Shu'ayb (peace be upon him) to them. He was such a clear and gentle speaker that scholars call him the 'orator of the prophets'. He told them two things together: worship Allah alone, and give full measure and weight. He reminded them that whatever remains with Allah is better for them than dishonest profit, and that he did not want to become a policeman over them — he wanted them to fear Allah in their own hearts.",
      "Most of them refused and mocked him, saying his prayer had no power over their business. In the end a terrible punishment struck them: a mighty blast and shaking that left their homes empty. Shu'ayb and the believers were saved. His story teaches that honest work is part of faith; a person cannot pray in the masjid and cheat in the market.",
      `Shuaib's Message — Allah the Almighty revealed the story of Shu'aib (pbuh): — "To the people of Madyan (Madian) (We sent) their brother Shu'aib. He said: "O my people! Worship Allah, you have no other Ilah (God) but Him.`,
      `Verily! a clear proof (sign) from your Lord has come unto you; so give full measure and full weight and wrong not men in their things, and do not mischief on the earth after it has been set in order that will be better for you, if you are believers.`,
      `And sit not on every road, threatening, and hindering from the Path of Allah those who believe in Him, and seeking to make it crooked. Remember when you were but few, and He multiplied you. See what was the end of the Mufsideen (mischief makers, corrupts and liars).`,
      `And if there is a party of you who believes in that which I have been sent and a party who do not believe, so be patient until Allah judges between us, and He is the Best of judges." The chiefs of those who were arrogant among his people said: "We shall certainly drive you out, O Shu'aib! and those who have believed with you from our town, or else you all shall return to our religion." He said: "Even though we hate it! We should have invented a lie against Allah if we returned to your religion, after Allah has rescued us from it.`,
      `It is not for us to return to it unless Allah, our Lord, should will. Our Lord comprehends all things in His Knowledge. In Allah (Alone) we put our trust.`,
      `Our Lord! Judge between us and our people in truth, for You are the Best of those Who gives judgment." The chiefs of those who disbelieved among his people said to their people: "If you follow Shu'aib be sure then you will be the losers!" Then he (shu'aib) turned from them and said: "O my people! I have indeed conveyed my Lord's Messages unto you and I have given you good advice.`,
      `Then how can I sorrow for the disbelieving people's (destruction)." (Ch 7:85-93 Quran)`,
      `The people of Madyan were Arabs who lived in the country of Ma'an, part of which today is greater Syria. They were a greedy people who did not believe that Allah existed and who led wicked lives. They gave short measure, praised their goods beyond their worth, and hid their defects.`,
      `They lied to their customers, thereby cheating them.`,
      `Allah sent His Prophet Shu'aib (pbuh) armed with many miracles. Shu'aib preached to them, begging them to be mindful of Allah's favors and warning them of the consequences of their evil ways, but they only mocked him.`,
      `Shu'aib remained calm as he reminded them of his kinship to them and that what he was doing was not for his personal gain.`,
      `They seized the belongings of Shu'aib and his followers, then drove them out of the city. The Messenger turned to his Lord for help, and his plea was answered. Allah sent down on them scorching heat and they suffered terribly.`,
      `On seeing a cloud gathering in the sky, they thought it would bring cool, refreshing rain, and rushed outside in the hope of enjoying the rainfall. Instead the cloud burst, hurling thunderbolts and fire. They heard a thunderous sound from above which caused the earth under their feet to tremble.`,
      `The evil doers perished in this state of horror.`,
      `The Disbeliever's Ignorance — Allah the Exalted stated: — "The dwellers of Al Aiyka (near Midian, or Madyan) belied the Messengers. When Shu'aib said to them: "Will you not fear Allah and obey Him? I am a trustworthy Messenger to you. SO fear Allah, keep your duty to Him, and obey me.`,
      `No reward do I ask of you for it (my message of Islamic Monotheism), my reward is only from the Lord of the Alamin (mankind, jinn and all that exists). Give full measure, and cause no loss to others. And weigh with the true and straight balance.`,
      `Defraud not people by reducing their things nor do evil making corruption and mischief in the land.`,
      `Fear Him Who created you and the generations of the men of old." They said: "You are only one of those bewitched! You are but a human being like us and verily, we think that you are one of the liars! So cause a piece of heaven to fall on us, if you are of the truthful!" He said: "My Lord is the Best Knower of what you do." But, they belied him, so the torment of the day of shadow (a gloomy cloud) seized them, indeed that was the torment of a Great Day.`,
      `Verily, in this is a sign yet most of them are not believers. And verily! Your Lord, He is indeed the All Mighty, the Most Merciful." (Ch 26:176-191 Quran).`,
    ],
    lessons: [
      "Honesty in business is a direct command from Allah.",
      "Worship and good manners cannot be separated.",
      "Small daily fairness is a great act of faith.",
    ],
    questions: [
      {
        id: "shuayb-1",
        question: "Which people was Shu'ayb sent to?",
        options: ["Madyan", "'Ad", "Thamud", "Egypt"],
        correctIndex: 0,
      },
      {
        id: "shuayb-2",
        question: "What was their main wrongdoing in the market?",
        options: [
          "Cheating in weights and measures",
          "Closing early",
          "Selling only to travellers",
          "Charging no tax",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-3",
        question: "What title do scholars give Shu'ayb?",
        options: [
          "The orator of the prophets",
          "The friend of Allah",
          "The spirit of Allah",
          "The seal of the prophets",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-4",
        question: "What two things did he call them to?",
        options: [
          "Worship Allah alone and trade honestly",
          "Pay more tax and travel less",
          "Build a temple and fast",
          "Move to a new land and farm",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-5",
        question: "What did he say is better than dishonest profit?",
        options: [
          "What remains with Allah",
          "Borrowing money",
          "A bigger shop",
          "More customers",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-6",
        question: "How did most of his people respond?",
        options: [
          "They mocked him and refused",
          "They repented immediately",
          "They asked him to lead the city",
          "They closed their markets",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-7",
        question: "What else were the people of Madyan doing wrong?",
        options: [
          "Frightening travellers and spreading corruption",
          "Building ships",
          "Farming on the road",
          "Teaching their children",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-8",
        question: "What punishment came to them?",
        options: [
          "A mighty blast and shaking",
          "A flood",
          "A wind for eight days",
          "A rain of birds",
        ],
        correctIndex: 0,
      },
      {
        id: "shuayb-9",
        question: "What happened to Shu'ayb and the believers?",
        options: ["They were saved", "They were destroyed", "They were exiled", "They were imprisoned"],
        correctIndex: 0,
      },
      {
        id: "shuayb-10",
        question: "What lesson do we take for our own lives?",
        options: [
          "Being honest in work and money is part of worship",
          "Trade is not allowed",
          "Only prayer matters",
          "Measuring is unnecessary",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "musa",
    name: "Musa",
    arabicName: "مُوسَى",
    title: "The prophet who spoke with Allah",
    emoji: "🌊",
    accent: "from-blue-500 to-indigo-600",
    summary:
      "Musa was saved as a baby, given the staff and the Tawrah, and led Bani Israil through the parted sea.",
    story: [
      "Pharaoh ruled Egypt and claimed to be a god. When he ordered the baby boys of Bani Israil to be killed, the mother of Musa (peace be upon him) placed her baby in a basket on the Nile, trusting Allah. The basket reached Pharaoh's own palace, and his wife Asiya loved the child and raised him. Musa grew up strong, and after defending a man and leaving Egypt, he worked for years in Madyan and married there.",
      "On his way back, at the valley of Tuwa, Allah spoke to him directly from a blessed tree — which is why he is called Kalimullah, the one who spoke with Allah. Allah gave him two great signs: his staff, which became a snake, and his hand, which shone white. Allah also gave him his brother Harun as a helper, and sent them both to Pharaoh with the message: worship Allah alone and free Bani Israil.",
      "Pharaoh refused, gathered his magicians and challenged Musa. When the magicians saw the staff swallow their tricks, they believed in Allah at once. Later Musa led his people out of Egypt. When the sea blocked their path and Pharaoh's army closed in, Allah told Musa to strike the sea with his staff; it parted and they crossed safely, while Pharaoh and his army drowned. Musa received the Tawrah and continued to guide his people with patience.",
      `Description of the Pharaoh — The pharaoh who ruled Egypt was a tyrant who oppressed the descendants of Jacob (pbuh), known as the children of Israel (Bani Israel). He used every means to demean and disgrace them. They were kept in bondage and forced to work for him for small wages or nothing.`,
      `Under this system the people obeyed and worshipped the pharaoh, and the ruling class carried out his orders, thereby authorizing his tyranny and crazy whims. The pharaoh wanted the people to obey him only, and to believe in the gods of his invention.`,
      `Perhaps, during that time, there were many classes of people who did not believe in or practice polytheism; however, they kept this to themselves and outwardly did as they were expected to do, without revolting or revealing themselves to anyone.`,
      `Thus, successive dynasties came to Egypt and assumed that they were gods or their representative or spokesmen.`,
      `Visions of Dethroning the Pharaoh — Years passed, and a despotic king, who was adored by the Egyptians, ruled Egypt. His king saw the children of Israel multiplying and prospering. He heard them talking about a vague vision that one of Israel' s sons would dethrone the pharaoh of Egypt.`,
      `Perhaps this vision was only a daydream that persisted within the hearts of the persecuted minority, or perhaps it was a prophecy from their books. Another tradition states that it was Pharaoh himself who had the vision.`,
      `Ibn 'Abbas narrated: "Pharaoh saw in his vision a fire, which came from Jerusalem and burned the houses of the Egyptians, and all Copts, and did not do harm to the children of Israel. When he woke up, he was horrified. He then gathered his priests and magicians and asked them about this vision.`,
      `They said: "This means a boy will be born of them and the Egyptian people will perish at his hands.' That is why Pharaoh commanded that all male children of the children of Israel be killed." Either way, this vision reached the ears of the Pharaoh.`,
      `He then issued a decree to slay any male child that would be born to the children of Israel.`,
      `The Killing of the Children of Israel — The killing of the children of Israel was carried out until the experts of economics said to Pharaoh: "The aged of the children of Israel die and the young are slaughtered. This will lead to their annihilation.`,
      `As a result, Pharaoh will lose the manpower of those who work for him, those whom he enslaves, and their women whom he exploits.`,
      `It is better to regulate this procedure by initiating the following policy: males should be slaughtered in one year but spared to live the next year." Pharaoh found that solution to be safer economically.`,
      `The Birth of Aaron and Moses (PBUT) — Moses's mother was pregnant with Aaron (pbuh) in a year that boys were spared; thus she gave birth to the child publicly and safely. During a year in which boys were to be slain, she gave birth to Moses (pbuh); thus his birth caused her much terror.`,
      `She was afraid he would be slain, so she nursed him secretly.`,
      `Description of the Pharaoh and Birth of Moses - Quranic — Allah the Almighty revealed:`,
      `"These are Verses of the manifest Book (that makes clear truth from falsehood, good from evil, etc.). We recite to you some of the news of Moses and Pharaoh in truth, for a people who believe (those who believe in this Quran, and in the Oneness of Allah).`,
      `Verily, Pharaoh exalted himself in the land and made its people sects, weakening (oppressing) a group (children of Israel) among them, killing their sons, and letting their females live. Verily, he was of the Mufsideen (those who commit great sins and crimes, oppressors, tyrants, etc.).`,
      `And we wished to do a favor to those who were weak (and oppressed) in the land, and to make them rulers and to make them the inheritors, and to establish them in the land, and We let Pharaoh and Haman and their hosts receive from them that which they feared.`,
      `And We inspired the mother of Moses, saying: "Suckle him (Moses), but when you fear for him, then cast him into the river and fear not, nor grieve. Verily! We shall bring him back to you, and shall make him one of (Our) Messengers." (Ch 28: 2-7 Quran).`,
      `Moses Thrown into the Nile — No sooner had the divine revelation finished that she obeyed the sacred and merciful call. She was commanded to make a basket for Moses. She nursed him, put him into the basket, then went to the shore of the Nile and threw it into the water.`,
      `Her mother's heart, the most merciful one in the world, grieved as she threw her son into the Nile. However, she was aware that Allah was much more merciful to Moses than to her, that He loved him more than her. Allah was his Lord and the Lord of the Nile.`,
      `Hardly had the basket touched the water of the Nile than Allah issued His command to the waves to be calm and gentle while carrying the child would one day be a prophet. She instructed her daughter to follow the course of the basket and to report back to her.`,
      `As the daughter followed the floating basket along the riverbank, she found herself right in the palace grounds and saw what was unfolding before her eyes.`,
      `The basket came to rest at the riverbank, which skirted the king's palace. The palace servants found the basket with the baby and took it to the Pharaoh and his queen. When the queen beheld the lovely infant, Allah instilled in her a strong love for this baby.`,
    ],
    lessons: [
      "Trust in Allah's plan even when it looks frightening.",
      "Truth is stronger than magic and propaganda.",
      "Leaders must be patient with the people they guide.",
    ],
    questions: [
      {
        id: "musa-1",
        question: "Why did Musa's mother place him in the river?",
        options: [
          "Pharaoh ordered baby boys of Bani Israil to be killed",
          "She was travelling",
          "She was poor",
          "The city was flooded",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-2",
        question: "Who raised Musa in the palace?",
        options: [
          "Asiya, Pharaoh's wife",
          "His aunt in Madyan",
          "A priest of Egypt",
          "A merchant family",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-3",
        question: "Where did Musa work after leaving Egypt?",
        options: ["Madyan", "Yemen", "Shaam", "Makkah"],
        correctIndex: 0,
      },
      {
        id: "musa-4",
        question: "Why is Musa called Kalimullah?",
        options: [
          "Allah spoke to him directly",
          "He wrote many books",
          "He was very brave",
          "He led an army",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-5",
        question: "What were the two signs given to him?",
        options: [
          "The staff and his shining hand",
          "A ring and a cloak",
          "A book and a pen",
          "A cloud and rain",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-6",
        question: "Who was sent with him as a helper?",
        options: ["His brother Harun", "Yusha", "Shu'ayb", "Dawud"],
        correctIndex: 0,
      },
      {
        id: "musa-7",
        question: "What did the magicians do when they saw the truth?",
        options: [
          "They believed in Allah",
          "They ran away",
          "They attacked Musa",
          "They asked for money",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-8",
        question: "How did Bani Israil cross the sea?",
        options: [
          "Allah parted it when Musa struck it with his staff",
          "They used boats",
          "They built a bridge",
          "They walked around it",
        ],
        correctIndex: 0,
      },
      {
        id: "musa-9",
        question: "What happened to Pharaoh and his army?",
        options: ["They drowned", "They turned back", "They believed", "They stayed in Egypt"],
        correctIndex: 0,
      },
      {
        id: "musa-10",
        question: "Which book was revealed to Musa?",
        options: ["The Tawrah", "The Injil", "The Zabur", "The Qur'an"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "harun",
    name: "Harun",
    arabicName: "هَارُون",
    title: "The eloquent brother and helper of Musa",
    emoji: "🗣️",
    accent: "from-purple-400 to-fuchsia-500",
    summary:
      "Harun was given to Musa as a helper; he spoke clearly and stayed gentle when his people went astray.",
    story: [
      "When Allah sent Musa to Pharaoh, Musa made a dua asking for his brother Harun (peace be upon him) to be sent with him, because Harun spoke more clearly and would strengthen him. Allah accepted the dua and made Harun a prophet too. They went together to the greatest tyrant of their time and delivered the message with courage and good words.",
      "Harun supported his brother in every difficulty. He helped guide Bani Israil out of Egypt and taught them what Allah had revealed. When Musa left for the mountain to receive the Tawrah, he put Harun in charge of the people.",
      "During that time a man called Samiri made a golden calf, and many people began to worship it. Harun warned them strongly that this was a test and that their Lord was Ar-Rahman, but they refused to listen and threatened him. He avoided fighting them so the nation would not split, and waited for Musa to return. Musa was angry at first, but understood, and both prayed for forgiveness. Their story teaches the value of teamwork, gentleness and holding a community together.",
    ],
    lessons: [
      "Ask Allah for helpers — good work needs teamwork.",
      "Speak clearly and kindly when calling to the truth.",
      "Wisdom sometimes means avoiding a fight to protect unity.",
    ],
    questions: [
      {
        id: "harun-1",
        question: "Who asked for Harun to be sent as a helper?",
        options: ["Musa", "Pharaoh", "Bani Israil", "Shu'ayb"],
        correctIndex: 0,
      },
      {
        id: "harun-2",
        question: "Why was Harun a good helper?",
        options: [
          "He spoke very clearly",
          "He was a soldier",
          "He was a builder",
          "He was a merchant",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-3",
        question: "Was Harun also a prophet?",
        options: ["Yes", "No", "Only a teacher", "Only a leader"],
        correctIndex: 0,
      },
      {
        id: "harun-4",
        question: "Who did they both go to warn?",
        options: ["Pharaoh", "The people of 'Ad", "Thamud", "The people of Madyan"],
        correctIndex: 0,
      },
      {
        id: "harun-5",
        question: "Who was left in charge when Musa went to the mountain?",
        options: ["Harun", "Samiri", "Yusha", "Pharaoh's wife"],
        correctIndex: 0,
      },
      {
        id: "harun-6",
        question: "What did Samiri make?",
        options: ["A golden calf", "A temple", "A ship", "An idol of stone"],
        correctIndex: 0,
      },
      {
        id: "harun-7",
        question: "What did Harun tell the people?",
        options: [
          "That it was a test and their Lord is Ar-Rahman",
          "That the calf was allowed",
          "To wait silently",
          "To leave the camp",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-8",
        question: "Why did Harun avoid fighting them?",
        options: [
          "So the nation would not split apart",
          "He was afraid of Samiri",
          "He agreed with them",
          "He was ill",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-9",
        question: "What did Musa do when he returned?",
        options: [
          "He was angry, then understood and prayed for forgiveness",
          "He left the people",
          "He worshipped the calf",
          "He punished Harun",
        ],
        correctIndex: 0,
      },
      {
        id: "harun-10",
        question: "What lesson do we learn from Harun?",
        options: [
          "Good work needs teamwork, gentle speech and unity",
          "Leaders should be harsh",
          "Speaking clearly is unimportant",
          "It is fine to worship images",
        ],
        correctIndex: 0,
      },
    ],
  },
];
