import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_2: BuiltInLesson[] = [
  {
    id: "ibrahim",
    name: "Ibrahim",
    arabicName: "إِبْرَاهِيم",
    title: "The friend of Allah who broke the idols",
    emoji: "🕋",
    accent: "from-violet-400 to-purple-500",
    summary:
      "Ibrahim argued against idol worship, survived the fire, and built the Ka'bah with his son Ismail.",
    story: [
      "Ibrahim (peace be upon him) grew up among people who worshipped idols, including his own father who carved them. Even as a young man he used his mind: he looked at the stars, the moon and the sun and understood that none of them could be his Lord, because they all disappear. He knew his Lord was the One who created everything.",
      "He asked his people why they worshipped statues that could not hear, see or help. One day, while they were away at a festival, he broke their idols and left the largest one standing. When they accused him, he told them to ask the big idol — and they had to admit that idols cannot speak. Instead of accepting the truth, they lit a huge fire and threw him into it. Allah commanded the fire to be cool and safe, and Ibrahim walked out unharmed.",
      "Ibrahim was tested again and again: he left his homeland, he was tested with the command about his son, and he passed every test with trust in Allah. With his son Ismail he raised the walls of the Ka'bah in Makkah and prayed that his family and the people who came after would remain in worship of Allah. Allah honoured him with the title Khalilullah, the close friend of Allah.",
      `Description of Abraham and his Family — Some of the People of the Book stated that his name was Abraham Ibn Tarikh, Ibn Nahur, Ibn Sarough, Ibn Raghu, Ibn Phaligh, Ibn Aher, Ibn Shalih, Ibn Arfghshand, Ibn Sam, Ibn Noah.`,
      `They said that when Tarikh was seventy five years old, he had Abraham, Nahor (Nohour) and Haran. Haran had a son named Lot.`,
      `They also said that Abraham was the middle child and that Haran died in the lifetime of his father in the land where he was born, the land of the Chaldeans (Al Kaldanieen), also known as Babylonia.`,
      `At that time some people worshipped idols of stone and wood; others worshipped the planets, stars, sun and moon; still others worshipped their kings and rulers.`,
      `Abraham was born into that atmosphere, into a typical family of that ancient time. The head of the family was not even an ordinary idolater, but was one who totally rejected Allah and who used to make the idols with his own hands.`,
      `Some traditions claimed that Abraham's father died before his birth and he was raised by an uncle whom Abraham called father. Other traditions said that his father was alive and was named Azer.`,
      `Into that family Abraham was born, destined to stand against his own family, against the entire system of his community. In brief, he stood against all kinds of polytheism.`,
      `Abraham's Childhood — He was endowed with spiritual understanding from an early age. Allah enlightened his heart and mind gave him wisdom from childhood. Allah the Almighty stated:`,
      `"Indeed We bestowed aforetime on Abraham his (portion of) guidance, and We were Well Acquainted with him( as to his Belief in the Oneness of Allah etc). (Ch 21:51)`,
      `During his early childhood Abraham realized that his father made strange statues. One day, he asked him about what it was he made. His father replied that he made statues of gods. Abraham was astonished and he spontaneously rejected the idea.`,
      `Being a child he played with such statues sitting on their backs as people sit on the backs of donkeys and mules.`,
      `One day his father saw him riding the statue of Mardukh and he became furious. He ordered his son not to play with it again.`,
      `Abraham asked: "What is this statue, father? It has big ears, bigger than ours." His father answered: "It is Mardukh, the god of gods, son! These big ears show his deep knowledge."`,
      `This made Abraham laugh, he was only seven years old at that time. — Abraham's Hatred for Idols`,
      `Years passed and Abraham grew. Since his childhood his heart had been full of hatred for these idols. He could not understand how a sane person could make a statue and then worship what he had made.`,
      `He noticed that these idols did not eat, drink or talk and they could not even turn themselves right side up if someone turned them upside down.`,
      `How, then could people believe that such statues could harm or benefit them? Abraham 's people had a big temple full of idols, in the middle of which was a niche accommodating the biggest gods which was of different kinds, qualities and shapes.`,
      `Abraham, who used to go to the temple with his father when he was a child, greatly despised all that wood and stone.`,
      `What surprised him was the way his people behaved when they entered the temple; they bowed and started to cry, begging and imploring their gods for help as if the idols could hear or understand these requests!`,
      `At first, such a sight seemed funny to Abraham, but later he began to feel angry. Was it not astonishing that all those people could be deceived? What added to the problem was that his father wanted him to be a priest when he was grown.`,
      `He wanted nothing more from his son that that he revere those statues, yet Abraham never stopped displaying his hatred and disdain of them.`,
      `Abraham Discovers Allah — One night Abraham left his house to go to a mountain. He walked alone in the dark until he chose a cave in the mountain where he sat resting his back against its wall. He looked at the sky.`,
      `He had hardly seen it when he remembered that he was looking at planets and stars which were worshipped by some people on earth. His young heart was filled with tremendous pain. He considered what was beyond the moon, the stars and the planets (i.e.`,
      `Allah) and was astonished that these celestial bodies were worshipped by men when they had been created to worship and obey their Creator, appearing and disappearing at His command.`,
    ],
    lessons: [
      "Use your mind — real faith is built on understanding, not blind habit.",
      "Stand for the truth even when you are the only one standing.",
      "Trusting Allah in hard tests brings the greatest honour.",
    ],
    questions: [
      {
        id: "ibrahim-1",
        question: "What did Ibrahim's people worship?",
        options: ["Idols", "The Ka'bah", "Angels", "Fire only"],
        correctIndex: 0,
      },
      {
        id: "ibrahim-2",
        question: "What did Ibrahim notice about the stars, moon and sun?",
        options: [
          "They are beautiful so they must be gods",
          "They disappear, so they cannot be the Lord",
          "They can hear duas",
          "They created the earth",
        ],
        correctIndex: 1,
      },
      {
        id: "ibrahim-3",
        question: "What did Ibrahim do to the idols?",
        options: [
          "He cleaned them",
          "He sold them",
          "He broke them and left the largest one",
          "He hid them",
        ],
        correctIndex: 2,
      },
      {
        id: "ibrahim-4",
        question: "What did he tell his people to do when they accused him?",
        options: [
          "Ask the big idol",
          "Rebuild the idols",
          "Wait for the king",
          "Bring more statues",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-5",
        question: "How did his people try to punish him?",
        options: [
          "They threw him into a fire",
          "They put him in prison forever",
          "They took his wealth",
          "They exiled him to the sea",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-6",
        question: "What happened in the fire?",
        options: [
          "Allah made it cool and safe",
          "It burned him badly",
          "It rained heavily",
          "The people put it out",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-7",
        question: "Which building did Ibrahim raise with his son?",
        options: ["The Ka'bah", "Masjid al-Aqsa", "A palace", "A tower"],
        correctIndex: 0,
      },
      {
        id: "ibrahim-8",
        question: "Which son helped him build it?",
        options: ["Ismail", "Ishaq", "Yaqub", "Yusuf"],
        correctIndex: 0,
      },
      {
        id: "ibrahim-9",
        question: "What honourable title was Ibrahim given?",
        options: [
          "Khalilullah — the close friend of Allah",
          "Kalimullah",
          "Ruhullah",
          "Amin",
        ],
        correctIndex: 0,
      },
      {
        id: "ibrahim-10",
        question: "What do we learn from Ibrahim's tests?",
        options: [
          "Trusting Allah in difficulty raises our rank",
          "Tests only come to bad people",
          "We should avoid all difficulty",
          "Faith needs no patience",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "lut",
    name: "Lut",
    arabicName: "لُوط",
    title: "The prophet who left a corrupt city",
    emoji: "🌋",
    accent: "from-orange-400 to-red-500",
    summary:
      "Lut warned his people against shameless sins and cruelty to guests; only he and his followers were saved.",
    story: [
      "Lut (peace be upon him) was a nephew of Ibrahim and believed in his message. Allah sent him as a prophet to the cities of Sodom, whose people had fallen into open sin. They were shameless in their immorality, they robbed travellers, and they treated guests cruelly instead of honouring them.",
      "Lut called them for many years to fear Allah and to leave their evil habits. They mocked him and threatened to drive him out of the town. Even his own wife did not believe in his message and sided with the people of the city.",
      "One night angels came in the form of guests. When the people of the town came to harm them, the angels told Lut that they had been sent to destroy the city, and ordered him to leave with his believing family and not look back. At dawn the city was overturned and a rain of stones fell upon it. Lut and the believers were saved, but his wife stayed behind and was destroyed with them. The story shows that Allah's punishment falls on stubborn sin, and that hospitality and modesty are part of faith.",
      `Description of the People of Sodom — Prophet Abraham (PBUH) left Egypt accompanied by his nephew Lut (PBUH), who then went to the city of Sodom (Sadum), which was on the western shore of the Dead Sea. This city was filled with evil. Its residents waylaid, robbed and killed travelers.`,
      `Another common evil among them was that men had sex with men instead of with women. This unnatural act later became known as sodomy (after the city of Sodom). It was practiced openly and unashamedly.`,
      `Lot's Message — It was at the height of these crimes and sins that Allah revealed to Prophet Lut (PBUH) that he should summon the people to give up their indecent behavior, but they were so deeply sunk in their immoral habits that they were deaf to Lot's preaching.`,
      `Swamped in their unnatural desires, they refused to listen, even when Lot warned them of Allah's punishment. Instead, they threatened to drive him out of the city if he kept on preaching.`,
      `Allah the Almighty revealed: The people of Lot (those dwelt in the towns of Sodom in Palestine) belied the Messengers when their brother Lot said to them: "Will you not fear Allah and obey Him? Verily! I am a trustworthy Messenger to you. SO fear Allah, keep your duty to Him, and obey me.`,
      `No reward do I ask of you for it (my Message of Islamic Monotheism) my reward is only from the Lord of the Alamin (mankind, jinn and all that exists).`,
      `Go you in unto the males of the Alamin (mankind), and leave those whom Allah has created for you to be your wives? Nay, you are a trespassing people!" They said: "If you cease not, O Lot! Verily, you will be one of those who are driven out!" HE said: "I am indeed, of those who disapprove with severe anger and fury your (this evil) action (of sodomy).`,
      `My Lord! Save me and my family from what they do." SO We saved him and his family, all except an old woman (this wife) among those who remained behind. (Ch 26:160-171 Quran)`,
      `The doings of Lot's people saddened his heart. Their unwholesome reputation spread throughout the land, while he struggled against them. As the years passed, he persisted in his mission but to no avail.`,
      `No one responded to his call and believed except for the members of his family, and even in his household, not all the members believed. Lot's wife, like Noah's wife, a disbeliever.`,
      `Allah the Almighty declared: "Allah set forth an example for those who disbelieve, the wife of Noah and the wife of Lot.`,
      `They were under two of Our righteous slaves, but they both betrayed their (husbands, by rejecting their doctrines) so they (Noah & Lut) benefited them (their respective wives) not, against Allah, and it was said: "Enter the Fire along with those who enter!" (Ch 66:10 Quran)`,
      `Angels Come to Meet Lot — If home is the place of comfort and rest, then Lut found none, for he was tormented both inside and outside his home. His life was continuous torture and he suffered greatly, but he remained patient and steadfast with his people.`,
      `The years rolled by, and still not one believed in him. Instead, they belittled his message and mockingly challenged him: "Bring Allah's Torment upon us if you are one of the truthful!" (Ch 29:29 Quran).`,
      `Overwhelmed with despair, Lot prayed to Allah to grant him victory and destroy the corrupt. Therefore, the angels left Abraham (pbuh) and headed for Sodom the town of Lut (pbuh). They reached the walls of the town in the afternoon.`,
      `The first person who caught sight of them was Lot's daughter, who was sitting beside the river, filling her jug with water. When she lifted her face and saw them, she was stunned that there could be men of such magnificent beauty on earth.`,
      `One of the tree men (angels) asked her: "O maiden, is there a place to rest?" Remembering the character of her people she replied, "Stay here and do not enter until I inform my father and return." Leaving her jug by the river, she swiftly ran home. "O father!" she cried.`,
      `"You are wanted by young men at the town gate and I have never before seen the like of their faces!"`,
      `Lot felt distressed as he quickly ran to his guests. He asked them where they came from and where they were going. They did not answer his questions. Instead they asked if he could host them. He started talking with them and impressed upon them the subject of his people's nature.`,
      `Lot was filled with turmoil; he wanted to convince his guests without offending them, not to spend the night there, yet at the same time he wanted to extend to them the expected hospitality normally accorded to guests. In vain he tried to make them understand the perilous situation.`,
      `At last, therefore, he requested them to wait until the night fell, for then no one would see them.`,
      `The Mob at Lot's House — When darkness fell on the town, Lot escorted his guest to his home. No one was aware of their presence. However, as soon as Lot's wife saw them, she slipped out of the house quietly so that no one noticed her.`,
      `Quickly, she ran to her people with the news and it spread to all the inhabitants like wildfire. The people rushed towards Lot quickly and excitedly. Lot was surprised by their discovery of his guests. and he wondered who could have informed them.`,
      `The matter became clear, however, when he could not find his wife, anywhere, thus adding grief to his sorrow.`,
    ],
    lessons: [
      "Modesty and shame are protections given by Allah.",
      "Honouring guests is a sign of a believing heart.",
      "Family ties cannot save a person who rejects the truth.",
    ],
    questions: [
      {
        id: "lut-1",
        question: "How was Lut related to Ibrahim?",
        options: ["His nephew", "His brother", "His son", "His cousin's son"],
        correctIndex: 0,
      },
      {
        id: "lut-2",
        question: "What were the sins of Lut's people?",
        options: [
          "Open immorality, robbery and harming guests",
          "Farming on holy days",
          "Building tall towers",
          "Refusing to pay taxes",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-3",
        question: "How did the people respond to Lut's warnings?",
        options: [
          "They mocked him and threatened to expel him",
          "They repented",
          "They asked for a sign and believed",
          "They left the city",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-4",
        question: "Who came to Lut in the form of guests?",
        options: ["Angels", "Traders", "Kings", "Travellers from Egypt"],
        correctIndex: 0,
      },
      {
        id: "lut-5",
        question: "What did the angels order Lut to do?",
        options: [
          "Leave the city with the believers and not look back",
          "Fight the people",
          "Stay and warn them again",
          "Hide inside his house",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-6",
        question: "What happened to the city?",
        options: [
          "It was overturned and stones rained on it",
          "It was flooded",
          "It was burned by an army",
          "It sank into the sea",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-7",
        question: "What happened to Lut's wife?",
        options: [
          "She stayed behind and was destroyed",
          "She was saved",
          "She became a believer at the end",
          "She travelled to Egypt",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-8",
        question: "Why did the people of the city deserve punishment?",
        options: [
          "They stubbornly refused to leave their sins",
          "They were poor",
          "They lived in the desert",
          "They had no prophet",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-9",
        question: "What good manners does this story highlight?",
        options: [
          "Honouring guests and keeping modesty",
          "Eating a lot",
          "Speaking loudly",
          "Travelling at night",
        ],
        correctIndex: 0,
      },
      {
        id: "lut-10",
        question: "What does Lut's wife teach us?",
        options: [
          "Being close to a prophet does not save someone who rejects faith",
          "Women cannot be believers",
          "Family always follows the truth",
          "Looking back is a small matter",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ismail",
    name: "Ismail",
    arabicName: "إِسْمَاعِيل",
    title: "The patient son and builder of the Ka'bah",
    emoji: "💧",
    accent: "from-teal-400 to-emerald-500",
    summary:
      "Ismail trusted Allah in the greatest test, and the well of Zamzam sprang for him as a baby.",
    story: [
      "Ismail (peace be upon him) was the son of Ibrahim and Hajar. By Allah's command, Ibrahim left them in the empty valley of Makkah with a little food and water. When the water ran out, Hajar ran between the hills of Safa and Marwah searching for help. Allah caused water to gush from the ground near the baby, and that spring is the well of Zamzam, which still flows today.",
      "As Ismail grew, Ibrahim saw in a dream that he was commanded to sacrifice his beloved son. He told Ismail about it, and Ismail answered with amazing calm: do what you have been commanded, and you will find me patient. When they both submitted, Allah called out that the test was complete and sent a ram to be sacrificed instead. Muslims remember this act of obedience every year in Eid al-Adha.",
      "Father and son later raised the walls of the Ka'bah together, praying that Allah accept their work. Ismail became a prophet to the people of that region and was known for keeping his promises. From his descendants came the final Prophet, Muhammad (peace be upon him).",
      `Abraham leaves Hajar and Ishmael — One day, Abraham woke up and asked his wife Hajar to get her son and prepare for a long journey. In a few days Abraham started out with his wife Hajar and their son Ishmael. The child was still nursing and not yet weaned.`,
      `Abraham walked through cultivated land, desert, and mountains until he reached the desert of the Arabian Peninsula and came to an uncultivated valley having no fruit, no trees, no food, no water. The valley had no sign of life.`,
      `After Abraham had helped his wife and child to dismount, he left them with a small amount of food and water which was hardly enough for 2 days. He turned around and walked away. He wife hurried after him asking: "Where are you going Abrahim, leaving us in this barren valley?"`,
      `Abraham did not answer her, but continued walking. She repeated what she had said, but he remained silent. Finally she understood that he was not acting on his own initiative. she realized that Allah had commanded him to do this.`,
      `She asked him : "Did Allah command you to do so?" He replied: "Yes." Then his great wife said: "We are not going to be lost, since Allah Who has commanded you is with us." Abraham invoked Almighty Allah thus:`,
      `"O Our Lord! I have made some of my offspring to dwell in a valley with no cultivation, by Your Sacred House (the Ka'ba at Mecca); in order, O our Lord, that they may offer prayers perfectly (Iqamat as salat) so fill some hearts among men with love towards them, and O Allah provide them with fruits so that they may give thanks.`,
      `O our Lord! Certainly, You know what we conceal and what we reveal. Nothing on the earth or in the heavens is hidden from Allah." (Ch 14:37-38)`,
      `Hajar and Ishmael - Narrated by Ibn Abbas — Ibn Abbas narrated: "The first lady to use a girdle was the mother of Ishmael. She used a girdle so that she might hide her tracks from Sarah (by dragging it).`,
      `Abraham brought her and her son Ishmael while she was suckling him to a place near the Kaba under a tree on the spot of ZamZam at the highest place in the mosque.`,
      `During those days there was nobody in Mecca, nor was there any water so he made them sit over there and placed near them a leather bag containing some dates and a small water skin containing some water and set out homeward. Ishmael's mother followed him saying:`,
      `"O Abraham! Where are you going, leaving us in this valley where there is no person whose company we may enjoy, nor is there anything to enjoy?" she repeated that to him many times, but he did not look back at her.`,
      `Then she asked him : "Has Allah ordered you to do so?" He said: "Yes." She then said: "Then He will not neglect us," and returned while Abraham proceeded onwards.`,
      `On reaching the Thaniya where they could not see him, he faced the Kaba and raising both hands, invoked Allah saying the following prayers:`,
      `"O our Lord! I have made some of my offspring dwell in a valley without cultivation, by Your Sacred House (Kaba at Mecca) in order, O our Lord that they may offer prayer perfectly.`,
      `So fill some hearts among men with love towards them, and O Allah provide them with fruits so that they may give thanks." (Ch 14:37)`,
      `Ibn Abbas's narration continued; "Ishmael's mother went on suckling Ishmael and drinking from the water (she had) When the water in the water skin had been used up, she became thirsty and her child also became thirsty, She started looking at him (Ishmael) tossing in agony.`,
      `She left him, for she could not endure looking at him, and found that the mountain of As-Safa was the nearest mountain to her on that land. she too on it and started looking at the valley keenly so that she might see somebody, but she could not see anybody.`,
      `Then she descended for As Safa and when she reached the valley, she tucked up her robe and ran in the valley like a person in distress and trouble till she crossed the valley and reached the mountain of Al Marwa.`,
      `There she stood and started looking expecting to see somebody, but she could not see anybody. She repeated that running between Safa And Marwa seven times."`,
      `Hajar sees Zam-zam - by Prophet Muhammad — The prophet Muhammad (pbuh) said: "This is the source of the tradition of the Sa'y (rituals of the hajj, pilgrimage) the going of people between them (As-Safa and Al-Marwa).`,
      `When she reached Al Marwa (for the last time) she heard a voice and she asked herself to be quiet and listened attentively.`,
      `She heard the voice again and said: "O whoever you maybe! You have made me hear your voice; have you got something to help me?" And behold! She saw an angel at the place of Zam zam, digging the earth with his heel (or his wing) till water flowed from that place.`,
      `She started to make something like a basin around it, using her hand in this way, and started filling her water skin with water with her hands and the water was flowing out water she had scooped some of it." The Prophet (pbuh) added: "May Allah bestow mercy on Ishmael's mother! Had she let the zam-zam flow without trying to control it, or had she not scooped from that water to fill her water skin, Zam zam would have been a stream flowing on the surface of the earth."`,
      `Makka is Settled - Told by Prophet Muhammad — The Prophet (pbuh) continued: "Then she drank water and suckled her child.`,
    ],
    lessons: [
      "Trust that Allah provides even in an empty desert.",
      "Real obedience is calm and willing, not forced.",
      "Keeping promises is a prophetic quality.",
    ],
    questions: [
      {
        id: "ismail-1",
        question: "Who were Ismail's parents?",
        options: [
          "Ibrahim and Hajar",
          "Ibrahim and Sarah",
          "Yaqub and Rahil",
          "Nuh and his wife",
        ],
        correctIndex: 0,
      },
      {
        id: "ismail-2",
        question: "Where were Hajar and baby Ismail left?",
        options: [
          "The valley of Makkah",
          "Egypt",
          "Madyan",
          "Jerusalem",
        ],
        correctIndex: 0,
      },
      {
        id: "ismail-3",
        question: "Between which two hills did Hajar search for help?",
        options: ["Safa and Marwah", "Uhud and Badr", "Judi and Sinai", "Arafat and Mina"],
        correctIndex: 0,
      },
      {
        id: "ismail-4",
        question: "What is the name of the spring that appeared?",
        options: ["Zamzam", "Kawthar", "Salsabil", "Tasnim"],
        correctIndex: 0,
      },
      {
        id: "ismail-5",
        question: "How did Ibrahim learn about the command to sacrifice his son?",
        options: ["Through a dream", "From a letter", "From an angel in the market", "From his people"],
        correctIndex: 0,
      },
      {
        id: "ismail-6",
        question: "How did Ismail respond?",
        options: [
          "He told his father to do as he was commanded and promised patience",
          "He ran away",
          "He asked for a delay",
          "He refused",
        ],
        correctIndex: 0,
      },
      {
        id: "ismail-7",
        question: "What did Allah send in place of Ismail?",
        options: ["A ram", "A camel", "A cow", "A bird"],
        correctIndex: 0,
      },
      {
        id: "ismail-8",
        question: "Which Eid remembers this event?",
        options: ["Eid al-Adha", "Eid al-Fitr", "Eid al-Ghadir", "Laylat al-Qadr"],
        correctIndex: 0,
      },
      {
        id: "ismail-9",
        question: "What did Ismail build with his father?",
        options: ["The Ka'bah", "A palace", "A city wall", "A ship"],
        correctIndex: 0,
      },
      {
        id: "ismail-10",
        question: "Which final prophet came from Ismail's descendants?",
        options: ["Muhammad (peace be upon him)", "Isa", "Musa", "Dawud"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ishaq",
    name: "Ishaq",
    arabicName: "إِسْحَاق",
    title: "The good news given to Ibrahim in old age",
    emoji: "🌟",
    accent: "from-lime-400 to-green-500",
    summary:
      "Ishaq was born to Ibrahim and Sarah in their old age and became a prophet after his father.",
    story: [
      "Ibrahim and his wife Sarah had grown very old and had no child together. One day guests came to Ibrahim's home, and he quickly prepared food for them, as generous people do. The guests were angels, and they brought news that Sarah would have a son. Sarah was astonished and laughed, asking how she could have a child at her age. The angels replied that this was the decree of Allah, and nothing is difficult for Him.",
      "The promised son was Ishaq (peace be upon him). He grew up in a household built on worship, honesty and generosity, and Allah made him a prophet. He carried on the message of his father, calling people to worship Allah alone and to keep good character.",
      "Allah blessed Ishaq with a son, Yaqub, who also became a prophet. Through this family a long line of prophets continued among Bani Israil. The story reminds us that Allah answers duas in His own time, and that His promise never fails even when it seems impossible.",
      `Isaac's Sons - from Commentators — The Quran does not give details of Isaac's life (pbuh), but reliable Quranic commentators mentioned that when Abraham felt that his life was drawing to a close, he wished to see Isaac married.`,
      `He did not want Isaac to marry one of the Canaanites, who were pagans, so he sent a trustworth servant to Haran in Iraq to choose a bride for Isaac. The servant's choice fell upon Rebekah Bint Bethuel, Ibn Nahor (who was a brother of Abraham).`,
      `Isaac married her and she gave birth to a set of twins, Esau (Al Eis) and Jacob (Yaqub).`,
      `Ill feelings developed between the two brothers when they grew into manhood. Esau disliked the fact that Jacob was favoured by his father and by Allah with prophethood. This ill feeling became so searious that Esau threatened to kill his brother. Fearing for his life, Jacob fled the country.`,
      `Isaac's Sons - from the People of the Book — The People of the Book said that when Isaac was forty years old, he married Rebekah Bint Bethuel, during his father's life. They said she was sterile, so Isaac prayed to Allah and then she became pregnant. She gave birth to twin boys.`,
      `The first one was called Esau whom the Arabs called Al-Eis. He became the father of Rum. The second one was called Jacob, which means Isreal, (belonging to the people of Israel).`,
      `Issac's Death — Jacob came to his father Isaac and settled with him in the village of Hebron which lies in the land of Canaan where Abraham had lived. Then Isaac fell ill and died when he was one hundred eighty years old.`,
      `His sons Esau and Jacob buried him with his father Abraham Al Khalil in a cave which he had bought. It was said that Abraham died at the age of one hundred seventy five.`,
    ],
    lessons: [
      "Nothing is impossible for Allah — never lose hope in dua.",
      "Generosity to guests is a habit of the righteous.",
      "A home built on worship raises righteous children.",
    ],
    questions: [
      {
        id: "ishaq-1",
        question: "Who were Ishaq's parents?",
        options: [
          "Ibrahim and Sarah",
          "Ibrahim and Hajar",
          "Yaqub and Rahil",
          "Lut and his wife",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-2",
        question: "Who brought the good news of his birth?",
        options: ["Angels in the form of guests", "A merchant", "A king", "A neighbour"],
        correctIndex: 0,
      },
      {
        id: "ishaq-3",
        question: "How did Ibrahim treat the guests?",
        options: [
          "He quickly prepared food for them",
          "He sent them away",
          "He ignored them",
          "He asked them for money",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-4",
        question: "Why was Sarah astonished?",
        options: [
          "She and Ibrahim were very old",
          "She did not know the guests",
          "She was travelling",
          "She had many children already",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-5",
        question: "What did the angels say about Allah's decree?",
        options: [
          "Nothing is difficult for Allah",
          "It might change",
          "It depends on people",
          "It was only a hope",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-6",
        question: "What did Ishaq become?",
        options: ["A prophet", "A king only", "A merchant", "A judge only"],
        correctIndex: 0,
      },
      {
        id: "ishaq-7",
        question: "Which prophet was Ishaq's son?",
        options: ["Yaqub", "Yusuf", "Musa", "Harun"],
        correctIndex: 0,
      },
      {
        id: "ishaq-8",
        question: "What message did Ishaq carry?",
        options: [
          "To worship Allah alone and keep good character",
          "To collect wealth",
          "To build large cities",
          "To fight neighbouring tribes",
        ],
        correctIndex: 0,
      },
      {
        id: "ishaq-9",
        question: "Through this family, which nation received many prophets?",
        options: ["Bani Israil", "The people of 'Ad", "Thamud", "Madyan"],
        correctIndex: 0,
      },
      {
        id: "ishaq-10",
        question: "What lesson does the birth of Ishaq teach?",
        options: [
          "Allah answers dua in His own time and His promise never fails",
          "Old age prevents blessings",
          "Guests should not be fed",
          "Laughing is forbidden",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "yaqub",
    name: "Yaqub",
    arabicName: "يَعْقُوب",
    title: "The patient father of Yusuf",
    emoji: "🕊️",
    accent: "from-cyan-400 to-blue-500",
    summary:
      "Yaqub, also called Israil, showed beautiful patience when he lost his beloved son Yusuf.",
    story: [
      "Yaqub (peace be upon him) was the son of Ishaq and the grandson of Ibrahim. He is also called Israil, and his twelve sons became the tribes of Bani Israil. He raised his children to worship Allah alone and, when he was dying, his final advice to them was to hold on to Islam — submission to Allah.",
      "Yaqub loved his son Yusuf dearly. When Yusuf told him about a dream of eleven stars, the sun and the moon prostrating to him, Yaqub understood that his son would be given something great and told him not to tell his brothers. Later the brothers took Yusuf away and returned with a shirt stained with blood, claiming a wolf had eaten him. Yaqub did not believe them, but he did not despair either. He said he would be patient and seek help from Allah alone.",
      "For many years he grieved, yet he kept telling his sons never to lose hope in Allah's mercy. In the end Allah reunited him with Yusuf in Egypt, and his eyesight and joy were restored. His story is the finest example of 'beautiful patience' — sadness that does not turn into complaint against Allah.",
      `Isaac's Sons - Jacob and Esau — Isaac married Rebekah Bint Bethuel, Ibn Nahor, and she gave birth to a set of twins, Esau (Al Eis) and Jacob (Yaqub). Ill feelings developed between the two brothers when they grew into manhood.`,
      `Esau disliked the fact that Jacob was favored by his father and by Allah with prophethood. This ill feeling became so serious that Esau threatened to kill his brother. Fearing for his life, Jacob fled the country.`,
      `Isaac's Sons - from the People of the Book — The People of the Book said that when Isaac was forty years old, he married Rebekah, Bint Bethuel, during his father's life. They said she was sterile, so Isaac prayed to Allah and then she became pregnant. She gave birth to twin boys.`,
      `The first one was called Esau whom the Arabs called Al-Eis. He became the father of Rum. The second one was called Jacob, which means Isreal, (belonging to the people of Israel).`,
      `The People of the Book claimed that when Isaac (pbuh) grew old and his eye sight had weakened, he had a desire for food, so he asked his son Esau to go hunting and bring him some cooked game. Esau asked him to bless the food and pray for him. Esau, a hunter, went out to get his father the meat.`,
      `Rebekah, overhearing this, ordered her son Jacob to slaughter two goats of his best flock and cook them as his father liked and bring it to him before his brother returned. She dressed Jacob in his brother's clothes and put goat skin on his arms and neck, for Esau was hairy while Jacob was not.`,
      `When he approached his father with the food, his father asked: 'Who are you?' Jacob answered: 'I am your son.' When his father finished eating, he prayed for his son to be the more blessed brother and to prevail over them and all people, and for Allah to sustain him and his children.`,
      `When he left his father, his brother Esau, who had carried out his father's command, entered.`,
      `Isaac asked him: "What is this my son?" He answered: "This is the food you like." Isaac asked: "Did you bring it an hour ago and ask me to pray for you?" Esau said: "No, I swear I did not," and he knew his brother had preceded him in this matter and he was sick at heart.`,
      `Jacob Leaves his Home - from the People of the Book — The People of the Book said Esau threatened to kill his brother when their father was dead. They also said that he asked his father to pray for him that Allah make the earth good for his offspring and multiply his sustenance and fruits.`,
      `When their mother knew that Esau threatened his brother Jacob, she commanded her son Jacob to go to her brother Laban in the land of Haran and abide with him for a time until his brother's anger had abated, and to marry one of the Laban's daughters.`,
      `She told her husband Isaac to command him with that advice and pray for him, and he did.`,
      `Jacob's Promise — Jacob (pbuh) left his family, when night came he found a place to rest. He took a stone and put it under his head and slept. He dreamed of a ladder from heaven to earth.`,
      `Angels were ascending and descending and the Lord addressed him and said to him; "I will bless you and your offspring and make this land for you and for those who come after you." When he awoke he felt joyful from what he had seen in his dream and vowed, for Allah's sake that if he returned to his family safely, he would build here a temple for Allah the Almighty.`,
      `He also vowed to give one tenth of his property for the sake of Allah. He poured oil on the stone so as to recognize it and called the place "Ayle's House" (Bethel), which means "House of Allah". It was to be the location of Jerusalem later.`,
      `Jacob's Wives - from the People of the Book — The People of the Book also said that when Jacob came to his maternal uncle in the land of Haran, his uncle had two daughters. The elder one was called Leah (Lia) and the younger one was Rachel (Rahil). The latter was the better and lovelier of the two.`,
      `His uncle agreed to marry his daughter to him on the condition that Jacob pasture his sheep for seven years. After a period of time, his uncle prepared a feast and gathered people for the wedding. He married Leah, his elder daughter, to him at night. She was weak-sighted and ugly.`,
      `When morning came, Jacob discovered she was Leah and he complained to his uncle. "You deceived me; I was engaged to Rachel and you married me to Leah." His uncle said: "It is not our tradition to marry the younger daughter before the elder daughter.`,
      `However, if you love her sister, work another seven years and I will marry you to both of them." Jacob worked for seven years and then married Rachel. It was acceptable in their time, as described in the Torah, for a man to marry two sisters. Laban gave a female slave to each daughter.`,
      `Leah's slave was called Zilpah and Rachel's slave was called Bilha.`,
      `Jacob's Children - from the People of the Book — Almighty Allah compensated Leah's weakness by giving her sons. The first one was named Rueben (Robel), after whom there were Simon (Shamun), Levi (Lawi), and Judah (Yahudh). Rachel felt jealous of Leah's having sons, as she was barren.`,
      `She gave her slave Bilha to her husband and he had relations with her until she became pregnant. She gave birth to a son and named him Naphtali.`,
      `Leah was vexed that Rachel's slave had give birth to a son, so she in turn gave her slave Zilpah to Jacob (pbuh), Zilpah gave birth to two sons, Gad and Asher. Then Leah got pregnant and gave birth to her fifth son, Issaacher, and later she gave birth to a sixth son Zebulun.`,
      `After this Leah gave birth to a daughter named Dinah. Thus, Leah had seven sons from Jacob. Then Rachel prayed to Allah to give her a son from Jacob. Allah heard her call and responded to her prayer. She gave birth to a son, great, honorable, and beautiful. She named him Joseph (Yusuf).`,
    ],
    lessons: [
      "Beautiful patience means grieving without complaining against Allah.",
      "Never lose hope in Allah's mercy, no matter how long the test.",
      "A parent's most important gift is teaching tawhid.",
    ],
    questions: [
      {
        id: "yaqub-1",
        question: "Who was Yaqub's father?",
        options: ["Ishaq", "Ismail", "Ibrahim", "Yusuf"],
        correctIndex: 0,
      },
      {
        id: "yaqub-2",
        question: "By which other name is Yaqub known?",
        options: ["Israil", "Kalimullah", "Ruhullah", "Al-Amin"],
        correctIndex: 0,
      },
      {
        id: "yaqub-3",
        question: "How many sons did he have?",
        options: ["Twelve", "Seven", "Four", "Twenty"],
        correctIndex: 0,
      },
      {
        id: "yaqub-4",
        question: "What was his final advice to his sons?",
        options: [
          "To hold on to Islam and worship Allah alone",
          "To divide his wealth",
          "To travel to Egypt",
          "To build a temple",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-5",
        question: "What did Yusuf see in his dream?",
        options: [
          "Eleven stars, the sun and the moon prostrating",
          "Seven cows",
          "A ship on the sea",
          "A garden of palm trees",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-6",
        question: "Why did Yaqub tell Yusuf not to tell his brothers?",
        options: [
          "He feared their jealousy",
          "The dream was unimportant",
          "They would not understand dreams",
          "He wanted to tell them himself",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-7",
        question: "What did the brothers claim happened to Yusuf?",
        options: [
          "A wolf had eaten him",
          "He was lost in a storm",
          "He travelled to Egypt",
          "He fell ill",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-8",
        question: "How did Yaqub react to the news?",
        options: [
          "With patience, seeking help from Allah",
          "With anger and revenge",
          "By giving up faith",
          "By punishing his sons",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-9",
        question: "What did he keep telling his sons about Allah's mercy?",
        options: [
          "Never to lose hope in it",
          "That it is only for prophets",
          "That it had ended",
          "That it needs no dua",
        ],
        correctIndex: 0,
      },
      {
        id: "yaqub-10",
        question: "How did his long test end?",
        options: [
          "Allah reunited him with Yusuf in Egypt",
          "He never saw Yusuf again",
          "He moved to Makkah",
          "His sons left him",
        ],
        correctIndex: 0,
      },
    ],
  },
];
