import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_4: BuiltInLesson[] = [
  {
    id: "dhul-kifl",
    name: "Dhul-Kifl",
    arabicName: "ذُو الْكِفْل",
    title: "The prophet who kept every promise",
    emoji: "🤝",
    accent: "from-slate-400 to-slate-600",
    summary:
      "Dhul-Kifl is praised in the Qur'an among the patient and righteous prophets who kept their word.",
    story: [
      "Dhul-Kifl (peace be upon him) is mentioned twice in the Qur'an, always in the company of great prophets such as Ismail and Idris. Allah describes them together as people of patience and as righteous servants who were chosen by Him.",
      "His name is understood to mean the one who takes on a share or a guarantee, because he promised to carry out duties and never broke his word. It is said that he judged between people with fairness, kept himself away from anger, and spent his nights in worship. He accepted heavy responsibilities and fulfilled them without complaining.",
      "The Qur'an does not give a long account of his life, and that itself is a lesson: what matters most is not fame or detail, but that Allah counted him among the patient and the righteous. A believer can be almost unknown to people yet honoured by Allah.",
    ],
    lessons: [
      "Keeping your word is a mark of true faith.",
      "Patience and fairness are praised by Allah even without fame.",
      "Accept responsibility, then fulfil it properly.",
    ],
    questions: [
      {
        id: "dhul-kifl-1",
        question: "How many times is Dhul-Kifl mentioned in the Qur'an?",
        options: ["Twice", "Ten times", "Once", "Never"],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-2",
        question: "With which prophets is he mentioned?",
        options: [
          "Ismail and Idris",
          "Musa and Harun",
          "Isa and Yahya",
          "Nuh and Hud",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-3",
        question: "How does Allah describe him and those with him?",
        options: [
          "As patient and righteous servants",
          "As kings",
          "As wealthy men",
          "As warriors",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-4",
        question: "What does his name suggest?",
        options: [
          "One who takes on a share or guarantee",
          "One who travels",
          "One who writes",
          "One who fights",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-5",
        question: "What is he known for in the reports about him?",
        options: [
          "Judging fairly and keeping his promises",
          "Building cities",
          "Leading armies",
          "Collecting wealth",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-6",
        question: "How did he spend his nights?",
        options: ["In worship", "In trade", "In travel", "In meetings"],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-7",
        question: "How did he deal with anger?",
        options: [
          "He kept himself away from it",
          "He used it against enemies",
          "He ignored justice",
          "He punished quickly",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-8",
        question: "How did he treat heavy responsibilities?",
        options: [
          "He fulfilled them without complaining",
          "He refused them",
          "He passed them to others",
          "He delayed them",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-9",
        question: "Why is the shortness of his story itself a lesson?",
        options: [
          "Honour with Allah does not depend on fame",
          "His story was forgotten",
          "He did little good",
          "He lived a short life",
        ],
        correctIndex: 0,
      },
      {
        id: "dhul-kifl-10",
        question: "What quality should we copy from him?",
        options: [
          "Keeping our promises",
          "Speaking a lot",
          "Seeking praise",
          "Avoiding people",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "dawud",
    name: "Dawud",
    arabicName: "دَاوُد",
    title: "The young shepherd who defeated Jalut",
    emoji: "🎶",
    accent: "from-amber-400 to-yellow-600",
    summary:
      "Dawud defeated the giant Jalut, was given the Zabur and a beautiful voice, and ruled with justice.",
    story: [
      "Dawud (peace be upon him) was a young man in the army of Talut when Bani Israil faced the powerful warrior Jalut (Goliath). While the soldiers were afraid, Dawud trusted Allah, went forward with a sling and stones, and defeated Jalut. Allah then gave him kingship and prophethood together.",
      "Allah gave Dawud special gifts: the Zabur (Psalms), a voice so beautiful that the birds and mountains would join him in glorifying Allah, and the skill of shaping iron to make armour. He earned his own living from his craft instead of taking from the treasury. He fasted often, prayed at night, and judged between people with justice.",
      "Once two men came to him with a dispute and he judged quickly; Allah taught him to listen to both sides carefully, and Dawud turned to Allah in repentance immediately. He is remembered as a servant who was always thankful, always returning to his Lord, and a king who never let power make him proud.",
    ],
    lessons: [
      "Courage comes from trust in Allah, not from body size.",
      "Earning your own halal living is honourable.",
      "Justice means listening carefully to both sides.",
    ],
    questions: [
      {
        id: "dawud-1",
        question: "Whom did Dawud defeat as a young man?",
        options: ["Jalut", "Pharaoh", "Samiri", "Namrud"],
        correctIndex: 0,
      },
      {
        id: "dawud-2",
        question: "What did he use in the battle?",
        options: ["A sling and stones", "A long spear", "A chariot", "A bow of iron"],
        correctIndex: 0,
      },
      {
        id: "dawud-3",
        question: "Which army was he part of?",
        options: ["The army of Talut", "The army of Egypt", "The army of Madyan", "The army of Rome"],
        correctIndex: 0,
      },
      {
        id: "dawud-4",
        question: "Which book was given to Dawud?",
        options: ["The Zabur", "The Tawrah", "The Injil", "The Qur'an"],
        correctIndex: 0,
      },
      {
        id: "dawud-5",
        question: "What happened when he glorified Allah?",
        options: [
          "The birds and mountains joined him",
          "The sea parted",
          "Rain fell",
          "The sun stopped",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-6",
        question: "Which craft was he taught?",
        options: [
          "Shaping iron to make armour",
          "Building ships",
          "Weaving cloth",
          "Making glass",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-7",
        question: "How did he earn his living as a king?",
        options: [
          "From his own craft, not the treasury",
          "From taxes only",
          "From gifts of other kings",
          "He did not work",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-8",
        question: "What acts of worship was he known for?",
        options: [
          "Frequent fasting and night prayer",
          "Only charity",
          "Only fasting in Ramadan",
          "Only reciting poetry",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-9",
        question: "What did Allah teach him about judging?",
        options: [
          "To listen carefully to both sides",
          "To judge quickly",
          "To follow the stronger party",
          "To leave judging to others",
        ],
        correctIndex: 0,
      },
      {
        id: "dawud-10",
        question: "How is Dawud remembered?",
        options: [
          "A thankful servant who always returned to Allah",
          "A proud king",
          "A silent worshipper",
          "A wealthy trader",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "sulayman",
    name: "Sulayman",
    arabicName: "سُلَيْمَان",
    title: "The king who understood the language of animals",
    emoji: "🐜",
    accent: "from-emerald-500 to-teal-600",
    summary:
      "Sulayman was given a mighty kingdom, control of the wind and jinn, and the speech of animals — and stayed grateful.",
    story: [
      "Sulayman (peace be upon him) was the son of Dawud and inherited both prophethood and kingship. He asked Allah for a kingdom that no one after him would have, and Allah answered him. The wind carried his command, the jinn worked for him, and he understood the speech of birds and animals. He never let these gifts make him arrogant; he said openly that all of it was from the favour of his Lord.",
      "One day, while marching with his army, he heard an ant warning the others to hide so they would not be crushed. Sulayman smiled and thanked Allah for teaching him to be gentle. Another time the hoopoe bird brought news of the people of Saba who worshipped the sun. Sulayman sent them a letter inviting them to worship Allah alone. Their queen, Bilqis, came to visit, saw his wisdom and the throne prepared for her, and accepted faith in Allah.",
      "Sulayman also built and repaired places of worship and ruled with justice. He died standing, leaning on his staff, and the jinn kept working until a small creature ate through the staff and he fell — showing everyone that even the greatest king is a servant of Allah, and only Allah knows the unseen.",
    ],
    lessons: [
      "Great blessings should increase gratitude, not pride.",
      "Kindness includes even the smallest creatures.",
      "Wisdom invites people to the truth gently.",
    ],
    questions: [
      {
        id: "sulayman-1",
        question: "Who was Sulayman's father?",
        options: ["Dawud", "Yaqub", "Ishaq", "Musa"],
        correctIndex: 0,
      },
      {
        id: "sulayman-2",
        question: "What did Sulayman ask Allah for?",
        options: [
          "A kingdom that no one after him would have",
          "Endless wealth only",
          "A long life",
          "An army of men",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-3",
        question: "Which creatures worked for him by Allah's permission?",
        options: ["The jinn", "The angels", "The birds only", "Sea creatures"],
        correctIndex: 0,
      },
      {
        id: "sulayman-4",
        question: "What did he understand that others could not?",
        options: [
          "The speech of birds and animals",
          "The future",
          "Every language of men only",
          "The thoughts of people",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-5",
        question: "What did the ant say?",
        options: [
          "It warned the other ants to hide",
          "It asked for food",
          "It praised the army",
          "It called for rain",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-6",
        question: "Which bird brought news of Saba?",
        options: ["The hoopoe", "An eagle", "A crow", "A dove"],
        correctIndex: 0,
      },
      {
        id: "sulayman-7",
        question: "What were the people of Saba worshipping?",
        options: ["The sun", "Idols of stone", "Fire", "The moon"],
        correctIndex: 0,
      },
      {
        id: "sulayman-8",
        question: "Who was the queen who came to visit him?",
        options: ["Bilqis", "Asiya", "Sarah", "Maryam"],
        correctIndex: 0,
      },
      {
        id: "sulayman-9",
        question: "How did Sulayman treat his great blessings?",
        options: [
          "He thanked Allah and said they were from His favour",
          "He became proud",
          "He hid them",
          "He gave up his kingdom",
        ],
        correctIndex: 0,
      },
      {
        id: "sulayman-10",
        question: "How did the jinn learn that he had died?",
        options: [
          "A small creature ate his staff and he fell",
          "An angel told them",
          "He wrote a letter",
          "The wind stopped",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "ilyas",
    name: "Ilyas",
    arabicName: "إِلْيَاس",
    title: "The prophet who stood against Ba'l worship",
    emoji: "⛈️",
    accent: "from-sky-500 to-blue-700",
    summary:
      "Ilyas warned his people against worshipping the idol Ba'l and called them back to Allah alone.",
    story: [
      "Ilyas (peace be upon him) was sent to a people of Bani Israil who had left the way of Musa and started worshipping an idol they called Ba'l. Their leaders encouraged this, and the ordinary people followed without thinking.",
      "Ilyas stood before them and asked a simple question: will you worship Ba'l and leave the best of creators — Allah, your Lord and the Lord of your forefathers? He warned them of the consequences of shirk and reminded them of the blessings they enjoyed.",
      "Most of them rejected him, and only a small group believed. Allah saved Ilyas and the believers, and the Qur'an says that peace be upon Ilyas and that Allah left a good remembrance of him among later generations. His story shows that a believer's duty is to speak the truth clearly, even to a whole society that has gone the wrong way.",
    ],
    lessons: [
      "Following the crowd is not an excuse before Allah.",
      "Speak the truth clearly even when few will accept it.",
      "Allah preserves a good name for those who stand for Him.",
    ],
    questions: [
      {
        id: "ilyas-1",
        question: "Which idol were the people of Ilyas worshipping?",
        options: ["Ba'l", "Al-Lat", "The golden calf", "The sun"],
        correctIndex: 0,
      },
      {
        id: "ilyas-2",
        question: "To which nation was Ilyas sent?",
        options: ["A people of Bani Israil", "The people of 'Ad", "Thamud", "Quraysh"],
        correctIndex: 0,
      },
      {
        id: "ilyas-3",
        question: "What question did he ask them?",
        options: [
          "Will you worship Ba'l and leave the best of creators?",
          "Why do you not build temples?",
          "Where is your king?",
          "Why do you not travel?",
        ],
        correctIndex: 0,
      },
      {
        id: "ilyas-4",
        question: "Whose way had they abandoned?",
        options: ["The way of Musa", "The way of Isa", "The way of Nuh", "The way of Ibrahim only"],
        correctIndex: 0,
      },
      {
        id: "ilyas-5",
        question: "Who encouraged the idol worship?",
        options: ["Their leaders", "Their prophets", "Travellers", "Their children"],
        correctIndex: 0,
      },
      {
        id: "ilyas-6",
        question: "How did most people respond to Ilyas?",
        options: ["They rejected him", "They believed", "They asked for a sign", "They left the city"],
        correctIndex: 0,
      },
      {
        id: "ilyas-7",
        question: "What happened to Ilyas and the believers?",
        options: ["Allah saved them", "They were destroyed", "They were exiled", "They were imprisoned"],
        correctIndex: 0,
      },
      {
        id: "ilyas-8",
        question: "What does the Qur'an say about Ilyas?",
        options: [
          "Peace be upon him, and a good remembrance was left of him",
          "That he was a king",
          "That he wrote a book",
          "That he had a large army",
        ],
        correctIndex: 0,
      },
      {
        id: "ilyas-9",
        question: "Why did the ordinary people follow the idol?",
        options: [
          "They followed their leaders without thinking",
          "They were forced by another nation",
          "They had no prophet",
          "They could not read",
        ],
        correctIndex: 0,
      },
      {
        id: "ilyas-10",
        question: "What is the lesson for us?",
        options: [
          "We must speak the truth even if society disagrees",
          "We should always follow the majority",
          "Idols are harmless",
          "Prophets only warn kings",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "al-yasa",
    name: "Al-Yasa'",
    arabicName: "الْيَسَع",
    title: "The chosen successor of Ilyas",
    emoji: "🌿",
    accent: "from-green-400 to-emerald-600",
    summary:
      "Al-Yasa' continued the mission of Ilyas and is praised by Allah as one of the chosen and excellent servants.",
    story: [
      "Al-Yasa' (peace be upon him) lived among Bani Israil and was a companion and student of Ilyas. When Ilyas' mission ended, Al-Yasa' carried it on, calling the people back to the worship of Allah alone after they had turned to idols.",
      "The Qur'an mentions him twice, listing him with Ismail and Dhul-Kifl, and describing them as chosen ones and among the excellent. This means his patience and sincerity were accepted by Allah, even though the details of his life are not narrated at length.",
      "He continued teaching, reminding and warning his people, and he faced the same stubbornness that earlier prophets faced. His story shows that the message of tawhid never stops: when one caller passes, another takes up the responsibility, and every generation needs people who remind it of Allah.",
    ],
    lessons: [
      "Good work should be continued by the next generation.",
      "Learning from a righteous teacher shapes a righteous life.",
      "Allah counts sincerity, even when people forget your details.",
    ],
    questions: [
      {
        id: "al-yasa-1",
        question: "Whose mission did Al-Yasa' continue?",
        options: ["Ilyas", "Musa", "Dawud", "Yunus"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-2",
        question: "Among which people did he live?",
        options: ["Bani Israil", "'Ad", "Thamud", "Madyan"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-3",
        question: "How does the Qur'an describe him?",
        options: [
          "Among the chosen and the excellent",
          "As a king",
          "As a rich merchant",
          "As a warrior",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-4",
        question: "With which prophets is he listed?",
        options: [
          "Ismail and Dhul-Kifl",
          "Musa and Harun",
          "Isa and Yahya",
          "Nuh and Hud",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-5",
        question: "What was his main call?",
        options: [
          "To worship Allah alone",
          "To build a temple",
          "To fight the neighbours",
          "To collect wealth",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-6",
        question: "What had the people turned to before him?",
        options: ["Idols", "Farming", "Trade", "Poetry"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-7",
        question: "What relationship did he have with Ilyas?",
        options: [
          "He was his companion and student",
          "He was his enemy",
          "He never met him",
          "He was his king",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-8",
        question: "How many times is he mentioned in the Qur'an?",
        options: ["Twice", "Once", "Seven times", "Never"],
        correctIndex: 0,
      },
      {
        id: "al-yasa-9",
        question: "What difficulty did he face?",
        options: [
          "The stubbornness of his people",
          "Loss of memory",
          "A long journey",
          "Loss of his kingdom",
        ],
        correctIndex: 0,
      },
      {
        id: "al-yasa-10",
        question: "What lesson does his story give us?",
        options: [
          "Every generation needs people who remind it of Allah",
          "Only famous people matter",
          "Teaching is easy",
          "Prophets did not have students",
        ],
        correctIndex: 0,
      },
    ],
  },
];
