import type { BuiltInLesson } from "../types";

export const PROPHETS_PART_1: BuiltInLesson[] = [
  {
    id: "adam",
    name: "Adam",
    arabicName: "آدَم",
    title: "The first human and the first prophet",
    emoji: "🌍",
    accent: "from-emerald-400 to-teal-500",
    summary:
      "Allah created Adam from clay, taught him the names of everything, and made him the first prophet.",
    story: [
      "Allah created Adam (peace be upon him) from clay and breathed life into him. He was the first human being and the father of all people. Allah taught Adam the names of everything, so his knowledge was greater than that of the angels. When Allah asked the angels to prostrate to Adam out of respect, they all obeyed except Iblis, who refused out of pride and was expelled from Allah's mercy.",
      "Adam lived in Paradise with his wife Hawwa (Eve). Allah allowed them to enjoy everything there but told them not to eat from one particular tree. Iblis whispered to them again and again, promising that the tree would make them live forever. In the end they ate from it, and they immediately realised they had disobeyed their Lord.",
      "Adam and Hawwa were sorry for what they had done. They turned to Allah with a beautiful dua, asking for forgiveness, and Allah forgave them. They were sent down to live on earth, where Adam became the first prophet, teaching his children to worship Allah alone. His story shows that everyone makes mistakes, but the person who repents sincerely is loved by Allah.",
    ],
    lessons: [
      "Pride is what destroyed Iblis — humility keeps our hearts clean.",
      "Knowledge is a gift from Allah and it raises a person's rank.",
      "When we slip, we repent straight away instead of despairing.",
    ],
    questions: [
      {
        id: "adam-1",
        question: "What was Adam (peace be upon him) created from?",
        options: ["Clay", "Light", "Fire", "Water only"],
        correctIndex: 0,
      },
      {
        id: "adam-2",
        question: "Which creature refused to prostrate to Adam?",
        options: ["Jibril", "Iblis", "Mikail", "A jinn who later believed"],
        correctIndex: 1,
      },
      {
        id: "adam-3",
        question: "Why did Iblis refuse to obey Allah's command?",
        options: [
          "He was confused",
          "He was afraid",
          "He was proud and arrogant",
          "He did not hear the command",
        ],
        correctIndex: 2,
      },
      {
        id: "adam-4",
        question: "What special knowledge did Allah give Adam?",
        options: [
          "The names of everything",
          "The ability to fly",
          "The language of animals only",
          "The future of every person",
        ],
        correctIndex: 0,
      },
      {
        id: "adam-5",
        question: "What was the name of Adam's wife?",
        options: ["Maryam", "Asiya", "Hawwa", "Sarah"],
        correctIndex: 2,
      },
      {
        id: "adam-6",
        question: "What did Allah tell Adam and Hawwa not to do in Paradise?",
        options: [
          "Not to speak to the angels",
          "Not to eat from one tree",
          "Not to leave their home",
          "Not to drink from the rivers",
        ],
        correctIndex: 1,
      },
      {
        id: "adam-7",
        question: "How did Iblis trick them?",
        options: [
          "He forced them",
          "He whispered and made false promises",
          "He changed the tree",
          "He hid the command from them",
        ],
        correctIndex: 1,
      },
      {
        id: "adam-8",
        question: "What did Adam and Hawwa do after their mistake?",
        options: [
          "They blamed each other",
          "They hid from Allah",
          "They repented and asked Allah for forgiveness",
          "They gave up hope",
        ],
        correctIndex: 2,
      },
      {
        id: "adam-9",
        question: "Did Allah accept Adam's repentance?",
        options: [
          "Yes, Allah forgave him",
          "No, never",
          "Only after many years of punishment",
          "The story does not say",
        ],
        correctIndex: 0,
      },
      {
        id: "adam-10",
        question: "Why is Adam called the first prophet?",
        options: [
          "He was the strongest man",
          "He built the first city",
          "He taught his children to worship Allah alone",
          "He wrote the first book",
        ],
        correctIndex: 2,
      },
    ],
  },
  {
    id: "idris",
    name: "Idris",
    arabicName: "إِدْرِيس",
    title: "The patient prophet raised to a high station",
    emoji: "📜",
    accent: "from-sky-400 to-indigo-500",
    summary:
      "Idris was known for truthfulness and patience, and Allah raised him to a high place.",
    story: [
      "Idris (peace be upon him) came after Adam, in a time when many people had started to forget the way of their father Adam. The Qur'an describes Idris with two beautiful qualities: he was truthful and he was patient. He never lied, and he never gave up when calling people to the worship of Allah.",
      "Idris spent his days worshipping Allah and teaching people. He is remembered as one of the earliest people to write with a pen and to study carefully the signs of Allah in the world. He reminded people that this life is short and that everything they do is recorded.",
      "Allah praised him in the Qur'an and said that He raised him to a high station. Because of his patience and truthfulness, his rank with Allah became very high. His story teaches us that steady worship, honesty and patience raise a believer even when the people around them are heedless.",
    ],
    lessons: [
      "Truthfulness in small things builds a trustworthy character.",
      "Patience with people is part of calling them to good.",
      "Allah raises those who are steady in worship.",
    ],
    questions: [
      {
        id: "idris-1",
        question: "Which two qualities does the Qur'an mention about Idris?",
        options: [
          "Truthfulness and patience",
          "Strength and wealth",
          "Speed and courage",
          "Kingship and power",
        ],
        correctIndex: 0,
      },
      {
        id: "idris-2",
        question: "When did Idris live?",
        options: [
          "After Adam",
          "After Musa",
          "At the same time as Isa",
          "After the Prophet Muhammad",
        ],
        correctIndex: 0,
      },
      {
        id: "idris-3",
        question: "What did Allah do for Idris because of his high character?",
        options: [
          "Gave him a kingdom",
          "Raised him to a high station",
          "Made him rich",
          "Gave him a large army",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-4",
        question: "What is Idris remembered for using early on?",
        options: ["The pen and writing", "The sword", "Ships", "Iron tools only"],
        correctIndex: 0,
      },
      {
        id: "idris-5",
        question: "What did Idris remind people about this life?",
        options: [
          "That it lasts forever",
          "That it is short and our deeds are recorded",
          "That only rich people succeed",
          "That it has no purpose",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-6",
        question: "How did Idris behave when people ignored his message?",
        options: [
          "He stopped calling them",
          "He stayed patient and continued",
          "He punished them",
          "He left the earth",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-7",
        question: "What did the people of his time begin to forget?",
        options: [
          "The way of Adam and the worship of Allah",
          "How to farm",
          "How to build houses",
          "Their own names",
        ],
        correctIndex: 0,
      },
      {
        id: "idris-8",
        question: "Being truthful means that a person:",
        options: [
          "Says what people like to hear",
          "Never lies",
          "Speaks only in public",
          "Stays silent always",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-9",
        question: "What raises a believer's rank according to this story?",
        options: [
          "Wealth and fame",
          "Patience, honesty and steady worship",
          "Winning arguments",
          "Having many followers",
        ],
        correctIndex: 1,
      },
      {
        id: "idris-10",
        question: "Idris was one of the prophets who:",
        options: [
          "Was sent only to one family",
          "Called his people to worship Allah alone",
          "Never spoke to anyone",
          "Refused prophethood",
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: "nuh",
    name: "Nuh",
    arabicName: "نُوح",
    title: "The prophet of the ark and the great flood",
    emoji: "🚢",
    accent: "from-blue-400 to-cyan-500",
    summary:
      "Nuh called his people for 950 years, then built an ark by Allah's command and was saved from the flood.",
    story: [
      "The people of Nuh (peace be upon him) had begun to worship idols made of stone and wood. Allah sent Nuh to warn them and to call them back to the worship of the One Lord. He called them day and night, in public and in private, for about 950 years. Only a small group believed; the rest mocked him, called him a liar, and even put their fingers in their ears so they would not hear him.",
      "Allah then commanded Nuh to build a huge ark. The people laughed as he built a ship far from any sea. When the ark was ready, Allah told Nuh to carry the believers and a pair of every kind of animal on board. Then water burst from the earth and poured from the sky, and a great flood covered the land.",
      "Nuh called out to his own son to come aboard, but the son refused and said he would climb a mountain instead. He drowned with the disbelievers. The ark floated safely and finally settled on Mount Judi. Nuh and the believers came down and thanked Allah. His story teaches patience over long years and that faith, not family name, is what saves a person.",
    ],
    lessons: [
      "Patience in doing good even when results take a long time.",
      "Obeying Allah can look strange to others — obey anyway.",
      "Faith is personal: being related to a righteous person is not enough.",
    ],
    questions: [
      {
        id: "nuh-1",
        question: "What were the people of Nuh worshipping?",
        options: ["Idols", "Angels", "The prophets", "Nothing at all"],
        correctIndex: 0,
      },
      {
        id: "nuh-2",
        question: "For roughly how long did Nuh call his people?",
        options: ["40 years", "100 years", "950 years", "10 years"],
        correctIndex: 2,
      },
      {
        id: "nuh-3",
        question: "How did most of his people respond?",
        options: [
          "They believed quickly",
          "They mocked him and refused to listen",
          "They asked for more proof and then believed",
          "They left the city",
        ],
        correctIndex: 1,
      },
      {
        id: "nuh-4",
        question: "What did Allah command Nuh to build?",
        options: ["A city", "A mosque", "An ark", "A wall"],
        correctIndex: 2,
      },
      {
        id: "nuh-5",
        question: "Who and what did Nuh take on board?",
        options: [
          "Only his family",
          "The believers and pairs of animals",
          "All the people of the town",
          "Only the animals",
        ],
        correctIndex: 1,
      },
      {
        id: "nuh-6",
        question: "How did the flood begin?",
        options: [
          "Water came from the earth and the sky",
          "A river changed direction",
          "The sea dried up",
          "Rain fell for one hour",
        ],
        correctIndex: 0,
      },
      {
        id: "nuh-7",
        question: "What happened to the son who refused to board?",
        options: [
          "He was saved on a mountain",
          "He drowned",
          "He believed at the last moment",
          "He built his own boat",
        ],
        correctIndex: 1,
      },
      {
        id: "nuh-8",
        question: "Where did the ark finally settle?",
        options: ["Mount Judi", "Mount Sinai", "Mount Uhud", "Mount Arafat"],
        correctIndex: 0,
      },
      {
        id: "nuh-9",
        question: "Why did the people laugh while Nuh was building?",
        options: [
          "He was building far from water",
          "He was building very slowly",
          "The wood was broken",
          "He was building at night",
        ],
        correctIndex: 0,
      },
      {
        id: "nuh-10",
        question: "What is the main lesson from the story of Nuh?",
        options: [
          "Patience in calling to Allah, and that faith saves a person",
          "Boats are important",
          "Rain is dangerous",
          "Long life is a reward",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "hud",
    name: "Hud",
    arabicName: "هُود",
    title: "The prophet sent to the mighty people of 'Ad",
    emoji: "🏜️",
    accent: "from-amber-400 to-orange-500",
    summary:
      "Hud warned the strong people of 'Ad about their pride, and they were destroyed by a fierce wind.",
    story: [
      "The people of 'Ad were tall, strong and skilled builders. They lived in a land of gardens and tall pillars, and they thought no one could ever defeat them. Their strength made them proud, and they worshipped idols instead of the One who had given them all that power.",
      "Allah sent them Hud (peace be upon him), a man from among themselves. He told them clearly: worship Allah alone, do not be arrogant, and remember the favours you have been given. They answered that he was foolish and that their idols would protect them. They challenged him to bring the punishment he warned them about.",
      "Then rain stopped falling and a cloud appeared. They were happy, thinking it would bring rain, but it carried a furious wind that blew for several days and nights. The proud people of 'Ad were destroyed, while Hud and the believers were saved by Allah's mercy. Their story warns us that strength and wealth are tests, not proof that Allah is pleased with us.",
    ],
    lessons: [
      "Strength and skill are gifts from Allah, not reasons for arrogance.",
      "Blessings should lead to gratitude, not heedlessness.",
      "Allah's help protects the believers even when they are few.",
    ],
    questions: [
      {
        id: "hud-1",
        question: "Which people was Hud sent to?",
        options: ["'Ad", "Thamud", "Madyan", "Bani Israil"],
        correctIndex: 0,
      },
      {
        id: "hud-2",
        question: "What were the people of 'Ad famous for?",
        options: [
          "Their strength and tall buildings",
          "Their ships",
          "Their books",
          "Their armies of elephants",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-3",
        question: "What was their main sin?",
        options: [
          "Arrogance and worshipping idols",
          "Farming badly",
          "Travelling too much",
          "Building houses",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-4",
        question: "Where did Hud come from?",
        options: [
          "From among the people of 'Ad themselves",
          "From another country",
          "From Egypt",
          "From Madyan",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-5",
        question: "What did Hud call them to do?",
        options: [
          "Worship Allah alone and leave arrogance",
          "Build higher towers",
          "Fight their neighbours",
          "Move to a new land",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-6",
        question: "How did they reply to Hud?",
        options: [
          "They called him foolish and trusted their idols",
          "They believed at once",
          "They asked him to lead them",
          "They stayed silent",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-7",
        question: "What did they think the cloud would bring?",
        options: ["Rain", "Birds", "Darkness", "Snow"],
        correctIndex: 0,
      },
      {
        id: "hud-8",
        question: "What was the punishment of 'Ad?",
        options: [
          "A furious wind",
          "A flood",
          "An earthquake",
          "A swarm of locusts",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-9",
        question: "What happened to Hud and the believers?",
        options: [
          "Allah saved them",
          "They were destroyed too",
          "They were taken prisoner",
          "They lost their faith",
        ],
        correctIndex: 0,
      },
      {
        id: "hud-10",
        question: "What lesson do we take from the people of 'Ad?",
        options: [
          "Power and wealth are tests from Allah",
          "Tall buildings are forbidden",
          "Wind is always a punishment",
          "Strong people are always wrong",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "salih",
    name: "Salih",
    arabicName: "صَالِح",
    title: "The prophet of Thamud and the she-camel",
    emoji: "🐪",
    accent: "from-rose-400 to-pink-500",
    summary:
      "Salih was sent to Thamud, who carved homes in mountains; they killed the she-camel sign and were destroyed.",
    story: [
      "Thamud came after 'Ad. They were clever people who carved beautiful homes into solid mountains and had plenty of water and crops. Like those before them, they worshipped idols and thought their skill made them safe from any harm.",
      "Allah sent Salih (peace be upon him) to call them to worship Allah alone. They asked him for a sign, so Allah sent a special she-camel. Salih told them that the camel must be left alone to drink and graze, and that they must not harm her. For a while they obeyed, but the arrogant leaders grew tired of the test and plotted against her.",
      "A group of them killed the she-camel and then dared Salih to bring the punishment. He told them they had only three days. On the third day a mighty blast and earthquake struck their homes, and the strong carved houses could not protect them. Salih and the believers were saved. Their story shows that clear signs mean nothing to a heart that refuses to be humble.",
    ],
    lessons: [
      "Signs from Allah must be honoured, not tested and mocked.",
      "Kindness to animals is part of taqwa.",
      "Clever people can still be foolish if they reject the truth.",
    ],
    questions: [
      {
        id: "salih-1",
        question: "Which people was Salih sent to?",
        options: ["Thamud", "'Ad", "Madyan", "Quraysh"],
        correctIndex: 0,
      },
      {
        id: "salih-2",
        question: "What were Thamud skilled at?",
        options: [
          "Carving houses in mountains",
          "Sailing ships",
          "Making paper",
          "Riding elephants",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-3",
        question: "What sign did Allah give them?",
        options: ["A she-camel", "A staff", "A cloud", "A river"],
        correctIndex: 0,
      },
      {
        id: "salih-4",
        question: "What were they told about the she-camel?",
        options: [
          "To leave her to drink and graze, and not harm her",
          "To ride her every day",
          "To sell her",
          "To keep her in a house",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-5",
        question: "What did the arrogant group do?",
        options: [
          "They killed the she-camel",
          "They hid her",
          "They followed Salih",
          "They freed her in the desert",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-6",
        question: "How long were they given after that?",
        options: ["Three days", "One year", "Forty days", "One hour"],
        correctIndex: 0,
      },
      {
        id: "salih-7",
        question: "What punishment came to Thamud?",
        options: [
          "A mighty blast and earthquake",
          "A flood",
          "A famine only",
          "A strong wind for eight days",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-8",
        question: "Did their carved homes protect them?",
        options: [
          "No, nothing could protect them",
          "Yes, they were safe inside",
          "Only the largest houses survived",
          "The story does not say",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-9",
        question: "What happened to Salih and the believers?",
        options: [
          "Allah saved them",
          "They were destroyed",
          "They stayed in the city",
          "They lost their faith",
        ],
        correctIndex: 0,
      },
      {
        id: "salih-10",
        question: "What lesson does the she-camel teach us?",
        options: [
          "To respect Allah's signs and be kind to animals",
          "To keep camels as pets",
          "To avoid mountains",
          "To dig more wells",
        ],
        correctIndex: 0,
      },
    ],
  },
];
